// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;
using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.ExternalSchema;

namespace BeneficialStrategies.Iso20022.Choices.ErrorHandling3Choice
{
    /// <summary>
    /// Specification of the error, in coded form.
    /// </summary>
    [IsoId("_RN4hYXhdEeidzqjNEfehPg")]
    [DisplayName("Code")]
    public record Code : ErrorHandling3Choice_
    {
        /// <summary>
        /// Contains the main value for the container.
        /// Specifies the error code as generated by the system in the response, as published in an external balance type code set.
        /// External code sets can be downloaded from www.iso20022.org.
        /// </summary>
        [IsoXmlTag("Cd")]
        public required ExternalSystemErrorHandling1Code Value { get; init; }
    }
}
