// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

// For source code clarity, the primative types used in this implementation are represented in source code as their ISO-declared types.
// Because too many were clashing with Microsoft framework types, all names are prefixed with 'Iso' for disambiguation.

// Global namespace usings required by generated code
global using System.ComponentModel;
global using System.Runtime.Serialization;
global using BeneficialStrategies.Iso20022.Amounts;
global using BeneficialStrategies.Iso20022.Codesets;
global using BeneficialStrategies.Iso20022.Framework;
global using BeneficialStrategies.Iso20022.Metadata;
#if NET8_0_OR_GREATER // C# 12 global type aliases
global using IsoMax35Text = System.String; // Text
global using IsoMax70Text = System.String; // Text
global using IsoMax140Text = System.String; // Text
global using IsoMax350Text = System.String; // Text
global using IsoMax16Text = System.String; // Text
global using IsoPhoneNumber = System.String; // Text
global using IsoMax256Text = System.String; // Text
global using IsoMax2048Text = System.String; // Text
global using IsoExtended350Code = System.String; // Text
global using IsoMax8Text = System.String; // Text
global using IsoExact4AlphaNumericText = System.String; // Text
global using IsoMax3Text = System.String; // Text
global using IsoMax4AlphaNumericText = System.String; // Text
global using IsoPreviousAll = System.String; // Text
global using IsoMax3NumericText = System.String; // Text
global using IsoMax10Text = System.String; // Text
global using IsoMax34Text = System.String; // Text
global using IsoMax5NumericText = System.String; // Text
global using IsoMax20000Text = System.String; // Text
global using IsoMax15NumericText = System.String; // Text
global using IsoMax210Text = System.String; // Text
global using IsoRestrictedFINXMax16Text = System.String; // Text
global using IsoRestrictedFINXMax35Text = System.String; // Text
global using IsoRestrictedFINXMax34Text = System.String; // Text
global using IsoRestrictedFINXMax210Text = System.String; // Text
global using IsoExact3NumericText = System.String; // Text
global using IsoISO20022MessageIdentificationText = System.String; // Text
global using IsoRestrictedFINXMax140Text = System.String; // Text
global using IsoRestrictedFINXMax31Text = System.String; // Text
global using IsoRestrictedFINExact2Text = System.String; // Text
global using IsoRestrictedFINXMax30Text = System.String; // Text
global using IsoRestrictedFINXMax350Text = System.String; // Text
global using IsoRestrictedFINMax30Text = System.String; // Text
global using IsoRestrictedFINMax8Text = System.String; // Text
global using IsoRestrictedFINX2Max34Text = System.String; // Text
global using IsoRestrictedFINXMax256Text = System.String; // Text
global using IsoExact3UpperCaseAlphaNumericText = System.String; // Text
global using IsoMax30Text = System.String; // Text
global using IsoMax8000Text = System.String; // Text
global using IsoRestrictedFINXMax70Text = System.String; // Text
global using IsoRestrictedFINZMax256Text = System.String; // Text
global using IsoRestrictedFINZMax8000Text = System.String; // Text
global using IsoMax6Text = System.String; // Text
global using IsoMax105Text = System.String; // Text
global using IsoRestrictedFINMax35Text = System.String; // Text
global using IsoMax60Text = System.String; // Text
global using IsoExact5NumericText = System.String; // Text
global using IsoExact4NumericText = System.String; // Text
global using IsoRestrictedFINXMax8Text = System.String; // Text
global using IsoRestrictedFINXMax24Text = System.String; // Text
global using IsoMax128Text = System.String; // Text
global using IsoMax4NumericText = System.String; // Text
global using IsoMax4Text = System.String; // Text
global using IsoMax15PlusSignedNumericText = System.String; // Text
global using IsoUnlimited9Text = System.String; // Text
global using IsoMax500Text = System.String; // Text
global using IsoMin8Max28NumericText = System.String; // Text
global using IsoMin2Max3NumericText = System.String; // Text
global using IsoExact1NumericText = System.String; // Text
global using IsoMin3Max4NumericText = System.String; // Text
global using IsoExternalLocalInstrumentCode_Obsolete = System.String; // Text
global using IsoMax1025Text = System.String; // Text
global using IsoMax2000Text = System.String; // Text
global using IsoRefused7Text = System.String; // Text
global using IsoExact42Text = System.String; // Text
global using IsoMax20Text = System.String; // Text
global using IsoMin3Max4Text = System.String; // Text
global using IsoMax9NumericText = System.String; // Text
global using IsoExact10Text = System.String; // Text
global using IsoMax35NumericText = System.String; // Text
global using IsoMax2NumericText = System.String; // Text
global using IsoMax45Text = System.String; // Text
global using IsoMin6Max8Text = System.String; // Text
global using IsoMax40Text = System.String; // Text
global using IsoMax12Text = System.String; // Text
global using IsoRestrictedMS02MS03CodeText = System.String; // Text
global using IsoRestrictedRR01CodeText = System.String; // Text
global using IsoRestrictedSEPACodeText = System.String; // Text
global using IsoRestrictedSMNDACodeText = System.String; // Text
global using IsoRestrictedB2BCORECodeText = System.String; // Text
global using IsoRestrictedRR01SL01CodeText = System.String; // Text
global using IsoRestrictedFINMax210Text = System.String; // Text
global using IsoRestrictedFINMax16Text = System.String; // Text
global using IsoRestrictedFINMax34Text = System.String; // Text
global using IsoRestrictedFINMax23Text = System.String; // Text
global using IsoRestrictedFINMax15Text = System.String; // Text
global using IsoRestrictedFINMax31Text = System.String; // Text
global using IsoExact7NumericText = System.String; // Text
global using IsoMax10NumericText = System.String; // Text
global using IsoExact32AlphaNumericText = System.String; // Text
global using IsoMax240Text = System.String; // Text
global using IsoMax50Text = System.String; // Text
global using IsoMax5AlphaNumericText = System.String; // Text
global using IsoMax450Text = System.String; // Text
global using IsoMax52Text = System.String; // Text
global using IsoMax15Text = System.String; // Text
global using IsoMax1000Text = System.String; // Text
global using IsoExact3AlphaNumericText = System.String; // Text
global using IsoMin2Max3AlphaText = System.String; // Text
global using IsoMax25Text = System.String; // Text
global using IsoMax15AlphaNumericText = System.String; // Text
global using IsoMax104Text = System.String; // Text
global using IsoMax37Text = System.String; // Text
global using IsoMax76Text = System.String; // Text
global using IsoMax13AlphaNumericText = System.String; // Text
global using IsoMax14Text = System.String; // Text
global using IsoMax14AlphaNumericText = System.String; // Text
global using IsoMax64Text = System.String; // Text
global using IsoMax20AlphaNumericText = System.String; // Text
global using IsoMax100AlphaNumericUnderscoreText = System.String; // Text
global using IsoMax38AlphaNumericText = System.String; // Text
global using IsoExact2NumericText = System.String; // Text
global using IsoMax5Text = System.String; // Text
global using IsoExact2AlphaNumericText = System.String; // Text
global using IsoRateSourceText = System.String; // Text
global using IsoMax6AlphaText = System.String; // Text
global using IsoDateOffsetText = System.String; // Text
global using IsoMax1850Text = System.String; // Text
global using IsoExact2UpperCaseAlphaText = System.String; // Text
global using IsoRestrictedFINXMax52Text = System.String; // Text
global using IsoRestrictedFINXMax25Text = System.String; // Text
global using IsoMax19NumericText = System.String; // Text
global using IsoMax6NumericText = System.String; // Text
global using IsoMax20KText = System.String; // Text
global using IsoMax12NumericText = System.String; // Text
global using IsoMax8NumericText = System.String; // Text
global using IsoExact12Text = System.String; // Text
global using IsoMax23NumericText = System.String; // Text
global using IsoExact15Text = System.String; // Text
global using IsoMax9999HexBinaryText = System.String; // Text
global using IsoMax10KText = System.String; // Text
global using IsoMax99Text = System.String; // Text
global using IsoMax11NumericText = System.String; // Text
global using IsoExact6AlphaNumericText = System.String; // Text
global using IsoMax4000Text = System.String; // Text
global using IsoMax32HexBinaryText = System.String; // Text
global using IsoExact1HexBinaryText = System.String; // Text
global using IsoMax10KHexBinaryText = System.String; // Text
global using IsoMax8HexBinaryText = System.String; // Text
global using IsoMax19HexBinaryText = System.String; // Text
global using IsoMax16HexBinaryText = System.String; // Text
global using IsoRestrictedFINZMax2048Text = System.String; // Text
global using IsoMax72Text = System.String; // Text
global using IsoMax100Text = System.String; // Text
global using IsoRestrictedFINXMax520Text = System.String; // Text
global using IsoExact4AlphaNumericUnderscoreText = System.String; // Text
global using IsoRestrictedFINMax50Text = System.String; // Text
global using IsoMax200Text = System.String; // Text
global using IsoMax512Text = System.String; // Text
global using IsoMax280Text = System.String; // Text
global using IsoGeographicPointInDecimalDegrees = System.String; // Text
global using IsoMax10MbText = System.String; // Text
global using IsoMax40KText = System.String; // Text
global using IsoISODateTime = System.DateTime; // DateTime
global using IsoISONormalisedDateTime = System.DateTime; // DateTime
global using IsoISODate = System.DateOnly; // Date
global using IsoISINIdentifier = System.String; // IdentifierSet
global using IsoBICFIIdentifier = System.String; // IdentifierSet
global using IsoBICIdentifier = System.String; // IdentifierSet
global using IsoIBAN2007Identifier = System.String; // IdentifierSet
global using IsoIBANIdentifier = System.String; // IdentifierSet
global using IsoBBANIdentifier = System.String; // IdentifierSet
global using IsoUPICIdentifier = System.String; // IdentifierSet
global using IsoAnyBICIdentifier = System.String; // IdentifierSet
global using IsoRICIdentifier = System.String; // IdentifierSet
global using IsoTickerIdentifier = System.String; // IdentifierSet
global using IsoBloombergIdentifier = System.String; // IdentifierSet
global using IsoConsolidatedTapeAssociationIdentifier = System.String; // IdentifierSet
global using IsoEuroclearClearstreamIdentifier = System.String; // IdentifierSet
global using IsoCHIPSUniversalIdentifier = System.String; // IdentifierSet
global using IsoNewZealandNCCIdentifier = System.String; // IdentifierSet
global using IsoIrishNSCIdentifier = System.String; // IdentifierSet
global using IsoUKDomesticSortCodeIdentifier = System.String; // IdentifierSet
global using IsoCHIPSParticipantIdentifier = System.String; // IdentifierSet
global using IsoSwissBCIdentifier = System.String; // IdentifierSet
global using IsoFedwireRoutingNumberIdentifier = System.String; // IdentifierSet
global using IsoPortugueseNCCIdentifier = System.String; // IdentifierSet
global using IsoRussianCentralBankIdentificationCodeIdentifier = System.String; // IdentifierSet
global using IsoItalianDomesticIdentifier = System.String; // IdentifierSet
global using IsoAustrianBankleitzahlIdentifier = System.String; // IdentifierSet
global using IsoCanadianPaymentsARNIdentifier = System.String; // IdentifierSet
global using IsoSwissSICIdentifier = System.String; // IdentifierSet
global using IsoGermanBankleitzahlIdentifier = System.String; // IdentifierSet
global using IsoSpanishDomesticInterbankingIdentifier = System.String; // IdentifierSet
global using IsoSouthAfricanNCCIdentifier = System.String; // IdentifierSet
global using IsoHongKongBankIdentifier = System.String; // IdentifierSet
global using IsoExtensiveBranchNetworkIdentifier = System.String; // IdentifierSet
global using IsoSmallNetworkIdentifier = System.String; // IdentifierSet
global using IsoSEDOLIdentifier = System.String; // IdentifierSet
global using IsoCUSIPIdentifier = System.String; // IdentifierSet
global using IsoQUICKIdentifier = System.String; // IdentifierSet
global using IsoWertpapierIdentifier = System.String; // IdentifierSet
global using IsoDutchIdentifier = System.String; // IdentifierSet
global using IsoValorenIdentifier = System.String; // IdentifierSet
global using IsoSicovamIdentifier = System.String; // IdentifierSet
global using IsoBelgianIdentifier = System.String; // IdentifierSet
global using IsoEntryTypeIdentifier = System.String; // IdentifierSet
global using IsoBICNonFIIdentifier = System.String; // IdentifierSet
global using IsoIBEIIdentifier = System.String; // IdentifierSet
global using IsoBEIIdentifier = System.String; // IdentifierSet
global using IsoEANGLNIdentifier = System.String; // IdentifierSet
global using IsoDunsIdentifier = System.String; // IdentifierSet
global using IsoMICIdentifier = System.String; // IdentifierSet
global using IsoCFIIdentifier = System.String; // IdentifierSet
global using IsoRatingValueIdentifier = System.String; // IdentifierSet
global using IsoLEIIdentifier = System.String; // IdentifierSet
global using IsoIndianFinancialSystemCodeIdentifier = System.String; // IdentifierSet
global using IsoHellenicBankIdentificationCodeIdentifier = System.String; // IdentifierSet
global using IsoPolishNationalClearingCodeIdentifier = System.String; // IdentifierSet
global using IsoSNA2008SectorIdentifier = System.String; // IdentifierSet
global using IsoEICIdentifier = System.String; // IdentifierSet
global using IsoNACEDomainIdentifier = System.String; // IdentifierSet
global using IsoISINOct2015Identifier = System.String; // IdentifierSet
global using IsoCFIOct2015Identifier = System.String; // IdentifierSet
global using IsoBloomberg2Identifier = System.String; // IdentifierSet
global using IsoAnyBICDec2014Identifier = System.String; // IdentifierSet
global using IsoBICFIDec2014Identifier = System.String; // IdentifierSet
global using IsoBICNonFIDec2014Identifier = System.String; // IdentifierSet
global using IsoUUIDv4Identifier = System.String; // IdentifierSet
global using IsoELFIdentifier = System.String; // IdentifierSet
global using IsoISICIdentifier = System.String; // IdentifierSet
global using IsoMerchantCategoryCodeIdentifier = System.String; // IdentifierSet
global using IsoUTIIdentifier = System.String; // IdentifierSet
global using IsoISIN2021Identifier = System.String; // IdentifierSet
global using IsoDTI2021Identifier = System.String; // IdentifierSet
global using IsoYesNoIndicator = System.String; // IndicatorSet
global using IsoPlusOrMinusIndicator = System.String; // IndicatorSet
global using IsoRequestedIndicator = System.String; // IndicatorSet
global using IsoTrueFalseIndicator = System.String; // IndicatorSet
global using IsoPaymentDirectionIndicator = System.String; // IndicatorSet
global using IsoAllOrNoneIndicator = System.String; // IndicatorSet
global using IsoChargeIncludedIndicator = System.String; // IndicatorSet
global using IsoBatchBookingIndicator = System.String; // IndicatorSet
global using IsoGroupingIndicator = System.String; // IndicatorSet
global using IsoGroupCancellationIndicator = System.String; // IndicatorSet
global using IsoIdentificationVerificationIndicator = System.String; // IndicatorSet
global using IsoAMLIndicator = System.String; // IndicatorSet
global using IsoOverrideIndicator = System.String; // IndicatorSet
global using IsoDirectionIndicator = System.String; // IndicatorSet
global using IsoNumber = System.UInt64; // Quantity
global using IsoDecimalNumber = System.UInt64; // Quantity
global using IsoMax3Number = System.UInt64; // Quantity
global using IsoRestrictedFINDecimalNumber = System.UInt64; // Quantity
global using IsoNonNegativeDecimalNumber = System.UInt64; // Quantity
global using IsoLongDecimalNumber = System.UInt64; // Quantity
global using IsoRestrictedMonthExact2Number = System.UInt64; // Quantity
global using IsoPositiveNumber = System.UInt64; // Quantity
global using IsoMax5Number = System.UInt64; // Quantity
global using IsoMax1Number = System.UInt64; // Quantity
global using IsoDecimalNumberFraction5 = System.UInt64; // Quantity
global using IsoLongFraction21DecimalNumber = System.UInt64; // Quantity
global using IsoNonNegativeFraction5DecimalNumber = System.UInt64; // Quantity
global using IsoNonNegativeNumber = System.UInt64; // Quantity
global using IsoMax20PositiveNumber = System.UInt64; // Quantity
global using IsoMax20PositiveDecimalNumber = System.UInt64; // Quantity
global using IsoMax6NumberFraction2 = System.UInt64; // Quantity
global using IsoMax10NumberFraction2 = System.UInt64; // Quantity
global using IsoFraction5DecimalNumber = System.UInt64; // Quantity
global using IsoMax2Fraction1NonNegativeNumber = System.UInt64; // Quantity
global using IsoLongFraction19DecimalNumber = System.UInt64; // Quantity
global using IsoDayOfMonthNumber = System.UInt64; // Quantity
global using IsoMax30DecimalNumber = System.UInt64; // Quantity
global using IsoMax5PositiveNumber = System.UInt64; // Quantity
global using IsoMax10PositiveNumber = System.UInt64; // Quantity
global using IsoISOTime = System.TimeOnly; // Time
global using IsoPercentageRate = System.Decimal; // Rate
global using IsoPercentageBoundedRate = System.Decimal; // Rate
global using IsoBaseOneRate = System.Decimal; // Rate
global using IsoBaseOne14Rate = System.Decimal; // Rate
global using IsoPercentage = System.Decimal; // Rate
global using IsoBaseOne18Rate = System.Decimal; // Rate
global using IsoBaseOne25Rate = System.Decimal; // Rate
global using IsoISOYearMonth = System.UInt16; // YearMonth
global using IsoISOYear = System.UInt16; // Year
global using IsoISORestrictedYear = System.UInt16; // Year
global using IsoMax10KBinary = System.Byte[]; // Binary
global using IsoMax2MBBinary = System.Byte[]; // Binary
global using IsoMax10000Binary = System.Byte[]; // Binary
global using IsoMax3000Binary = System.Byte[]; // Binary
global using IsoMax35Binary = System.Byte[]; // Binary
global using IsoMax500Binary = System.Byte[]; // Binary
global using IsoMax140Binary = System.Byte[]; // Binary
global using IsoMin5Max16Binary = System.Byte[]; // Binary
global using IsoMax5000Binary = System.Byte[]; // Binary
global using IsoMax100KBinary = System.Byte[]; // Binary
global using IsoMax2KBinary = System.Byte[]; // Binary
global using IsoMax50Binary = System.Byte[]; // Binary
global using IsoMax4kBinary = System.Byte[]; // Binary
global using IsoMax1kBinary = System.Byte[]; // Binary
global using IsoMax10MbBinary = System.Byte[]; // Binary
global using IsoMin1Max256Binary = System.Byte[]; // Binary
global using IsoMax20MbBinary = System.Byte[]; // Binary
global using IsoanySimpleType = System.String; // Schema
global using IsoanyURI = System.String; // Schema
global using Isobase64Binary = System.String; // Schema
global using Isoboolean = System.String; // Schema
global using Isobyte = System.String; // Schema
global using Isodate = System.String; // Schema
global using IsodateTime = System.String; // Schema
global using Isodecimal = System.String; // Schema
global using Isodouble = System.String; // Schema
global using Isoduration = System.String; // Schema
global using IsoENTITIES = System.String; // Schema
global using IsoENTITY = System.String; // Schema
global using Isofloat = System.String; // Schema
global using IsogDay = System.String; // Schema
global using IsogMonth = System.String; // Schema
global using IsogMonthDay = System.String; // Schema
global using IsogYear = System.String; // Schema
global using IsogYearMonth = System.String; // Schema
global using IsohexBinary = System.String; // Schema
global using IsoID = System.String; // Schema
global using IsoIDREF = System.String; // Schema
global using IsoIDREFS = System.String; // Schema
global using Isoint = System.String; // Schema
global using Isointeger = System.String; // Schema
global using Isolanguage = System.String; // Schema
global using Isolong = System.String; // Schema
global using IsoName = System.String; // Schema
global using IsoNCName = System.String; // Schema
global using IsonegativeInteger = System.String; // Schema
global using IsoNMTOKEN = System.String; // Schema
global using IsoNMTOKENS = System.String; // Schema
global using IsononNegativeInteger = System.String; // Schema
global using IsononPositiveInteger = System.String; // Schema
global using IsonormalizedString = System.String; // Schema
global using IsopositiveInteger = System.String; // Schema
global using IsoQName = System.String; // Schema
global using Isoshort = System.String; // Schema
global using Isostring = System.String; // Schema
global using Isotime = System.String; // Schema
global using Isotoken = System.String; // Schema
global using IsounsignedByte = System.String; // Schema
global using IsounsignedInt = System.String; // Schema
global using IsounsignedLong = System.String; // Schema
global using IsounsignedShort = System.String; // Schema
global using IsoISOMonth = System.Byte; // Month
global using IsoDTI2024Identifier = System.String; // IdentifierSet
global using IsoExact4UpperCaseAlphaText = System.String; // Text
global using IsoHexBinaryText = System.String; // Text
global using IsoMax10DateText = System.String; // Text
global using IsoMax47Text = System.String; // Text
global using IsoNACEDomain2025Identifier = System.String; // IdentifierSet
global using IsoNPIIdentifier = System.String; // IdentifierSet
global using IsoPercentage14Rate = System.Decimal; // Rate
global using IsoSHA256SignatureText = System.String; // Text
// External Codesets
global using CountryCode = System.String;
global using CurrencyCode = System.String;
global using ActiveCurrencyCode = System.String;
global using ActiveOrHistoricCurrencyCode = System.String;
global using LanguageCode = System.String;
global using NationalityCode = System.String;
global using ExternalClearingSystemMemberCode = System.String;
global using ExternalFinancialInstitutionIdentification1Code = System.String;
global using ExternalCommunicationFormat1Code = System.String;
global using ExternalBankTransactionDomainCode = System.String;
global using ExternalBankTransactionFamilyCode = System.String;
global using ExternalBankTransactionSubFamilyCode = System.String;
global using ExternalBankTransactionDomain1Code = System.String;
global using ExternalBankTransactionFamily1Code = System.String;
global using ExternalBankTransactionSubFamily1Code = System.String;
global using ExternalPurposeCode_Obsolete = System.String;
global using ExternalCardTransactionCategory1Code = System.String;
global using ExternalCode = System.String;
global using ISO2ALanguageCode = System.String;
global using ISO3ACountryCode = System.String;
global using ISO3NumericCountryCode = System.String;
global using UnicodeChartsCode = System.String;
global using BusinessMessagePriorityCode = System.String;
global using ExternalDiscrepancyCode = System.String;
global using ExternalDiscrepancy1Code = System.String;
global using ExternalFinancialInstrumentProductType1Code = System.String;
global using ExternalCardTransactionCategoryCode = System.String;
global using ExternalClearingSystemMember1Code = System.String;
global using EuroCurrencyCode = System.String;
global using ExternalMandateSetupReason1Code = System.String;
global using ExternalMandateSetupReasonCode = System.String;
global using ExternalTechnicalError1Code = System.String;
global using ExternalTechnicalErrorCode = System.String;
global using CountrySubDivisionCode = System.String;
global using ExternalSystemEvent1Code = System.String;
global using ExternalFinancialInstitutionIdentificationCode = System.String;
global using ExternalCommunicationFormatCode = System.String;
global using ExternalFinancialInstrumentProductTypeCode = System.String;
global using ExternalCreditLineType1Code = System.String;
global using ExternalCreditLineTypeCode = System.String;
global using ExternalSecuritiesLendingTypeCode = System.String;
global using ExternalSecuritiesLendingType1Code = System.String;
global using ExternalInvalidEventReason1Code = System.String;
global using ExternalInvalidPaymentsEvent1Code = System.String;
global using ExternalInvalidPaymentsEventCode = System.String;
global using ExternalInvalidEventReasonCode = System.String;
global using ExternalSystemPartyType1Code = System.String;
global using ParentCurrencyCode = System.String;
global using ExternalSystemPartyTypeCode = System.String;
global using ISO3NumericCurrencyCode = System.String;
global using ExternalDebtorAgentInstruction1Code = System.String;
global using ExternalTrackertAlertStatus1Code = System.String;
global using ExternalTrackerAlertStatusReason1Code = System.String;
global using ExternalTrackerAlertStatusReasonCode = System.String;
global using ExternalTrackertAlertStatusCode = System.String;
global using ExternalChequeAgentInstruction1Code = System.String;
global using ExternalChequeCancellationStatus1Code = System.String;
global using ExternalChequeCancellationReason1Code = System.String;
global using ExternalInstructedAgentInstruction1Code = System.String;
global using ExternalChequeCancellationStatusCode = System.String;
global using ExternalInstructedAgentInstructionCode = System.String;
global using ExternalChequeAgentInstructionCode = System.String;
global using ExternalChequeCancellationReasonCode = System.String;
global using ExternalSecuritiesUpdateReason1Code = System.String;
global using ExternalSecuritiesUpdateReasonCode = System.String;
global using ExternalNotificationCancellationReason1Code = System.String;
global using ExternalNotificationCancellationReasonCode = System.String;
global using ISO8583TransactionTypeCode = System.String;
global using ISO8583MessageReasonCode = System.String;
global using ISO8583AmountTypeCode = System.String;
global using ISOMax3ACountryCode = System.String;
global using ISOMax3ALanguageCode = System.String;
global using ISO8583ResponseCode = System.String;
global using ISO18245MerchantCategoryCode = System.String;
global using ExternalAuthenticationMethod1Code = System.String;
global using ISOCountrySubDivisionCode = System.String;
global using ISO8583AccountTypeCode = System.String;
global using ExternalAuthenticationMethodCode = System.String;
global using ExternalPartyRelationshipType1Code = System.String;
global using ExternalPartyRelationshipTypeCode = System.String;
global using ExternalTrackerInvestigationStatusReason1Code = System.String;
global using ExternalTrackerInvestigationStatus1Code = System.String;
global using ExternalTrackerInvestigationType1Code = System.String;
global using ExternalTrackerInvestigationStatusCode = System.String;
global using ExternalTrackerInvestigationStatusReasonCode = System.String;
global using ExternalTrackerInvestigationTypeCode = System.String;
global using ExternalIndustrySectorClassification1Code = System.String;
global using ExternalIndustrySectorClassificationCode = System.String;
global using ExternalInvestigationAction1Code = System.String;
global using ExternalInvestigationActionCode = System.String;
global using ExternalInvestigationActionReason1Code = System.String;
global using ExternalInvestigationActionReasonCode = System.String;
global using ExternalInvestigationInstrument1Code = System.String;
global using ExternalInvestigationInstrumentCode = System.String;
global using ExternalInvestigationReason1Code = System.String;
global using ExternalInvestigationReasonCode = System.String;
global using ExternalInvestigationReasonSubType1Code = System.String;
global using ExternalInvestigationReasonSubTypeCode = System.String;
global using ExternalInvestigationServiceLevel1Code = System.String;
global using ExternalInvestigationServiceLevelCode = System.String;
global using ExternalInvestigationStatus1Code = System.String;
global using ExternalInvestigationStatusCode = System.String;
global using ExternalInvestigationStatusReason1Code = System.String;
global using ExternalInvestigationStatusReasonCode = System.String;
global using ExternalInvestigationSubType1Code = System.String;
global using ExternalInvestigationSubTypeCode = System.String;
global using ExternalInvestigationType1Code = System.String;
global using ExternalInvestigationTypeCode = System.String;
global using ExternalLegalFramework1Code = System.String;
global using ExternalLegalFrameworkCode = System.String;
global using ExternalMessageFunction1Code = System.String;
global using ExternalMessageFunctionCode = System.String;
global using ExternalNotificationSubType1Code = System.String;
global using ExternalNotificationSubTypeCode = System.String;
global using ExternalNotificationType1Code = System.String;
global using ExternalNotificationTypeCode = System.String;
global using ExternalPostTradeEventType1Code = System.String;
global using ExternalPostTradeEventTypeCode = System.String;
global using ExternalProductType1Code = System.String;
global using ExternalProductTypeCode = System.String;
global using ExternalRegulatoryInformationType1Code = System.String;
global using ExternalRegulatoryInformationTypeCode = System.String;
global using ExternalTrackerNotificationSubTypeCode = System.String;
global using ExternalTrackerNotificationTypeCode = System.String;
global using FXTradeConfirmationStatusCode = System.String;
global using FailureReason9Code = System.String;
global using FundingSourceType3Code = System.String;
global using InstalmentAmountDetailsType3Code = System.String;
global using InterestRateIndexTenorCode = System.String;
global using InvestigationLocationMethod1Code = System.String;
global using InvestigationLocationMethodCode = System.String;
global using LanguageVersion1Code = System.String;
global using LanguageVersionCode = System.String;
global using MOTO2Code = System.String;
global using MOTOV2Code = System.String;
global using NonEligibleProceedsIndicator2Code = System.String;
global using OfferType5Code = System.String;
global using OptionDefinitionType1Code = System.String;
global using OrderEventType1Code = System.String;
global using OrderEventTypeCode = System.String;
global using OrderRestrictionType1Code = System.String;
global using OrderRestrictionTypeCode = System.String;
global using OrderStatus10Code = System.String;
global using OrderStatus11Code = System.String;
global using OrderType3Code = System.String;
global using POIComponentType7Code = System.String;
global using PartyExceptionType1Code = System.String;
global using PartyExceptionTypeCode = System.String;
global using PartyRole4Code = System.String;
global using PassiveOrAgressiveType1Code = System.String;
global using PassiveOrAgressiveTypeCode = System.String;
global using PaymentInstrumentType2Code = System.String;
global using PreferredContactMethod2Code = System.String;
global using PriceCalculationMethod1Code = System.String;
global using PriceCalculationMethodCode = System.String;
global using ProcessedStatus7Code = System.String;
global using PurchaseIdentifierType2Code = System.String;
global using RedemptionAnnouncementNoticeType1Code = System.String;
global using RedemptionAnnouncementNoticeTypeCode = System.String;
global using Response12Code = System.String;
global using ResultDetail5Code = System.String;
global using ReturnedStatus1Code = System.String;
global using ReturnedStatusCode = System.String;
global using SettlementDate8Code = System.String;
global using SettlementDateV2Code = System.String;
global using Side6Code = System.String;
global using SoftwareType1Code = System.String;
global using SoftwareTypeCode = System.String;
global using Status11Code = System.String;
global using TransferOfProceedsType1Code = System.String;
global using TransferOfProceedsTypeCode = System.String;
global using ValidityPeriodType1Code = System.String;
global using ValidityPeriodTypeCode = System.String;
#endif
