// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

// For source code clarity, the primative types used in this implementation are represented in source code as their ISO-declared types.
// Because too many were clashing with Microsoft framework types, all names are prefixed with 'Iso' for disambiguation.

// Global namespace usings required by generated code
global using System.ComponentModel;
global using System.Runtime.Serialization;
global using System.Text.Json.Serialization;
global using BeneficialStrategies.Iso20022.Amounts;
global using BeneficialStrategies.Iso20022.Codesets;
global using BeneficialStrategies.Iso20022.SimpleTypes;
// IsoMax*Text aliases — redirect to validated structs in SimpleTypes namespace
// IsoRestrictedFINX* aliases — redirect to validated structs
// IsoRestrictedFIN* and IsoRestrictedFINZ* aliases
// Indicator aliases — boolean true/false wire types
// Identifier and financial-code aliases
global using IsoBICFIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BICFIIdentifier;
global using IsoBICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BICIdentifier;
global using IsoBICNonFIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BICNonFIIdentifier;
global using IsoAnyBICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.AnyBICIdentifier;
global using IsoBEIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BEIIdentifier;
global using IsoBICFIDec2014Identifier = BeneficialStrategies.Iso20022.SimpleTypes.BICFIDec2014Identifier;
global using IsoBICNonFIDec2014Identifier = BeneficialStrategies.Iso20022.SimpleTypes.BICNonFIDec2014Identifier;
global using IsoAnyBICDec2014Identifier = BeneficialStrategies.Iso20022.SimpleTypes.AnyBICDec2014Identifier;
global using IsoIBANIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.IBANIdentifier;
global using IsoIBAN2007Identifier = BeneficialStrategies.Iso20022.SimpleTypes.IBAN2007Identifier;
global using IsoBBANIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BBANIdentifier;
global using IsoAustrianBankleitzahlIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.AustrianBankleitzahlIdentifier;
global using IsoCanadianPaymentsARNIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.CanadianPaymentsARNIdentifier;
global using IsoCHIPSParticipantIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.CHIPSParticipantIdentifier;
global using IsoCHIPSUniversalIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.CHIPSUniversalIdentifier;
global using IsoExtensiveBranchNetworkIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ExtensiveBranchNetworkIdentifier;
global using IsoFedwireRoutingNumberIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.FedwireRoutingNumberIdentifier;
global using IsoGermanBankleitzahlIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.GermanBankleitzahlIdentifier;
global using IsoHellenicBankIdentificationCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.HellenicBankIdentificationCodeIdentifier;
global using IsoHongKongBankIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.HongKongBankIdentifier;
global using IsoIndianFinancialSystemCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.IndianFinancialSystemCodeIdentifier;
global using IsoIrishNSCIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.IrishNSCIdentifier;
global using IsoItalianDomesticIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ItalianDomesticIdentifier;
global using IsoNewZealandNCCIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.NewZealandNCCIdentifier;
global using IsoPolishNationalClearingCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.PolishNationalClearingCodeIdentifier;
global using IsoPortugueseNCCIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.PortugueseNCCIdentifier;
global using IsoRussianCentralBankIdentificationCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.RussianCentralBankIdentificationCodeIdentifier;
global using IsoSmallNetworkIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SmallNetworkIdentifier;
global using IsoSouthAfricanNCCIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SouthAfricanNCCIdentifier;
global using IsoSpanishDomesticInterbankingIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SpanishDomesticInterbankingIdentifier;
global using IsoSwissBCIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SwissBCIdentifier;
global using IsoSwissSICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SwissSICIdentifier;
global using IsoUKDomesticSortCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.UKDomesticSortCodeIdentifier;
global using IsoISINIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ISINIdentifier;
global using IsoISINOct2015Identifier = BeneficialStrategies.Iso20022.SimpleTypes.ISINOct2015Identifier;
global using IsoISIN2021Identifier = BeneficialStrategies.Iso20022.SimpleTypes.ISIN2021Identifier;
global using IsoLEIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.LEIIdentifier;
global using IsoMICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.MICIdentifier;
global using IsoCFIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.CFIIdentifier;
global using IsoCFIOct2015Identifier = BeneficialStrategies.Iso20022.SimpleTypes.CFIOct2015Identifier;
global using IsoELFIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ELFIdentifier;
global using IsoEICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.EICIdentifier;
global using IsoIBEIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.IBEIIdentifier;
global using IsoISICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ISICIdentifier;
global using IsoUPICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.UPICIdentifier;
global using IsoDunsIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.DunsIdentifier;
global using IsoEANGLNIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.EANGLNIdentifier;
global using IsoMerchantCategoryCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.MerchantCategoryCodeIdentifier;
global using IsoNACEDomainIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.NACEDomainIdentifier;
global using IsoNACEDomain2025Identifier = BeneficialStrategies.Iso20022.SimpleTypes.NACEDomain2025Identifier;
global using IsoBloomberg2Identifier = BeneficialStrategies.Iso20022.SimpleTypes.Bloomberg2Identifier;
global using IsoDTI2021Identifier = BeneficialStrategies.Iso20022.SimpleTypes.DTI2021Identifier;
global using IsoDTI2024Identifier = BeneficialStrategies.Iso20022.SimpleTypes.DTI2024Identifier;
global using IsoEntryTypeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.EntryTypeIdentifier;
global using IsoUUIDv4Identifier = BeneficialStrategies.Iso20022.SimpleTypes.UUIDv4Identifier;
global using IsoUTIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.UTIIdentifier;
global using IsoISO20022MessageIdentificationText = BeneficialStrategies.Iso20022.SimpleTypes.ISO20022MessageIdentificationText;
global using IsoBloombergIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BloombergIdentifier;
global using IsoConsolidatedTapeAssociationIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ConsolidatedTapeAssociationIdentifier;
global using IsoEuroclearClearstreamIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.EuroclearClearstreamIdentifier;
global using IsoRICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.RICIdentifier;
global using IsoTickerIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.TickerIdentifier;
global using IsoYesNoIndicator = BeneficialStrategies.Iso20022.SimpleTypes.YesNoIndicator;
global using IsoTrueFalseIndicator = BeneficialStrategies.Iso20022.SimpleTypes.TrueFalseIndicator;
global using IsoPlusOrMinusIndicator = BeneficialStrategies.Iso20022.SimpleTypes.PlusOrMinusIndicator;
global using IsoAllOrNoneIndicator = BeneficialStrategies.Iso20022.SimpleTypes.AllOrNoneIndicator;
global using IsoAMLIndicator = BeneficialStrategies.Iso20022.SimpleTypes.AMLIndicator;
global using IsoBatchBookingIndicator = BeneficialStrategies.Iso20022.SimpleTypes.BatchBookingIndicator;
global using IsoChargeIncludedIndicator = BeneficialStrategies.Iso20022.SimpleTypes.ChargeIncludedIndicator;
global using IsoGroupCancellationIndicator = BeneficialStrategies.Iso20022.SimpleTypes.GroupCancellationIndicator;
global using IsoGroupingIndicator = BeneficialStrategies.Iso20022.SimpleTypes.GroupingIndicator;
global using IsoIdentificationVerificationIndicator = BeneficialStrategies.Iso20022.SimpleTypes.IdentificationVerificationIndicator;
global using IsoOverrideIndicator = BeneficialStrategies.Iso20022.SimpleTypes.OverrideIndicator;
global using IsoPaymentDirectionIndicator = BeneficialStrategies.Iso20022.SimpleTypes.PaymentDirectionIndicator;
global using IsoRequestedIndicator = BeneficialStrategies.Iso20022.SimpleTypes.RequestedIndicator;
global using IsoRestrictedFINMax8Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax8Text;
global using IsoRestrictedFINMax15Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax15Text;
global using IsoRestrictedFINMax16Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax16Text;
global using IsoRestrictedFINMax23Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax23Text;
global using IsoRestrictedFINMax30Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax30Text;
global using IsoRestrictedFINMax31Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax31Text;
global using IsoRestrictedFINMax34Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax34Text;
global using IsoRestrictedFINMax35Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax35Text;
global using IsoRestrictedFINMax50Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax50Text;
global using IsoRestrictedFINMax210Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax210Text;
global using IsoRestrictedFINZMax256Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINZMax256Text;
global using IsoRestrictedFINZMax2048Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINZMax2048Text;
global using IsoRestrictedFINZMax8000Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINZMax8000Text;
global using IsoRestrictedFINXMax8Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax8Text;
global using IsoRestrictedFINXMax16Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax16Text;
global using IsoRestrictedFINXMax24Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax24Text;
global using IsoRestrictedFINXMax25Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax25Text;
global using IsoRestrictedFINXMax30Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax30Text;
global using IsoRestrictedFINXMax31Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax31Text;
global using IsoRestrictedFINXMax34Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax34Text;
global using IsoRestrictedFINXMax35Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax35Text;
global using IsoRestrictedFINXMax52Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax52Text;
global using IsoRestrictedFINXMax70Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax70Text;
global using IsoRestrictedFINXMax140Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax140Text;
global using IsoRestrictedFINXMax210Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax210Text;
global using IsoRestrictedFINXMax256Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax256Text;
global using IsoRestrictedFINXMax350Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax350Text;
global using IsoRestrictedFINXMax520Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax520Text;
global using IsoRestrictedFINX2Max34Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINX2Max34Text;
// IsoXxx aliases for Groups A/B/C/D pattern-restricted simple types
global using IsoMax2NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max2NumericText;
global using IsoMax3NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max3NumericText;
global using IsoMax4NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max4NumericText;
global using IsoMax5NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max5NumericText;
global using IsoMax6NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max6NumericText;
global using IsoMax8NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max8NumericText;
global using IsoMax9NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max9NumericText;
global using IsoMax10NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max10NumericText;
global using IsoMax11NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max11NumericText;
global using IsoMax12NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max12NumericText;
global using IsoMax15NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max15NumericText;
global using IsoMax19NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max19NumericText;
global using IsoMax23NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max23NumericText;
global using IsoMax35NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max35NumericText;
global using IsoExact1NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact1NumericText;
global using IsoExact2NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact2NumericText;
global using IsoExact3NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact3NumericText;
global using IsoExact4NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact4NumericText;
global using IsoExact5NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact5NumericText;
global using IsoExact7NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact7NumericText;
global using IsoExact14NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact14NumericText;
global using IsoMin2Max3NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Min2Max3NumericText;
global using IsoMin3Max4NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Min3Max4NumericText;
global using IsoMin8Max28NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Min8Max28NumericText;
global using IsoMax15PlusSignedNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max15PlusSignedNumericText;
global using IsoMax4AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max4AlphaNumericText;
global using IsoMax5AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max5AlphaNumericText;
global using IsoMax15AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max15AlphaNumericText;
global using IsoMax20AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max20AlphaNumericText;
global using IsoExact2AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact2AlphaNumericText;
global using IsoExact3AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact3AlphaNumericText;
global using IsoExact4AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact4AlphaNumericText;
global using IsoExact32AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact32AlphaNumericText;
global using IsoExact1Text = BeneficialStrategies.Iso20022.SimpleTypes.Exact1Text;
global using IsoExact10Text = BeneficialStrategies.Iso20022.SimpleTypes.Exact10Text;
global using IsoExact12Text = BeneficialStrategies.Iso20022.SimpleTypes.Exact12Text;
global using IsoExact15Text = BeneficialStrategies.Iso20022.SimpleTypes.Exact15Text;
global using IsoExact42Text = BeneficialStrategies.Iso20022.SimpleTypes.Exact42Text;
global using IsoExact2UpperCaseAlphaText = BeneficialStrategies.Iso20022.SimpleTypes.Exact2UpperCaseAlphaText;
global using IsoExact3UpperCaseAlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact3UpperCaseAlphaNumericText;
global using IsoExact1AlphaText = BeneficialStrategies.Iso20022.SimpleTypes.Exact1AlphaText;
global using IsoExact6AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact6AlphaNumericText;
global using IsoExact4AlphaNumericUnderscoreText = BeneficialStrategies.Iso20022.SimpleTypes.Exact4AlphaNumericUnderscoreText;
global using IsoRestrictedFINExact2Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINExact2Text;
global using IsoExact1HexBinaryText = BeneficialStrategies.Iso20022.SimpleTypes.Exact1HexBinaryText;
global using IsoMax3Text = BeneficialStrategies.Iso20022.SimpleTypes.Max3Text;
global using IsoMax4Text = BeneficialStrategies.Iso20022.SimpleTypes.Max4Text;
global using IsoMax6Text = BeneficialStrategies.Iso20022.SimpleTypes.Max6Text;
global using IsoMax8Text = BeneficialStrategies.Iso20022.SimpleTypes.Max8Text;
global using IsoMax10Text = BeneficialStrategies.Iso20022.SimpleTypes.Max10Text;
global using IsoMax12Text = BeneficialStrategies.Iso20022.SimpleTypes.Max12Text;
global using IsoMax15Text = BeneficialStrategies.Iso20022.SimpleTypes.Max15Text;
global using IsoMax16Text = BeneficialStrategies.Iso20022.SimpleTypes.Max16Text;
global using IsoMax20Text = BeneficialStrategies.Iso20022.SimpleTypes.Max20Text;
global using IsoMax25Text = BeneficialStrategies.Iso20022.SimpleTypes.Max25Text;
global using IsoMax30Text = BeneficialStrategies.Iso20022.SimpleTypes.Max30Text;
global using IsoMax34Text = BeneficialStrategies.Iso20022.SimpleTypes.Max34Text;
global using IsoMax35Text = BeneficialStrategies.Iso20022.SimpleTypes.Max35Text;
global using IsoMax36Text = BeneficialStrategies.Iso20022.SimpleTypes.Max36Text;
global using IsoMax37Text = BeneficialStrategies.Iso20022.SimpleTypes.Max37Text;
global using IsoMax40Text = BeneficialStrategies.Iso20022.SimpleTypes.Max40Text;
global using IsoMax45Text = BeneficialStrategies.Iso20022.SimpleTypes.Max45Text;
global using IsoMax48Text = BeneficialStrategies.Iso20022.SimpleTypes.Max48Text;
global using IsoMax50Text = BeneficialStrategies.Iso20022.SimpleTypes.Max50Text;
global using IsoMax52Text = BeneficialStrategies.Iso20022.SimpleTypes.Max52Text;
global using IsoMax60Text = BeneficialStrategies.Iso20022.SimpleTypes.Max60Text;
global using IsoMax64Text = BeneficialStrategies.Iso20022.SimpleTypes.Max64Text;
global using IsoMax70Text = BeneficialStrategies.Iso20022.SimpleTypes.Max70Text;
global using IsoMax72Text = BeneficialStrategies.Iso20022.SimpleTypes.Max72Text;
global using IsoMax76Text = BeneficialStrategies.Iso20022.SimpleTypes.Max76Text;
global using IsoMax99Text = BeneficialStrategies.Iso20022.SimpleTypes.Max99Text;
global using IsoMax100Text = BeneficialStrategies.Iso20022.SimpleTypes.Max100Text;
global using IsoMax104Text = BeneficialStrategies.Iso20022.SimpleTypes.Max104Text;
global using IsoMax105Text = BeneficialStrategies.Iso20022.SimpleTypes.Max105Text;
global using IsoMax128Text = BeneficialStrategies.Iso20022.SimpleTypes.Max128Text;
global using IsoMax140Text = BeneficialStrategies.Iso20022.SimpleTypes.Max140Text;
global using IsoMax200Text = BeneficialStrategies.Iso20022.SimpleTypes.Max200Text;
global using IsoMax210Text = BeneficialStrategies.Iso20022.SimpleTypes.Max210Text;
global using IsoMax240Text = BeneficialStrategies.Iso20022.SimpleTypes.Max240Text;
global using IsoMax256Text = BeneficialStrategies.Iso20022.SimpleTypes.Max256Text;
global using IsoMax280Text = BeneficialStrategies.Iso20022.SimpleTypes.Max280Text;
global using IsoMax350Text = BeneficialStrategies.Iso20022.SimpleTypes.Max350Text;
global using IsoMax450Text = BeneficialStrategies.Iso20022.SimpleTypes.Max450Text;
global using IsoMax500Text = BeneficialStrategies.Iso20022.SimpleTypes.Max500Text;
global using IsoMax512Text = BeneficialStrategies.Iso20022.SimpleTypes.Max512Text;
global using IsoMax1000Text = BeneficialStrategies.Iso20022.SimpleTypes.Max1000Text;
global using IsoMax1025Text = BeneficialStrategies.Iso20022.SimpleTypes.Max1025Text;
global using IsoMax2000Text = BeneficialStrategies.Iso20022.SimpleTypes.Max2000Text;
global using IsoMax2048Text = BeneficialStrategies.Iso20022.SimpleTypes.Max2048Text;
global using IsoMax4000Text = BeneficialStrategies.Iso20022.SimpleTypes.Max4000Text;
global using IsoMax8000Text = BeneficialStrategies.Iso20022.SimpleTypes.Max8000Text;
global using IsoMax20000Text = BeneficialStrategies.Iso20022.SimpleTypes.Max20000Text;
global using BeneficialStrategies.Iso20022.Framework;
global using BeneficialStrategies.Iso20022.Metadata;
global using BeneficialStrategies.Iso20022.Serialization;
global using IsoPhoneNumber = System.String; // Text
global using IsoExtended350Code = System.String; // Text
global using IsoPreviousAll = System.String; // Text
global using IsoUnlimited9Text = System.String; // Text
global using IsoExternalLocalInstrumentCode_Obsolete = System.String; // Text
global using IsoRefused7Text = System.String; // Text
global using IsoMin3Max4Text = System.String; // Text
global using IsoMin6Max8Text = System.String; // Text
global using IsoRestrictedMS02MS03CodeText = System.String; // Text
global using IsoRestrictedRR01CodeText = System.String; // Text
global using IsoRestrictedSEPACodeText = System.String; // Text
global using IsoRestrictedSMNDACodeText = System.String; // Text
global using IsoRestrictedB2BCORECodeText = System.String; // Text
global using IsoRestrictedRR01SL01CodeText = System.String; // Text
global using IsoMin2Max3AlphaText = System.String; // Text
global using IsoMax13AlphaNumericText = System.String; // Text
global using IsoMax14Text = System.String; // Text
global using IsoMax14AlphaNumericText = System.String; // Text
global using IsoMax100AlphaNumericUnderscoreText = System.String; // Text
global using IsoMax38AlphaNumericText = System.String; // Text
global using IsoMax5Text = System.String; // Text
global using IsoRateSourceText = System.String; // Text
global using IsoMax6AlphaText = System.String; // Text
global using IsoDateOffsetText = System.String; // Text
global using IsoMax1850Text = System.String; // Text
global using IsoMax20KText = System.String; // Text
global using IsoMax9999HexBinaryText = System.String; // Text
global using IsoMax10KText = System.String; // Text
global using IsoMax32HexBinaryText = System.String; // Text
global using IsoMax10KHexBinaryText = System.String; // Text
global using IsoMax8HexBinaryText = System.String; // Text
global using IsoMax19HexBinaryText = System.String; // Text
global using IsoMax16HexBinaryText = System.String; // Text
global using IsoGeographicPointInDecimalDegrees = System.String; // Text
global using IsoGeographicPointInDecimalDegreesText = System.String; // Text
global using IsoMin5Max8Text = System.String; // Text
global using IsoJulianDate = System.String; // Text
global using IsoMax10MbText = System.String; // Text
global using IsoMax40KText = System.String; // Text
global using IsoISODateTime = System.DateTime; // DateTime
global using IsoISONormalisedDateTime = System.DateTime; // DateTime
global using IsoISODate = System.DateOnly; // Date
global using IsoSEDOLIdentifier = System.String; // IdentifierSet
global using IsoCUSIPIdentifier = System.String; // IdentifierSet
global using IsoQUICKIdentifier = System.String; // IdentifierSet
global using IsoWertpapierIdentifier = System.String; // IdentifierSet
global using IsoDutchIdentifier = System.String; // IdentifierSet
global using IsoValorenIdentifier = System.String; // IdentifierSet
global using IsoSicovamIdentifier = System.String; // IdentifierSet
global using IsoBelgianIdentifier = System.String; // IdentifierSet
global using IsoRatingValueIdentifier = System.String; // IdentifierSet
global using IsoSNA2008SectorIdentifier = System.String; // IdentifierSet
global using IsoDirectionIndicator = System.String; // IndicatorSet
global using IsoNumber = System.UInt64; // Quantity
global using IsoDecimalNumber = System.UInt64; // Quantity
global using IsoMax3Number = System.UInt64; // Quantity
global using IsoRestrictedFINDecimalNumber = System.UInt64; // Quantity
global using IsoNonNegativeDecimalNumber = System.UInt64; // Quantity
global using IsoLongDecimalNumber = System.UInt64; // Quantity
global using IsoRestrictedMonthExact2Number = System.UInt64; // Quantity
global using IsoPositiveNumber = System.UInt64; // Quantity
global using IsoMax5Number = System.UInt64; // Quantity
global using IsoMax1Number = System.UInt64; // Quantity
global using IsoDecimalNumberFraction5 = System.UInt64; // Quantity
global using IsoLongFraction21DecimalNumber = System.UInt64; // Quantity
global using IsoNonNegativeFraction5DecimalNumber = System.UInt64; // Quantity
global using IsoNonNegativeNumber = System.UInt64; // Quantity
global using IsoMax20PositiveNumber = System.UInt64; // Quantity
global using IsoMax20PositiveDecimalNumber = System.UInt64; // Quantity
global using IsoMax6NumberFraction2 = System.UInt64; // Quantity
global using IsoMax10NumberFraction2 = System.UInt64; // Quantity
global using IsoFraction5DecimalNumber = System.UInt64; // Quantity
global using IsoMax2Fraction1NonNegativeNumber = System.UInt64; // Quantity
global using IsoLongFraction19DecimalNumber = System.UInt64; // Quantity
global using IsoDayOfMonthNumber = System.UInt64; // Quantity
global using IsoMax30DecimalNumber = System.UInt64; // Quantity
global using IsoMax5PositiveNumber = System.UInt64; // Quantity
global using IsoMax10PositiveNumber = System.UInt64; // Quantity
global using IsoISOTime = System.TimeOnly; // Time
global using IsoPercentageRate = System.Decimal; // Rate
global using IsoPercentageBoundedRate = System.Decimal; // Rate
global using IsoBaseOneRate = System.Decimal; // Rate
global using IsoBaseOne14Rate = System.Decimal; // Rate
global using IsoPercentage = System.Decimal; // Rate
global using IsoBaseOne18Rate = System.Decimal; // Rate
global using IsoBaseOne25Rate = System.Decimal; // Rate
global using IsoISOYearMonth = System.UInt16; // YearMonth
global using IsoISOYear = System.UInt16; // Year
global using IsoISORestrictedYear = System.UInt16; // Year
global using IsoMax10KBinary = System.Byte[]; // Binary
global using IsoMax2MBBinary = System.Byte[]; // Binary
global using IsoMax10000Binary = System.Byte[]; // Binary
global using IsoMax3000Binary = System.Byte[]; // Binary
global using IsoMax35Binary = System.Byte[]; // Binary
global using IsoMax500Binary = System.Byte[]; // Binary
global using IsoMax140Binary = System.Byte[]; // Binary
global using IsoMin5Max16Binary = System.Byte[]; // Binary
global using IsoMax5000Binary = System.Byte[]; // Binary
global using IsoMax100KBinary = System.Byte[]; // Binary
global using IsoMax2KBinary = System.Byte[]; // Binary
global using IsoMax50Binary = System.Byte[]; // Binary
global using IsoMax4kBinary = System.Byte[]; // Binary
global using IsoMax1kBinary = System.Byte[]; // Binary
global using IsoMax10MbBinary = System.Byte[]; // Binary
global using IsoMin1Max256Binary = System.Byte[]; // Binary
global using IsoMax16Binary = System.Byte[]; // Binary
global using IsoExact20Binary = System.Byte[]; // Binary
global using IsoMax20MbBinary = System.Byte[]; // Binary
global using IsoanySimpleType = System.String; // Schema
global using IsoanyURI = System.String; // Schema
global using Isobase64Binary = System.String; // Schema
global using Isoboolean = System.String; // Schema
global using Isobyte = System.String; // Schema
global using Isodate = System.String; // Schema
global using IsodateTime = System.String; // Schema
global using Isodecimal = System.String; // Schema
global using Isodouble = System.String; // Schema
global using Isoduration = System.String; // Schema
global using IsoENTITIES = System.String; // Schema
global using IsoENTITY = System.String; // Schema
global using Isofloat = System.String; // Schema
global using IsogDay = System.String; // Schema
global using IsogMonth = System.String; // Schema
global using IsogMonthDay = System.String; // Schema
global using IsogYear = System.String; // Schema
global using IsogYearMonth = System.String; // Schema
global using IsohexBinary = System.String; // Schema
global using IsoID = System.String; // Schema
global using IsoIDREF = System.String; // Schema
global using IsoIDREFS = System.String; // Schema
global using Isoint = System.String; // Schema
global using Isointeger = System.String; // Schema
global using Isolanguage = System.String; // Schema
global using Isolong = System.String; // Schema
global using IsoName = System.String; // Schema
global using IsoNCName = System.String; // Schema
global using IsonegativeInteger = System.String; // Schema
global using IsoNMTOKEN = System.String; // Schema
global using IsoNMTOKENS = System.String; // Schema
global using IsononNegativeInteger = System.String; // Schema
global using IsononPositiveInteger = System.String; // Schema
global using IsonormalizedString = System.String; // Schema
global using IsopositiveInteger = System.String; // Schema
global using IsoQName = System.String; // Schema
global using Isoshort = System.String; // Schema
global using Isostring = System.String; // Schema
global using Isotime = System.String; // Schema
global using Isotoken = System.String; // Schema
global using IsounsignedByte = System.String; // Schema
global using IsounsignedInt = System.String; // Schema
global using IsounsignedLong = System.String; // Schema
global using IsounsignedShort = System.String; // Schema
global using IsoISOMonth = System.Byte; // Month
global using IsoExact4UpperCaseAlphaText = System.String; // Text
global using IsoHexBinaryText = System.String; // Text
global using IsoMax10DateText = System.String; // Text
global using IsoMax47Text = System.String; // Text
global using IsoNPIIdentifier = System.String; // IdentifierSet
global using IsoPercentage14Rate = System.Decimal; // Rate
global using IsoSHA256SignatureText = System.String; // Text
// External Codesets
global using CurrencyCode = System.String;
global using ActiveCurrencyCode = System.String;
global using ActiveOrHistoricCurrencyCode = System.String;
global using LanguageCode = System.String;
global using NationalityCode = System.String;
global using ExternalClearingSystemMemberCode = System.String;
global using ExternalPurposeCode_Obsolete = System.String;
global using ExternalCode = System.String;
global using ISO2ALanguageCode = System.String;
global using ISO3ACountryCode = System.String;
global using ISO3NumericCountryCode = System.String;
global using BusinessFilePriorityCode = System.String;
global using ExternalDiscrepancy1Code = System.String;
global using ExternalClearingSystemMember1Code = System.String;
global using ExternalTechnicalError1Code = System.String;
global using ExternalTechnicalErrorCode = System.String;
global using ExternalSystemEvent1Code = System.String;
global using ExternalSecuritiesLendingTypeCode = System.String;
global using ExternalSecuritiesLendingType1Code = System.String;
global using ExternalInvalidEventReason1Code = System.String;
global using ExternalInvalidPaymentsEvent1Code = System.String;
global using ExternalInvalidPaymentsEventCode = System.String;
global using ExternalInvalidEventReasonCode = System.String;
global using ExternalSystemPartyType1Code = System.String;
global using ParentCurrencyCode = System.String;
global using ExternalSystemPartyTypeCode = System.String;
global using ISO3NumericCurrencyCode = System.String;
global using ExternalDebtorAgentInstruction1Code = System.String;
global using ExternalTrackertAlertStatus1Code = System.String;
global using ExternalTrackerAlertStatusReason1Code = System.String;
global using ExternalTrackerAlertStatusReasonCode = System.String;
global using ExternalTrackertAlertStatusCode = System.String;
global using ExternalChequeCancellationStatus1Code = System.String;
global using ExternalChequeCancellationReason1Code = System.String;
global using ExternalInstructedAgentInstruction1Code = System.String;
global using ExternalChequeCancellationStatusCode = System.String;
global using ExternalInstructedAgentInstructionCode = System.String;
global using ExternalChequeCancellationReasonCode = System.String;
global using ExternalSecuritiesUpdateReason1Code = System.String;
global using ExternalSecuritiesUpdateReasonCode = System.String;
global using ExternalNotificationCancellationReason1Code = System.String;
global using ExternalNotificationCancellationReasonCode = System.String;
global using ISO8583TransactionTypeCode = System.String;
global using ISO8583MessageReasonCode = System.String;
global using ISO8583AmountTypeCode = System.String;
global using ISOMax3ACountryCode = System.String;
global using ISOMax3ALanguageCode = System.String;
global using ISO8583ResponseCode = System.String;
global using ISO18245MerchantCategoryCode = System.String;
global using ExternalAuthenticationMethod1Code = System.String;
global using ISOCountrySubDivisionCode = System.String;
global using ISO8583AccountTypeCode = System.String;
global using ISO8583AccountEntryDeviceTypeCode = System.String;
global using ISO8583AccountIdentifierTypeCode = System.String;
global using ISO8583ActionCode = System.String;
global using ISO8583AdditionalServiceResultCode = System.String;
global using ISO8583FeeTypeCode = System.String;
global using ISO8583MessageErrorCode = System.String;
global using ISO8583NetworkManagementInformationCode = System.String;
global using ISO8583PINEntryCapabilityCode = System.String;
global using ISO8583POSConditionCode = System.String;
global using ISO8583ShippingIndicatorCode = System.String;
global using ExternalAuthenticationMethodCode = System.String;
global using ExternalPartyRelationshipType1Code = System.String;
global using ExternalPartyRelationshipTypeCode = System.String;
global using ExternalTrackerInvestigationStatusReason1Code = System.String;
global using ExternalTrackerInvestigationStatus1Code = System.String;
global using ExternalTrackerInvestigationType1Code = System.String;
global using ExternalTrackerInvestigationStatusCode = System.String;
global using ExternalTrackerInvestigationStatusReasonCode = System.String;
global using ExternalTrackerInvestigationTypeCode = System.String;
global using ExternalInvestigationAction1Code = System.String;
global using ExternalInvestigationActionCode = System.String;
global using ExternalInvestigationActionReason1Code = System.String;
global using ExternalInvestigationActionReasonCode = System.String;
global using ExternalInvestigationInstrument1Code = System.String;
global using ExternalInvestigationInstrumentCode = System.String;
global using ExternalInvestigationReason1Code = System.String;
global using ExternalInvestigationReasonCode = System.String;
global using ExternalInvestigationReasonSubType1Code = System.String;
global using ExternalInvestigationReasonSubTypeCode = System.String;
global using ExternalInvestigationServiceLevel1Code = System.String;
global using ExternalInvestigationServiceLevelCode = System.String;
global using ExternalInvestigationStatus1Code = System.String;
global using ExternalInvestigationStatusCode = System.String;
global using ExternalInvestigationStatusReason1Code = System.String;
global using ExternalInvestigationStatusReasonCode = System.String;
global using ExternalInvestigationSubType1Code = System.String;
global using ExternalInvestigationSubTypeCode = System.String;
global using ExternalInvestigationType1Code = System.String;
global using ExternalInvestigationTypeCode = System.String;
global using ExternalLegalFramework1Code = System.String;
global using ExternalLegalFrameworkCode = System.String;
global using ExternalMessageFunction1Code = System.String;
global using ExternalMessageFunctionCode = System.String;
global using ExternalNotificationSubType1Code = System.String;
global using ExternalNotificationSubTypeCode = System.String;
global using ExternalNotificationType1Code = System.String;
global using ExternalNotificationTypeCode = System.String;
global using ExternalPostTradeEventType1Code = System.String;
global using ExternalPostTradeEventTypeCode = System.String;
global using ExternalPaymentMethode1Code = System.String;
global using ExternalPaymentMethodeCode = System.String;
global using ExternalPenaltyPartyType1Code = System.String;
global using ExternalPenaltyPartyTypeCode = System.String;
global using ExternalProductType1Code = System.String;
global using ExternalProductTypeCode = System.String;
global using ExternalRegulatoryInformationType1Code = System.String;
global using ExternalRegulatoryInformationTypeCode = System.String;
global using ExternalRegulatoryReportingType1Code = System.String;
global using ExternalRegulatoryReportingTypeCode = System.String;
global using ExternalTrackerNotificationSubTypeCode = System.String;
global using ExternalTrackerNotificationTypeCode = System.String;
global using FXTradeConfirmationStatusCode = System.String;
global using NonEligibleProceedsIndicator2Code = System.String;
global using OfferType5Code = System.String;
global using OptionDefinitionType1Code = System.String;
global using OrderEventType1Code = System.String;
global using OrderEventTypeCode = System.String;
global using OrderRestrictionType1Code = System.String;
global using OrderRestrictionTypeCode = System.String;
global using OrderStatus10Code = System.String;
global using OrderStatus11Code = System.String;
global using OrderType3Code = System.String;
global using POIComponentType7Code = System.String;
global using PartyExceptionType1Code = System.String;
global using PartyExceptionTypeCode = System.String;
global using PartyRole4Code = System.String;
global using PassiveOrAgressiveType1Code = System.String;
global using PassiveOrAgressiveTypeCode = System.String;
global using PaymentInstrumentType2Code = System.String;
global using PreferredContactMethod2Code = System.String;
global using PriceCalculationMethod1Code = System.String;
global using PriceCalculationMethodCode = System.String;
global using ProcessedStatus7Code = System.String;
global using PurchaseIdentifierType2Code = System.String;
global using RedemptionAnnouncementNoticeType1Code = System.String;
global using RedemptionAnnouncementNoticeTypeCode = System.String;
global using Response12Code = System.String;
global using ResultDetail5Code = System.String;
global using ReturnedStatus1Code = System.String;
global using ReturnedStatusCode = System.String;
global using SettlementDate8Code = System.String;
global using SettlementDateV2Code = System.String;
global using Side6Code = System.String;
global using SoftwareType1Code = System.String;
global using SoftwareTypeCode = System.String;
global using Status11Code = System.String;
global using TransferOfProceedsType1Code = System.String;
global using TransferOfProceedsTypeCode = System.String;
global using ValidityPeriodType1Code = System.String;
global using ValidityPeriodTypeCode = System.String;
// ExternalSchema type aliases
global using IsoATICALaxProcessing = BeneficialStrategies.Iso20022.ExternalSchema.ATICALaxProcessing;
global using IsoLaxPayload = BeneficialStrategies.Iso20022.ExternalSchema.LaxPayload;
global using IsoSignatureEnvelope = BeneficialStrategies.Iso20022.ExternalSchema.SignatureEnvelope;
