// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

// For source code clarity, the primative types used in this implementation are represented in source code as their ISO-declared types.
// Because too many were clashing with Microsoft framework types, all names are prefixed with 'Iso' for disambiguation.

// Global namespace usings required by generated code
global using System.ComponentModel;
global using System.Runtime.Serialization;
global using System.Text.Json.Serialization;
global using BeneficialStrategies.Iso20022.Amounts;
global using BeneficialStrategies.Iso20022.Codesets;
global using BeneficialStrategies.Iso20022.SimpleTypes;

global using BeneficialStrategies.Iso20022.Framework;
global using BeneficialStrategies.Iso20022.Metadata;
global using BeneficialStrategies.Iso20022.Serialization;

// IsoMax*Text aliases — redirect to validated structs in SimpleTypes namespace
// IsoRestrictedFINX* aliases — redirect to validated structs
// IsoRestrictedFIN* and IsoRestrictedFINZ* aliases
// Indicator aliases — boolean true/false wire types
// XSD integer type aliases — W3C xs:int/long/short/byte/unsigned/constrained
global using Isoint = BeneficialStrategies.Iso20022.SimpleTypes.XsdInt;
global using Isolong = BeneficialStrategies.Iso20022.SimpleTypes.XsdLong;
global using Isoshort = BeneficialStrategies.Iso20022.SimpleTypes.XsdShort;
global using Isobyte = BeneficialStrategies.Iso20022.SimpleTypes.XsdByte;
global using IsounsignedByte = BeneficialStrategies.Iso20022.SimpleTypes.XsdUnsignedByte;
global using IsounsignedInt = BeneficialStrategies.Iso20022.SimpleTypes.XsdUnsignedInt;
global using IsounsignedLong = BeneficialStrategies.Iso20022.SimpleTypes.XsdUnsignedLong;
global using IsounsignedShort = BeneficialStrategies.Iso20022.SimpleTypes.XsdUnsignedShort;
global using Isointeger = BeneficialStrategies.Iso20022.SimpleTypes.XsdInteger;
global using IsopositiveInteger = BeneficialStrategies.Iso20022.SimpleTypes.XsdPositiveInteger;
global using IsonegativeInteger = BeneficialStrategies.Iso20022.SimpleTypes.XsdNegativeInteger;
global using IsononNegativeInteger = BeneficialStrategies.Iso20022.SimpleTypes.XsdNonNegativeInteger;
global using IsononPositiveInteger = BeneficialStrategies.Iso20022.SimpleTypes.XsdNonPositiveInteger;
// XSD boolean/floating-point type aliases — W3C xs:boolean/float/double
global using Isoboolean = BeneficialStrategies.Iso20022.SimpleTypes.XsdBoolean;
global using Isofloat = BeneficialStrategies.Iso20022.SimpleTypes.XsdFloat;
global using Isodouble = BeneficialStrategies.Iso20022.SimpleTypes.XsdDouble;
// XSD Gregorian/duration/URI type aliases — W3C xs:gYear/gYearMonth/gMonth/gMonthDay/gDay/duration/anyURI
global using IsogYear = BeneficialStrategies.Iso20022.SimpleTypes.XsdGYear;
global using IsogYearMonth = BeneficialStrategies.Iso20022.SimpleTypes.XsdGYearMonth;
global using IsogMonth = BeneficialStrategies.Iso20022.SimpleTypes.XsdGMonth;
global using IsogMonthDay = BeneficialStrategies.Iso20022.SimpleTypes.XsdGMonthDay;
global using IsogDay = BeneficialStrategies.Iso20022.SimpleTypes.XsdGDay;
global using Isoduration = BeneficialStrategies.Iso20022.SimpleTypes.XsdDuration;
global using IsoanyURI = BeneficialStrategies.Iso20022.SimpleTypes.XsdAnyURI;
// XSD string subtype / binary type aliases — W3C xs:normalizedString/token/language/hexBinary/base64Binary
global using IsonormalizedString = BeneficialStrategies.Iso20022.SimpleTypes.XsdNormalizedString;
global using Isotoken = BeneficialStrategies.Iso20022.SimpleTypes.XsdToken;
global using Isolanguage = BeneficialStrategies.Iso20022.SimpleTypes.XsdLanguage;
global using IsohexBinary = BeneficialStrategies.Iso20022.SimpleTypes.XsdHexBinary;
global using Isobase64Binary = BeneficialStrategies.Iso20022.SimpleTypes.XsdBase64Binary;
// Remaining SimpleTypes aliases
global using IsoExtended350Code = BeneficialStrategies.Iso20022.SimpleTypes.Extended350Code;
global using IsoExternalLocalInstrumentCode_Obsolete = BeneficialStrategies.Iso20022.SimpleTypes.ExternalLocalInstrumentCode_Obsolete;
global using IsoMin3Max4Text = BeneficialStrategies.Iso20022.SimpleTypes.Min3Max4Text;
global using IsoMin5Max8Text = BeneficialStrategies.Iso20022.SimpleTypes.Min5Max8Text;
global using IsoMin6Max8Text = BeneficialStrategies.Iso20022.SimpleTypes.Min6Max8Text;
global using IsoMax10KText = BeneficialStrategies.Iso20022.SimpleTypes.Max10KText;
global using IsoMax20KText = BeneficialStrategies.Iso20022.SimpleTypes.Max20KText;
global using IsoMax40KText = BeneficialStrategies.Iso20022.SimpleTypes.Max40KText;
global using IsoMax10MbText = BeneficialStrategies.Iso20022.SimpleTypes.Max10MbText;
global using IsoPhoneNumber = BeneficialStrategies.Iso20022.SimpleTypes.PhoneNumber;
global using IsoSHA256SignatureText = BeneficialStrategies.Iso20022.SimpleTypes.SHA256SignatureText;
global using IsoHexBinaryText = BeneficialStrategies.Iso20022.SimpleTypes.HexBinaryText;
global using IsoDateOffsetText = BeneficialStrategies.Iso20022.SimpleTypes.DateOffsetText;
global using IsoGeographicPointInDecimalDegrees = BeneficialStrategies.Iso20022.SimpleTypes.GeographicPointInDecimalDegrees;
global using IsoGeographicPointInDecimalDegreesText = BeneficialStrategies.Iso20022.SimpleTypes.GeographicPointInDecimalDegreesText;
global using IsoRefused7Text = BeneficialStrategies.Iso20022.SimpleTypes.Refused7Text;
global using IsoRateSourceText = BeneficialStrategies.Iso20022.SimpleTypes.RateSourceText;
global using IsoPreviousAll = BeneficialStrategies.Iso20022.SimpleTypes.PreviousAll;
global using IsoUnlimited9Text = BeneficialStrategies.Iso20022.SimpleTypes.Unlimited9Text;
global using IsoMax10DateText = BeneficialStrategies.Iso20022.SimpleTypes.Max10DateText;
global using IsoJulianDate = BeneficialStrategies.Iso20022.SimpleTypes.JulianDate;
global using IsoMax8HexBinaryText = BeneficialStrategies.Iso20022.SimpleTypes.Max8HexBinaryText;
global using IsoMax16HexBinaryText = BeneficialStrategies.Iso20022.SimpleTypes.Max16HexBinaryText;
global using IsoMax19HexBinaryText = BeneficialStrategies.Iso20022.SimpleTypes.Max19HexBinaryText;
global using IsoMax32HexBinaryText = BeneficialStrategies.Iso20022.SimpleTypes.Max32HexBinaryText;
global using IsoMax9999HexBinaryText = BeneficialStrategies.Iso20022.SimpleTypes.Max9999HexBinaryText;
global using IsoMax10KHexBinaryText = BeneficialStrategies.Iso20022.SimpleTypes.Max10KHexBinaryText;
global using IsoMax6AlphaText = BeneficialStrategies.Iso20022.SimpleTypes.Max6AlphaText;
global using IsoMin2Max3AlphaText = BeneficialStrategies.Iso20022.SimpleTypes.Min2Max3AlphaText;
// Identifier and financial-code aliases
global using IsoBICFIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BICFIIdentifier;
global using IsoBICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BICIdentifier;
global using IsoBICNonFIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BICNonFIIdentifier;
global using IsoAnyBICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.AnyBICIdentifier;
global using IsoBEIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BEIIdentifier;
global using IsoBICFIDec2014Identifier = BeneficialStrategies.Iso20022.SimpleTypes.BICFIDec2014Identifier;
global using IsoBICNonFIDec2014Identifier = BeneficialStrategies.Iso20022.SimpleTypes.BICNonFIDec2014Identifier;
global using IsoAnyBICDec2014Identifier = BeneficialStrategies.Iso20022.SimpleTypes.AnyBICDec2014Identifier;
global using IsoIBANIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.IBANIdentifier;
global using IsoIBAN2007Identifier = BeneficialStrategies.Iso20022.SimpleTypes.IBAN2007Identifier;
global using IsoBBANIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BBANIdentifier;
global using IsoAustrianBankleitzahlIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.AustrianBankleitzahlIdentifier;
global using IsoCanadianPaymentsARNIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.CanadianPaymentsARNIdentifier;
global using IsoCHIPSParticipantIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.CHIPSParticipantIdentifier;
global using IsoCHIPSUniversalIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.CHIPSUniversalIdentifier;
global using IsoExtensiveBranchNetworkIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ExtensiveBranchNetworkIdentifier;
global using IsoFedwireRoutingNumberIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.FedwireRoutingNumberIdentifier;
global using IsoGermanBankleitzahlIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.GermanBankleitzahlIdentifier;
global using IsoHellenicBankIdentificationCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.HellenicBankIdentificationCodeIdentifier;
global using IsoHongKongBankIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.HongKongBankIdentifier;
global using IsoIndianFinancialSystemCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.IndianFinancialSystemCodeIdentifier;
global using IsoIrishNSCIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.IrishNSCIdentifier;
global using IsoItalianDomesticIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ItalianDomesticIdentifier;
global using IsoNewZealandNCCIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.NewZealandNCCIdentifier;
global using IsoPolishNationalClearingCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.PolishNationalClearingCodeIdentifier;
global using IsoPortugueseNCCIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.PortugueseNCCIdentifier;
global using IsoRussianCentralBankIdentificationCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.RussianCentralBankIdentificationCodeIdentifier;
global using IsoSmallNetworkIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SmallNetworkIdentifier;
global using IsoSouthAfricanNCCIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SouthAfricanNCCIdentifier;
global using IsoSpanishDomesticInterbankingIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SpanishDomesticInterbankingIdentifier;
global using IsoSwissBCIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SwissBCIdentifier;
global using IsoSwissSICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SwissSICIdentifier;
global using IsoUKDomesticSortCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.UKDomesticSortCodeIdentifier;
global using IsoISINIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ISINIdentifier;
global using IsoISINOct2015Identifier = BeneficialStrategies.Iso20022.SimpleTypes.ISINOct2015Identifier;
global using IsoISIN2021Identifier = BeneficialStrategies.Iso20022.SimpleTypes.ISIN2021Identifier;
global using IsoLEIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.LEIIdentifier;
global using IsoMICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.MICIdentifier;
global using IsoCFIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.CFIIdentifier;
global using IsoCFIOct2015Identifier = BeneficialStrategies.Iso20022.SimpleTypes.CFIOct2015Identifier;
global using IsoEICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.EICIdentifier;
global using IsoIBEIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.IBEIIdentifier;
global using IsoISICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ISICIdentifier;
global using IsoUPICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.UPICIdentifier;
global using IsoDunsIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.DunsIdentifier;
global using IsoEANGLNIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.EANGLNIdentifier;
global using IsoMerchantCategoryCodeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.MerchantCategoryCodeIdentifier;
global using IsoNACEDomainIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.NACEDomainIdentifier;
global using IsoNACEDomain2025Identifier = BeneficialStrategies.Iso20022.SimpleTypes.NACEDomain2025Identifier;
global using IsoBloomberg2Identifier = BeneficialStrategies.Iso20022.SimpleTypes.Bloomberg2Identifier;
global using IsoDTI2021Identifier = BeneficialStrategies.Iso20022.SimpleTypes.DTI2021Identifier;
global using IsoDTI2024Identifier = BeneficialStrategies.Iso20022.SimpleTypes.DTI2024Identifier;
global using IsoEntryTypeIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.EntryTypeIdentifier;
global using IsoUUIDv4Identifier = BeneficialStrategies.Iso20022.SimpleTypes.UUIDv4Identifier;
global using IsoUTIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.UTIIdentifier;
global using IsoISO20022MessageIdentificationText = BeneficialStrategies.Iso20022.SimpleTypes.ISO20022MessageIdentificationText;
global using IsoBloombergIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BloombergIdentifier;
global using IsoConsolidatedTapeAssociationIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ConsolidatedTapeAssociationIdentifier;
global using IsoEuroclearClearstreamIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.EuroclearClearstreamIdentifier;
global using IsoRICIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.RICIdentifier;
global using IsoTickerIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.TickerIdentifier;
global using IsoYesNoIndicator = BeneficialStrategies.Iso20022.SimpleTypes.YesNoIndicator;
global using IsoTrueFalseIndicator = BeneficialStrategies.Iso20022.SimpleTypes.TrueFalseIndicator;
global using IsoPlusOrMinusIndicator = BeneficialStrategies.Iso20022.SimpleTypes.PlusOrMinusIndicator;
global using IsoAMLIndicator = BeneficialStrategies.Iso20022.SimpleTypes.AMLIndicator;
global using IsoBatchBookingIndicator = BeneficialStrategies.Iso20022.SimpleTypes.BatchBookingIndicator;
global using IsoChargeIncludedIndicator = BeneficialStrategies.Iso20022.SimpleTypes.ChargeIncludedIndicator;
global using IsoGroupCancellationIndicator = BeneficialStrategies.Iso20022.SimpleTypes.GroupCancellationIndicator;
global using IsoGroupingIndicator = BeneficialStrategies.Iso20022.SimpleTypes.GroupingIndicator;
global using IsoIdentificationVerificationIndicator = BeneficialStrategies.Iso20022.SimpleTypes.IdentificationVerificationIndicator;
global using IsoOverrideIndicator = BeneficialStrategies.Iso20022.SimpleTypes.OverrideIndicator;
global using IsoPaymentDirectionIndicator = BeneficialStrategies.Iso20022.SimpleTypes.PaymentDirectionIndicator;
global using IsoRequestedIndicator = BeneficialStrategies.Iso20022.SimpleTypes.RequestedIndicator;
global using IsoRestrictedFINMax8Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax8Text;
global using IsoRestrictedFINMax15Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax15Text;
global using IsoRestrictedFINMax16Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax16Text;
global using IsoRestrictedFINMax23Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax23Text;
global using IsoRestrictedFINMax30Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax30Text;
global using IsoRestrictedFINMax31Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax31Text;
global using IsoRestrictedFINMax34Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax34Text;
global using IsoRestrictedFINMax35Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax35Text;
global using IsoRestrictedFINMax50Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax50Text;
global using IsoRestrictedFINMax210Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINMax210Text;
global using IsoRestrictedFINZMax256Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINZMax256Text;
global using IsoRestrictedFINZMax2048Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINZMax2048Text;
global using IsoRestrictedFINZMax8000Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINZMax8000Text;
global using IsoRestrictedFINXMax8Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax8Text;
global using IsoRestrictedFINXMax16Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax16Text;
global using IsoRestrictedFINXMax24Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax24Text;
global using IsoRestrictedFINXMax25Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax25Text;
global using IsoRestrictedFINXMax30Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax30Text;
global using IsoRestrictedFINXMax31Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax31Text;
global using IsoRestrictedFINXMax34Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax34Text;
global using IsoRestrictedFINXMax35Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax35Text;
global using IsoRestrictedFINXMax52Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax52Text;
global using IsoRestrictedFINXMax70Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax70Text;
global using IsoRestrictedFINXMax140Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax140Text;
global using IsoRestrictedFINXMax210Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax210Text;
global using IsoRestrictedFINXMax256Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax256Text;
global using IsoRestrictedFINXMax350Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax350Text;
global using IsoRestrictedFINXMax520Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINXMax520Text;
global using IsoRestrictedFINX2Max34Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINX2Max34Text;
// IsoXxx aliases for Groups A/B/C/D pattern-restricted simple types
global using IsoMax2NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max2NumericText;
global using IsoMax3NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max3NumericText;
global using IsoMax4NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max4NumericText;
global using IsoMax5NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max5NumericText;
global using IsoMax6NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max6NumericText;
global using IsoMax8NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max8NumericText;
global using IsoMax9NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max9NumericText;
global using IsoMax10NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max10NumericText;
global using IsoMax11NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max11NumericText;
global using IsoMax12NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max12NumericText;
global using IsoMax15NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max15NumericText;
global using IsoMax19NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max19NumericText;
global using IsoMax23NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max23NumericText;
global using IsoMax35NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max35NumericText;
global using IsoExact1NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact1NumericText;
global using IsoExact2NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact2NumericText;
global using IsoExact3NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact3NumericText;
global using IsoExact4NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact4NumericText;
global using IsoExact5NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact5NumericText;
global using IsoExact7NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact7NumericText;
global using IsoExact14NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact14NumericText;
global using IsoMin2Max3NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Min2Max3NumericText;
global using IsoMin3Max4NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Min3Max4NumericText;
global using IsoMin8Max28NumericText = BeneficialStrategies.Iso20022.SimpleTypes.Min8Max28NumericText;
global using IsoMax15PlusSignedNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max15PlusSignedNumericText;
global using IsoMax4AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max4AlphaNumericText;
global using IsoMax5AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max5AlphaNumericText;
global using IsoMax15AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max15AlphaNumericText;
global using IsoMax20AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Max20AlphaNumericText;
global using IsoExact2AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact2AlphaNumericText;
global using IsoExact3AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact3AlphaNumericText;
global using IsoExact4AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact4AlphaNumericText;
global using IsoExact32AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact32AlphaNumericText;
global using IsoExact1Text = BeneficialStrategies.Iso20022.SimpleTypes.Exact1Text;
global using IsoExact10Text = BeneficialStrategies.Iso20022.SimpleTypes.Exact10Text;
global using IsoExact12Text = BeneficialStrategies.Iso20022.SimpleTypes.Exact12Text;
global using IsoExact15Text = BeneficialStrategies.Iso20022.SimpleTypes.Exact15Text;
global using IsoExact42Text = BeneficialStrategies.Iso20022.SimpleTypes.Exact42Text;
global using IsoExact2UpperCaseAlphaText = BeneficialStrategies.Iso20022.SimpleTypes.Exact2UpperCaseAlphaText;
global using IsoExact3UpperCaseAlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact3UpperCaseAlphaNumericText;
global using IsoExact1AlphaText = BeneficialStrategies.Iso20022.SimpleTypes.Exact1AlphaText;
global using IsoExact6AlphaNumericText = BeneficialStrategies.Iso20022.SimpleTypes.Exact6AlphaNumericText;
global using IsoExact4AlphaNumericUnderscoreText = BeneficialStrategies.Iso20022.SimpleTypes.Exact4AlphaNumericUnderscoreText;
global using IsoRestrictedFINExact2Text = BeneficialStrategies.Iso20022.SimpleTypes.RestrictedFINExact2Text;
global using IsoExact1HexBinaryText = BeneficialStrategies.Iso20022.SimpleTypes.Exact1HexBinaryText;
global using IsoMax3Text = BeneficialStrategies.Iso20022.SimpleTypes.Max3Text;
global using IsoMax4Text = BeneficialStrategies.Iso20022.SimpleTypes.Max4Text;
global using IsoMax6Text = BeneficialStrategies.Iso20022.SimpleTypes.Max6Text;
global using IsoMax8Text = BeneficialStrategies.Iso20022.SimpleTypes.Max8Text;
global using IsoMax10Text = BeneficialStrategies.Iso20022.SimpleTypes.Max10Text;
global using IsoMax12Text = BeneficialStrategies.Iso20022.SimpleTypes.Max12Text;
global using IsoMax15Text = BeneficialStrategies.Iso20022.SimpleTypes.Max15Text;
global using IsoMax16Text = BeneficialStrategies.Iso20022.SimpleTypes.Max16Text;
global using IsoMax20Text = BeneficialStrategies.Iso20022.SimpleTypes.Max20Text;
global using IsoMax25Text = BeneficialStrategies.Iso20022.SimpleTypes.Max25Text;
global using IsoMax30Text = BeneficialStrategies.Iso20022.SimpleTypes.Max30Text;
global using IsoMax34Text = BeneficialStrategies.Iso20022.SimpleTypes.Max34Text;
global using IsoMax35Text = BeneficialStrategies.Iso20022.SimpleTypes.Max35Text;
global using IsoMax36Text = BeneficialStrategies.Iso20022.SimpleTypes.Max36Text;
global using IsoMax37Text = BeneficialStrategies.Iso20022.SimpleTypes.Max37Text;
global using IsoMax40Text = BeneficialStrategies.Iso20022.SimpleTypes.Max40Text;
global using IsoMax45Text = BeneficialStrategies.Iso20022.SimpleTypes.Max45Text;
global using IsoMax48Text = BeneficialStrategies.Iso20022.SimpleTypes.Max48Text;
global using IsoMax50Text = BeneficialStrategies.Iso20022.SimpleTypes.Max50Text;
global using IsoMax52Text = BeneficialStrategies.Iso20022.SimpleTypes.Max52Text;
global using IsoMax60Text = BeneficialStrategies.Iso20022.SimpleTypes.Max60Text;
global using IsoMax64Text = BeneficialStrategies.Iso20022.SimpleTypes.Max64Text;
global using IsoMax70Text = BeneficialStrategies.Iso20022.SimpleTypes.Max70Text;
global using IsoMax72Text = BeneficialStrategies.Iso20022.SimpleTypes.Max72Text;
global using IsoMax76Text = BeneficialStrategies.Iso20022.SimpleTypes.Max76Text;
global using IsoMax99Text = BeneficialStrategies.Iso20022.SimpleTypes.Max99Text;
global using IsoMax100Text = BeneficialStrategies.Iso20022.SimpleTypes.Max100Text;
global using IsoMax104Text = BeneficialStrategies.Iso20022.SimpleTypes.Max104Text;
global using IsoMax105Text = BeneficialStrategies.Iso20022.SimpleTypes.Max105Text;
global using IsoMax128Text = BeneficialStrategies.Iso20022.SimpleTypes.Max128Text;
global using IsoMax140Text = BeneficialStrategies.Iso20022.SimpleTypes.Max140Text;
global using IsoMax200Text = BeneficialStrategies.Iso20022.SimpleTypes.Max200Text;
global using IsoMax210Text = BeneficialStrategies.Iso20022.SimpleTypes.Max210Text;
global using IsoMax240Text = BeneficialStrategies.Iso20022.SimpleTypes.Max240Text;
global using IsoMax256Text = BeneficialStrategies.Iso20022.SimpleTypes.Max256Text;
global using IsoMax280Text = BeneficialStrategies.Iso20022.SimpleTypes.Max280Text;
global using IsoMax350Text = BeneficialStrategies.Iso20022.SimpleTypes.Max350Text;
global using IsoMax450Text = BeneficialStrategies.Iso20022.SimpleTypes.Max450Text;
global using IsoMax500Text = BeneficialStrategies.Iso20022.SimpleTypes.Max500Text;
global using IsoMax512Text = BeneficialStrategies.Iso20022.SimpleTypes.Max512Text;
global using IsoMax1000Text = BeneficialStrategies.Iso20022.SimpleTypes.Max1000Text;
global using IsoMax1025Text = BeneficialStrategies.Iso20022.SimpleTypes.Max1025Text;
global using IsoMax2000Text = BeneficialStrategies.Iso20022.SimpleTypes.Max2000Text;
global using IsoMax2048Text = BeneficialStrategies.Iso20022.SimpleTypes.Max2048Text;
global using IsoMax4000Text = BeneficialStrategies.Iso20022.SimpleTypes.Max4000Text;
global using IsoMax8000Text = BeneficialStrategies.Iso20022.SimpleTypes.Max8000Text;
global using IsoMax20000Text = BeneficialStrategies.Iso20022.SimpleTypes.Max20000Text;

// global using IsoRestrictedMS02MS03CodeText = System.String; // Not in current ISO 20022 snapshot — payment scheme-specific code; cannot convert
// global using IsoRestrictedRR01CodeText = System.String; // Not in current ISO 20022 snapshot — payment scheme-specific code; cannot convert
// global using IsoRestrictedSEPACodeText = System.String; // Not in current ISO 20022 snapshot — SEPA payment scheme code; cannot convert
// global using IsoRestrictedSMNDACodeText = System.String; // Not in current ISO 20022 snapshot — payment scheme-specific code; cannot convert
// global using IsoRestrictedB2BCORECodeText = System.String; // Not in current ISO 20022 snapshot — B2B CORE scheme code; cannot convert
// global using IsoRestrictedRR01SL01CodeText = System.String; // Not in current ISO 20022 snapshot — payment scheme-specific code; cannot convert
// global using IsoMax13AlphaNumericText = System.String; // Not in current ISO 20022 snapshot — cannot convert
// global using IsoMax14Text = System.String; // Not in current ISO 20022 snapshot — cannot convert
// global using IsoMax14AlphaNumericText = System.String; // Not in current ISO 20022 snapshot — cannot convert
// global using IsoMax100AlphaNumericUnderscoreText = System.String; // Not in current ISO 20022 snapshot — cannot convert
// global using IsoMax38AlphaNumericText = System.String; // Not in current ISO 20022 snapshot — cannot convert
// global using IsoMax5Text = System.String; // Not in current ISO 20022 snapshot — cannot convert
// global using IsoMax1850Text = System.String; // Not in current ISO 20022 snapshot — cannot convert
global using IsoISODateTime = BeneficialStrategies.Iso20022.SimpleTypes.ISODateTime; // date+time, 3 permitted wire forms (UTC/offset/local) — see SimpleTypes/ISODateTime.cs
global using IsoISONormalisedDateTime = BeneficialStrategies.Iso20022.SimpleTypes.ISONormalisedDateTime; // ISODateTime restricted to always-UTC (pattern .*Z) — see SimpleTypes/ISONormalisedDateTime.cs
global using IsoISODate = System.DateOnly; // Date
global using IsoSEDOLIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SEDOLIdentifier; // IdentifierSet; London Stock Exchange proprietary format, no ISO-stated pattern
global using IsoCUSIPIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.CUSIPIdentifier; // IdentifierSet; CUSIP Bureau proprietary format, no ISO-stated pattern
global using IsoQUICKIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.QUICKIdentifier; // IdentifierSet; Japanese QUICK proprietary format, no ISO-stated pattern
global using IsoWertpapierIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.WertpapierIdentifier; // IdentifierSet; German WKN, ISO-stated 6-digit format
global using IsoDutchIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.DutchIdentifier; // IdentifierSet; Dutch securities proprietary format, no ISO-stated pattern
global using IsoValorenIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.ValorenIdentifier; // IdentifierSet; Swiss Telekurs proprietary format, no ISO-stated pattern
global using IsoSicovamIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SicovamIdentifier; // IdentifierSet; French Sicovam, ISO-stated 5-digit format
global using IsoBelgianIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.BelgianIdentifier; // IdentifierSet; Belgian securities proprietary format, no ISO-stated pattern
global using IsoRatingValueIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.RatingValueIdentifier; // IdentifierSet; rating agency proprietary values, no ISO-stated pattern
global using IsoSNA2008SectorIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.SNA2008SectorIdentifier; // IdentifierSet; UN SNA 2008 hierarchical sector codes, no ISO-stated pattern
// global using IsoDirectionIndicator = System.String; // Not in current ISO 20022 snapshot — cannot convert
global using IsoNumber = System.UInt64; // Quantity
global using IsoDecimalNumber = System.UInt64; // Quantity
global using IsoMax3Number = System.UInt64; // Quantity
global using IsoRestrictedFINDecimalNumber = System.UInt64; // Quantity
global using IsoNonNegativeDecimalNumber = System.UInt64; // Quantity
global using IsoLongDecimalNumber = System.UInt64; // Quantity
global using IsoRestrictedMonthExact2Number = System.UInt64; // Quantity
global using IsoPositiveNumber = System.UInt64; // Quantity
global using IsoMax5Number = System.UInt64; // Quantity
global using IsoMax1Number = System.UInt64; // Quantity
global using IsoDecimalNumberFraction5 = System.UInt64; // Quantity
global using IsoLongFraction21DecimalNumber = System.UInt64; // Quantity
global using IsoNonNegativeFraction5DecimalNumber = System.UInt64; // Quantity
global using IsoNonNegativeNumber = System.UInt64; // Quantity
global using IsoMax20PositiveNumber = System.UInt64; // Quantity
global using IsoMax20PositiveDecimalNumber = System.UInt64; // Quantity
global using IsoMax6NumberFraction2 = System.UInt64; // Quantity
global using IsoMax10NumberFraction2 = System.UInt64; // Quantity
global using IsoFraction5DecimalNumber = System.UInt64; // Quantity
global using IsoMax2Fraction1NonNegativeNumber = System.UInt64; // Quantity
global using IsoLongFraction19DecimalNumber = System.UInt64; // Quantity
global using IsoDayOfMonthNumber = System.UInt64; // Quantity
global using IsoMax30DecimalNumber = System.UInt64; // Quantity
global using IsoMax5PositiveNumber = System.UInt64; // Quantity
global using IsoMax10PositiveNumber = System.UInt64; // Quantity
global using IsoISOTime = System.TimeOnly; // Time
global using IsoPercentageRate = System.Decimal; // Rate
global using IsoPercentageBoundedRate = System.Decimal; // Rate
global using IsoBaseOneRate = System.Decimal; // Rate
global using IsoBaseOne14Rate = System.Decimal; // Rate
global using IsoPercentage = System.Decimal; // Rate
global using IsoBaseOne18Rate = System.Decimal; // Rate
global using IsoBaseOne25Rate = System.Decimal; // Rate
global using IsoISOYearMonth = System.UInt16; // YearMonth
global using IsoISOYear = System.UInt16; // Year
global using IsoISORestrictedYear = System.UInt16; // Year
global using IsoMax10KBinary = System.Byte[]; // Binary
global using IsoMax2MBBinary = System.Byte[]; // Binary
global using IsoMax10000Binary = System.Byte[]; // Binary
global using IsoMax3000Binary = System.Byte[]; // Binary
global using IsoMax35Binary = System.Byte[]; // Binary
global using IsoMax500Binary = System.Byte[]; // Binary
global using IsoMax140Binary = System.Byte[]; // Binary
global using IsoMin5Max16Binary = System.Byte[]; // Binary
global using IsoMax5000Binary = System.Byte[]; // Binary
global using IsoMax100KBinary = System.Byte[]; // Binary
global using IsoMax2KBinary = System.Byte[]; // Binary
global using IsoMax50Binary = System.Byte[]; // Binary
global using IsoMax4kBinary = System.Byte[]; // Binary
global using IsoMax1kBinary = System.Byte[]; // Binary
global using IsoMax10MbBinary = System.Byte[]; // Binary
global using IsoMin1Max256Binary = System.Byte[]; // Binary
global using IsoMax16Binary = System.Byte[]; // Binary
global using IsoExact20Binary = System.Byte[]; // Binary
global using IsoMax20MbBinary = System.Byte[]; // Binary
global using IsoanySimpleType = System.String; // W3C xs:anySimpleType — abstract root of the XSD simple-type hierarchy; no narrower representation possible without knowing the concrete runtime type
global using Isodate = System.DateOnly; // W3C xs:date — matches IsoISODate's existing choice for the same concept
global using IsodateTime = BeneficialStrategies.Iso20022.SimpleTypes.ISODateTime; // W3C xs:dateTime — reuses the struct built for ISO's own ISODateTime (plain DateTime can't capture the 3 permitted wire forms)
global using Isodecimal = System.Decimal; // W3C xs:decimal — matches the many Iso*Rate/Iso*Number aliases already using System.Decimal directly in this file
global using IsoENTITIES = System.String; // W3C xs:ENTITIES — DTD-era entity reference list; vestigial in schema-based XML, zero live usage, no meaningful BCL/struct mapping exists
global using IsoENTITY = System.String; // W3C xs:ENTITY — DTD-era entity reference; vestigial in schema-based XML, zero live usage, no meaningful BCL/struct mapping exists
global using IsoID = BeneficialStrategies.Iso20022.SimpleTypes.XsdID; // W3C xs:ID — 4 live usages; lexical shape only, document-wide uniqueness is a cross-element constraint this type can't enforce alone
global using IsoIDREF = BeneficialStrategies.Iso20022.SimpleTypes.XsdIDREF; // W3C xs:IDREF — same lexical shape as XsdID/XsdNCName
global using IsoIDREFS = BeneficialStrategies.Iso20022.SimpleTypes.XsdIDREFS; // W3C xs:IDREFS — whitespace-separated list of IDREF
global using IsoName = BeneficialStrategies.Iso20022.SimpleTypes.XsdName; // W3C xs:Name — XML 1.0 Name production (ASCII-range approximation, see type remarks)
global using IsoNCName = BeneficialStrategies.Iso20022.SimpleTypes.XsdNCName; // W3C xs:NCName — Name without a colon (ASCII-range approximation, see type remarks)
global using IsoNMTOKEN = BeneficialStrategies.Iso20022.SimpleTypes.XsdNMTOKEN; // W3C xs:NMTOKEN — XML 1.0 Nmtoken production (ASCII-range approximation, see type remarks)
global using IsoNMTOKENS = BeneficialStrategies.Iso20022.SimpleTypes.XsdNMTOKENS; // W3C xs:NMTOKENS — whitespace-separated list of NMTOKEN
global using IsoQName = System.Xml.XmlQualifiedName; // W3C xs:QName — verified real value equality from source (see CLAUDE.md "Class-typed properties..."); NOT YET wired into Iso20022XmlSerializer's leaf-type dispatch (IsLeafType/FormatLeaf/ParseLeaf) — currently zero live usage, so this is a documented follow-up, not a regression, if this type is ever assigned to a real field
global using Isostring = System.String; // W3C xs:string — already the exact correct mapping, not an oversight
global using Isotime = System.TimeOnly; // W3C xs:time — matches IsoISOTime's existing choice for the same concept
global using IsoISOMonth = System.Byte; // Month
// global using IsoExact4UpperCaseAlphaText = System.String; // Not in current ISO 20022 snapshot — cannot convert
// global using IsoMax47Text = System.String; // Not in current ISO 20022 snapshot — cannot convert
global using IsoNPIIdentifier = BeneficialStrategies.Iso20022.SimpleTypes.NPIIdentifier; // IdentifierSet; ISO 24366 format given in prose (13 upper-case alphanumeric + 2 check digits), pattern derived from that text
global using IsoPercentage14Rate = System.Decimal; // Rate
// External Codesets
global using CurrencyCode = System.String;
global using ActiveCurrencyCode = System.String;
global using ActiveOrHistoricCurrencyCode = System.String;
global using LanguageCode = System.String;
global using NationalityCode = System.String;
global using ExternalClearingSystemMemberCode = System.String;
global using ExternalPurposeCode_Obsolete = System.String;
global using ExternalCode = System.String;
global using ISO2ALanguageCode = System.String;
global using ISO3ACountryCode = System.String;
global using ISO3NumericCountryCode = System.String;
global using BusinessFilePriorityCode = System.String;
global using ExternalDiscrepancy1Code = System.String;
global using ExternalClearingSystemMember1Code = System.String;
global using ExternalTechnicalError1Code = System.String;
global using ExternalTechnicalErrorCode = System.String;
global using ExternalSystemEvent1Code = System.String;
global using ExternalSecuritiesLendingTypeCode = System.String;
global using ExternalSecuritiesLendingType1Code = System.String;
global using ExternalInvalidEventReason1Code = System.String;
global using ExternalInvalidPaymentsEvent1Code = System.String;
global using ExternalInvalidPaymentsEventCode = System.String;
global using ExternalInvalidEventReasonCode = System.String;
global using ParentCurrencyCode = System.String;
global using ISO3NumericCurrencyCode = System.String;
global using ExternalTrackertAlertStatus1Code = System.String;
global using ExternalTrackerAlertStatusReason1Code = System.String;
global using ExternalTrackerAlertStatusReasonCode = System.String;
global using ExternalTrackertAlertStatusCode = System.String;
global using ExternalSecuritiesUpdateReason1Code = System.String;
global using ExternalSecuritiesUpdateReasonCode = System.String;
global using ExternalNotificationCancellationReason1Code = System.String;
global using ExternalNotificationCancellationReasonCode = System.String;
global using ISO8583TransactionTypeCode = System.String;
global using ISO8583MessageReasonCode = System.String;
global using ISO8583AmountTypeCode = System.String;
global using ISOMax3ACountryCode = System.String;
global using ISOMax3ALanguageCode = System.String;
global using ISO8583ResponseCode = System.String;
global using ISO18245MerchantCategoryCode = System.String;
global using ISOCountrySubDivisionCode = System.String;
global using ISO8583AccountTypeCode = System.String;
global using ISO8583AccountEntryDeviceTypeCode = System.String;
global using ISO8583AccountIdentifierTypeCode = System.String;
global using ISO8583ActionCode = System.String;
global using ISO8583AdditionalServiceResultCode = System.String;
global using ISO8583FeeTypeCode = System.String;
global using ISO8583MessageErrorCode = System.String;
global using ISO8583NetworkManagementInformationCode = System.String;
global using ISO8583PINEntryCapabilityCode = System.String;
global using ISO8583POSConditionCode = System.String;
global using ISO8583ShippingIndicatorCode = System.String;
global using ExternalPartyRelationshipType1Code = System.String;
global using ExternalTrackerInvestigationStatusReason1Code = System.String;
global using ExternalTrackerInvestigationStatus1Code = System.String;
global using ExternalTrackerInvestigationType1Code = System.String;
global using ExternalTrackerInvestigationStatusCode = System.String;
global using ExternalTrackerInvestigationStatusReasonCode = System.String;
global using ExternalTrackerInvestigationTypeCode = System.String;
global using ExternalLegalFramework1Code = System.String;
global using ExternalLegalFrameworkCode = System.String;
global using ExternalNotificationSubType1Code = System.String;
global using ExternalNotificationSubTypeCode = System.String;
global using ExternalNotificationType1Code = System.String;
global using ExternalNotificationTypeCode = System.String;
global using ExternalPostTradeEventType1Code = System.String;
global using ExternalPostTradeEventTypeCode = System.String;
global using ExternalPaymentMethode1Code = System.String;
global using ExternalPaymentMethodeCode = System.String;
global using ExternalPenaltyPartyType1Code = System.String;
global using ExternalPenaltyPartyTypeCode = System.String;
global using ExternalProductType1Code = System.String;
global using ExternalProductTypeCode = System.String;
global using ExternalRegulatoryInformationType1Code = System.String;
global using ExternalRegulatoryInformationTypeCode = System.String;
global using ExternalRegulatoryReportingType1Code = System.String;
// ExternalSchema type aliases
global using IsoATICALaxProcessing = BeneficialStrategies.Iso20022.ExternalSchema.ATICALaxProcessing;
global using IsoLaxPayload = BeneficialStrategies.Iso20022.ExternalSchema.LaxPayload;
global using IsoSignatureEnvelope = BeneficialStrategies.Iso20022.ExternalSchema.SignatureEnvelope;
