// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;
using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.auth;

/// <summary>
/// This record is an implementation of the auth.053.001.01 ISO standard message type.
/// There are significant differences between different variants of the same message. It is crucial that you select exactly the implementation you intend to send or receive.
/// The FinancialInstrumentReportingTradingVolumeCapResultReport provides volume of trading and percentage of trading under waivers for equity instruments over a period. This message is generated by the supervisory authority for public distribution.
/// </summary>
[Description(
    @"The FinancialInstrumentReportingTradingVolumeCapResultReport provides volume of trading and percentage of trading under waivers for equity instruments over a period. This message is generated by the supervisory authority for public distribution."
)]
[IsoId("_ye5zAJuCEeaPcol5ibnfBQ")]
[DisplayName("Financial Instrument Reporting Trading Volume Cap Result Report V")]
public record FinancialInstrumentReportingTradingVolumeCapResultReportV01 : IOuterRecord
{
    /// <summary>
    /// The official ISO 20022 designation for this version of this message.
    /// </summary>
    public const string IsoIdentifier = "auth.053.001.01";

    /// <summary>
    /// The ISO specified XML tag that should be used for standardized serialization of this message.
    /// </summary>
    public const string XmlTag = "FinInstrmRptgTradgVolCapRsltRpt";

    /// <summary>
    /// The ISO specified XML namespace that should be used for standardized serialization of this message type.
    /// </summary>
    public const string DocumentNamespace = "urn:iso:std:iso:20022:tech:xsd:auth.053.001.01";

    /// <summary>
    /// The ISO specified XML element name that must surround the inner content to achieve standardized serialization.
    /// </summary>
    public const string DocumentElementName = "Document";

    /// <summary>
    /// The XML namespace in which this message is delivered.
    /// </summary>
    public static string IsoXmlNamspace => DocumentNamespace;

    /// <summary>
    /// Header information related to the global report.
    /// </summary>
    [IsoId("_N3DP4JuDEeaPcol5ibnfBQ")]
    [DisplayName("Report Header")]
    [IsoXmlTag("RptHdr")]
    public required SecuritiesMarketReportHeader1 ReportHeader { get; init; }

    /// <summary>
    /// Provides details on the volume of trades and percentage of trading under waivers of financial instruments.
    /// </summary>
    [IsoId("_Q9wMAJuMEeaPcol5ibnfBQ")]
    [DisplayName("Volume Cap Result")]
    [IsoXmlTag("VolCapRslt")]
    public required VolumeCapResult1 VolumeCapResult { get; init; }

    /// <summary>
    /// Additional information that can not be captured in the structured fields and/or any other specific block.
    /// </summary>
    [IsoId("_TcspwJuDEeaPcol5ibnfBQ")]
    [DisplayName("Supplementary Data")]
    [IsoXmlTag("SplmtryData")]
    public SupplementaryData1? SupplementaryData { get; init; }
}

// Since FinancialInstrumentReportingTradingVolumeCapResultReportV01Document is not really part of the logical business domain model,
// and only existed to facilitate implementation details of serialization, it has been appropriately removed.
// Some of the constants previously declared there have been relocated to FinancialInstrumentReportingTradingVolumeCapResultReportV01.
