// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Card transaction for which the authorisation is requested.
/// </summary>
[IsoId("_xReXwHstEeSTS7uHCe8FPQ")]
[DisplayName("Card Transaction")]
public partial record CardTransaction15
{
    #nullable enable
    
    /// <summary>
    /// Type of transaction being undertaken for the main service. 
    /// It correspond partially to the ISO 8583 field number 3.
    /// </summary>
    [IsoId("_VW8KEHsuEeSTS7uHCe8FPQ")]
    [DisplayName("Transaction Type")]
    [IsoXmlTag("TxTp")]
    public required CardPaymentServiceType7Code TransactionType { get; init; } 
    
    /// <summary>
    /// Service in addition to the main service. 
    /// It correspond partially to the ISO 8583: 2003 field number 22-3.
    /// </summary>
    [IsoId("_HzZ3IHsvEeSTS7uHCe8FPQ")]
    [DisplayName("Additional Service")]
    [IsoXmlTag("AddtlSvc")]
    public CardPaymentServiceType8Code? AdditionalService { get; init; } 
    
    /// <summary>
    /// Additional attribute of the service type. 
    /// It correspond partially to the ISO 8583: 2003 field number 22-3.
    /// </summary>
    [IsoId("_ie2mEHsvEeSTS7uHCe8FPQ")]
    [DisplayName("Service Attribute")]
    [IsoXmlTag("SvcAttr")]
    public CardPaymentServiceType3Code? ServiceAttribute { get; init; } 
    
    /// <summary>
    /// Category code conform to ISO 18245, related to the type of services or goods the merchant provides for the transaction. 
    /// It correspond to the ISO 8583 field number 18 for the version 87, field numbers 18 and 26 for the version 93, and field number 26 for the version 2003.
    /// </summary>
    [IsoId("_uMNlEHsvEeSTS7uHCe8FPQ")]
    [DisplayName("Merchant Category Code")]
    [IsoXmlTag("MrchntCtgyCd")]
    [IsoSimpleType(IsoSimpleType.Min3Max4NumericText)]
    public IsoMin3Max4NumericText? MerchantCategoryCode { get; init; } 
    
    /// <summary>
    /// Identification of the reconciliation period between the acquirer and the issuer or their respective agents.
    /// </summary>
    [IsoId("_QyfckHswEeSTS7uHCe8FPQ")]
    [DisplayName("Reconciliation")]
    [IsoXmlTag("Rcncltn")]
    public TransactionIdentifier2? Reconciliation { get; init; } 
    
    /// <summary>
    /// Date and time of the transaction transported unchanged by the acquirer from the card acceptor to the issuer. Corresponds to the CAPE data element TransactionIdentification/ TransactionDateTime.
    /// It correspond to the ISO 8583 field number 12.
    /// </summary>
    [IsoId("_ZFRyIHswEeSTS7uHCe8FPQ")]
    [DisplayName("Acceptor Transaction Date Time")]
    [IsoXmlTag("AccptrTxDtTm")]
    [IsoSimpleType(IsoSimpleType.ISODateTime)]
    public required IsoISODateTime AcceptorTransactionDateTime { get; init; } 
    
    /// <summary>
    /// Unique transaction identification generated by the acceptor or the acquirer transported unchanged by the acquirer from the card acceptor to the issuer. It is used to assist locating the original source information. Eventually it could be included in the cardholder statement. It corresponds to ISO 8583, field 37 and CAPE data element TransactionIdentification/TransactionReference.
    /// </summary>
    [IsoId("_cKaXEHswEeSTS7uHCe8FPQ")]
    [DisplayName("Acceptor Transaction Identification")]
    [IsoXmlTag("AccptrTxId")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35 ,MinimumLength = 1)]
    public required IsoMax35Text AcceptorTransactionIdentification { get; init; } 
    
    /// <summary>
    /// Number generated by the transaction Initiator to assist in identifying a transaction uniquely. This value remains unchanged for all messages within a message pair exchange, for instance an initiation/response. It corresponds to the ISO 8583 field number 11.
    /// </summary>
    [IsoId("_hHptIHswEeSTS7uHCe8FPQ")]
    [DisplayName("Initiator Transaction Identification")]
    [IsoXmlTag("InitrTxId")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35 ,MinimumLength = 1)]
    public required IsoMax35Text InitiatorTransactionIdentification { get; init; } 
    
    /// <summary>
    /// Unique identification to match transactions throughout their life cycle (for example, authorisation to financial presentment, financial presentment to chargeback). It shall contain the same value in all messages throughout a transaction’s life cycle. It corresponds partially to ISO 8583: 2003 field number 21.
    /// </summary>
    [IsoId("_lZZPIHswEeSTS7uHCe8FPQ")]
    [DisplayName("Transaction Life Cycle Identification")]
    [IsoXmlTag("TxLifeCyclId")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35 ,MinimumLength = 1)]
    public IsoMax35Text? TransactionLifeCycleIdentification { get; init; } 
    
    /// <summary>
    /// Life cycle transaction sequence number when multiple authorisations are performed for the same presentment.
    /// It corresponds partially to ISO 8583: 2003, field number 21.
    /// </summary>
    [IsoId("_wHqIoHswEeSTS7uHCe8FPQ")]
    [DisplayName("Transaction Life Cycle Sequence Number")]
    [IsoXmlTag("TxLifeCyclSeqNb")]
    [IsoSimpleType(IsoSimpleType.Number)]
    public IsoNumber? TransactionLifeCycleSequenceNumber { get; init; } 
    
    /// <summary>
    /// Total number of transactions under the same life cycle transaction sequence number.
    /// </summary>
    [IsoId("_KW0yYIIPEeSvPp7yXrNQIw")]
    [DisplayName("Transaction Life Cycle Sequence Counter")]
    [IsoXmlTag("TxLifeCyclSeqCntr")]
    [IsoSimpleType(IsoSimpleType.Number)]
    public IsoNumber? TransactionLifeCycleSequenceCounter { get; init; } 
    
    /// <summary>
    /// Identification of the original transaction.
    /// It corresponds to ISO 8583 field number 90 for the version 87, and field number 56 for the other versions.
    /// </summary>
    [IsoId("_bgmvoHsxEeSTS7uHCe8FPQ")]
    [DisplayName("Original Transaction")]
    [IsoXmlTag("OrgnlTx")]
    public CardTransaction3? OriginalTransaction { get; init; } 
    
    /// <summary>
    /// Details of the card transaction.
    /// </summary>
    [IsoId("_wkLQEHsxEeSTS7uHCe8FPQ")]
    [DisplayName("Transaction Details")]
    [IsoXmlTag("TxDtls")]
    public required CardTransactionDetail1 TransactionDetails { get; init; } 
    
    /// <summary>
    /// Outcome of the authorisation.
    /// </summary>
    [IsoId("_2WUCoHuFEeSZrqGdHyoIrw")]
    [DisplayName("Authorisation Result")]
    [IsoXmlTag("AuthstnRslt")]
    public AuthorisationResult7? AuthorisationResult { get; init; } 
    
    
    #nullable disable
    
}
