// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;
using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Payment token information.
/// </summary>
[IsoId("_OY-lIXr8EeSZrs_hiwNOWA")]
[DisplayName("Card Payment Token")]
public record CardPaymentToken4
{
    /// <summary>
    /// Surrogate value for the PAN.
    /// </summary>
    [IsoId("_dLnTAHr8EeSZrs_hiwNOWA")]
    [DisplayName("Token")]
    [IsoXmlTag("Tkn")]
    [IsoSimpleType(IsoSimpleType.Min8Max28NumericText)]
    public IsoMin8Max28NumericText? Token { get; init; }

    /// <summary>
    /// Identify a payment token inside a set of cards with the same PAN.
    /// </summary>
    [IsoId("_ibR10Hr8EeSZrs_hiwNOWA")]
    [DisplayName("Card Sequence Number")]
    [IsoXmlTag("CardSeqNb")]
    [IsoSimpleType(IsoSimpleType.Min2Max3NumericText)]
    public IsoMin2Max3NumericText? CardSequenceNumber { get; init; }

    /// <summary>
    /// Expiration date of the payment token that is generated by and maintained in the token vault.
    /// </summary>
    [IsoId("_n1I2cHr8EeSZrs_hiwNOWA")]
    [DisplayName("Token Expiry Date")]
    [IsoXmlTag("TknXpryDt")]
    [IsoSimpleType(IsoSimpleType.Max10Text)]
    [StringLength(maximumLength: 10, MinimumLength = 1)]
    public IsoMax10Text? TokenExpiryDate { get; init; }

    /// <summary>
    /// Additional payment token information.
    /// </summary>
    [IsoId("_OlsLcXr8EeSZrs_hiwNOWA")]
    [DisplayName("Token Characteristic")]
    [IsoXmlTag("TknChrtc")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35, MinimumLength = 1)]
    public IsoMax35Text? TokenCharacteristic { get; init; }

    /// <summary>
    /// Identifier of a token provider requestor.
    /// </summary>
    [IsoId("_OlsLc3r8EeSZrs_hiwNOWA")]
    [DisplayName("Token Requestor")]
    [IsoXmlTag("TknRqstr")]
    public PaymentTokenIdentifiers1? TokenRequestor { get; init; }

    /// <summary>
    /// Level of confidence resulting of the identification and authentication of the cardholder performed and the entity that performed it.
    /// </summary>
    [IsoId("_OlsLdXr8EeSZrs_hiwNOWA")]
    [DisplayName("Token Assurance Level")]
    [IsoXmlTag("TknAssrncLvl")]
    [IsoSimpleType(IsoSimpleType.Number)]
    public IsoNumber? TokenAssuranceLevel { get; init; }

    /// <summary>
    /// Information about the identification and verification of the cardholder.
    /// </summary>
    [IsoId("_vM3R8Hr8EeSZrs_hiwNOWA")]
    [DisplayName("Token Assurance Data")]
    [IsoXmlTag("TknAssrncData")]
    [IsoSimpleType(IsoSimpleType.Max500Binary)]
    public IsoMax500Binary? TokenAssuranceData { get; init; }
}
