// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;
using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Identification of the original transaction.
/// It corresponds to ISO 8583, field number 90 for the version 87, and 56 for the other versions.
/// </summary>
[IsoId("_BbVP4XsxEeSTS7uHCe8FPQ")]
[DisplayName("Card Transaction")]
public record CardTransaction3
{
    /// <summary>
    /// Date and time of the transaction transported unchanged by the acquirer from the card acceptor to the issuer. Corresponds to the CAPE data element TransactionIdentification/ TransactionDateTime.
    /// It correspond to the ISO 8583 field number 12.
    /// </summary>
    [IsoId("_Bo-qW3sxEeSTS7uHCe8FPQ")]
    [DisplayName("Acceptor Transaction Date Time")]
    [IsoXmlTag("AccptrTxDtTm")]
    [IsoSimpleType(IsoSimpleType.ISODateTime)]
    public required IsoISODateTime AcceptorTransactionDateTime { get; init; }

    /// <summary>
    /// Number generated by the transaction of the original transaction.
    /// </summary>
    [IsoId("_Bo-qX3sxEeSTS7uHCe8FPQ")]
    [DisplayName("Initiator Transaction Identification")]
    [IsoXmlTag("InitrTxId")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35, MinimumLength = 1)]
    public required IsoMax35Text InitiatorTransactionIdentification { get; init; }

    /// <summary>
    /// Identification of the entity, initiator of the transaction.
    /// </summary>
    [IsoId("_QxgIoHsxEeSTS7uHCe8FPQ")]
    [DisplayName("Initiator Identification")]
    [IsoXmlTag("InitrId")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35, MinimumLength = 1)]
    public required IsoMax35Text InitiatorIdentification { get; init; }
}
