// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Card transaction for which the authorisation has been requested.
/// </summary>
[IsoId("_1xK7IXu6EeSLmfFG0DG7zQ")]
[DisplayName("Card Transaction")]
public partial record CardTransaction9
{
    #nullable enable
    
    /// <summary>
    /// Type of reconciliation.
    /// </summary>
    [IsoId("_9yA6MHu8EeSLmfFG0DG7zQ")]
    [DisplayName("Reconciliation Type")]
    [IsoXmlTag("RcncltnTp")]
    public CardServiceType1Code? ReconciliationType { get; init; } 
    
    /// <summary>
    /// Identification of the reconciliation period between the acquirer and the issuer or their respective agents.
    /// </summary>
    [IsoId("_191eI3u6EeSLmfFG0DG7zQ")]
    [DisplayName("Reconciliation")]
    [IsoXmlTag("Rcncltn")]
    public TransactionIdentifier2? Reconciliation { get; init; } 
    
    /// <summary>
    /// Date when the settlement is expected.
    /// </summary>
    [IsoId("_eaxVEHu9EeSLmfFG0DG7zQ")]
    [DisplayName("Inter Bank Settlement Date")]
    [IsoXmlTag("IntrBkSttlmDt")]
    [IsoSimpleType(IsoSimpleType.ISODate)]
    public IsoISODate? InterBankSettlementDate { get; init; } 
    
    /// <summary>
    /// Date and time of the transaction.
    /// </summary>
    [IsoId("_kJP60Hu9EeSLmfFG0DG7zQ")]
    [DisplayName("Initiator Transaction Date Time")]
    [IsoXmlTag("InitrTxDtTm")]
    [IsoSimpleType(IsoSimpleType.ISODateTime)]
    public required IsoISODateTime InitiatorTransactionDateTime { get; init; } 
    
    /// <summary>
    /// Number generated by the transaction Initiator to assist in identifying a transaction uniquely. This value remains unchanged for all messages within a message pair exchange, for instance an initiation/response. It corresponds to the ISO 8583 field number 11.
    /// </summary>
    [IsoId("_191eJ3u6EeSLmfFG0DG7zQ")]
    [DisplayName("Initiator Transaction Identification")]
    [IsoXmlTag("InitrTxId")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35 ,MinimumLength = 1)]
    public required IsoMax35Text InitiatorTransactionIdentification { get; init; } 
    
    /// <summary>
    /// Unique identification to match transactions throughout their life cycle (for example, authorisation to financial presentment, financial presentment to chargeback). It shall contain the same value in all messages throughout a transaction’s life cycle. It corresponds partially to ISO 8583: 2003 field number 21.
    /// </summary>
    [IsoId("_191eKXu6EeSLmfFG0DG7zQ")]
    [DisplayName("Transaction Life Cycle Identification")]
    [IsoXmlTag("TxLifeCyclId")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35 ,MinimumLength = 1)]
    public IsoMax35Text? TransactionLifeCycleIdentification { get; init; } 
    
    /// <summary>
    /// Totals of the reconciliation.
    /// </summary>
    [IsoId("_SJWxUHu-EeSLmfFG0DG7zQ")]
    [DisplayName("Reconciliation Totals")]
    [IsoXmlTag("RcncltnTtls")]
    public TransactionTotals4? ReconciliationTotals { get; init; } 
    
    /// <summary>
    /// Net value of all gross amounts.
    /// </summary>
    [IsoId("_v7YkwHvAEeSLmfFG0DG7zQ")]
    [DisplayName("Amount Net Reconciliation")]
    [IsoXmlTag("AmtNetRcncltn")]
    public AmountAndDirection41? AmountNetReconciliation { get; init; } 
    
    /// <summary>
    /// Response to the reconciliation.
    /// </summary>
    [IsoId("_76BrUIOzEeSWSLYdc10LRg")]
    [DisplayName("Transaction Response")]
    [IsoXmlTag("TxRspn")]
    public ResponseType2? TransactionResponse { get; init; } 
    
    
    #nullable disable
    
}
