// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;
using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Contains authentication related data. such as 3DS authentication data.
/// </summary>
[IsoId("_EujNMGZ8EfCX7uJiAWHfoQ")]
[DisplayName("Card Authentication Data1")]
public record CardAuthenticationData1
{
    /// <summary>
    /// Specifies that card authentication is performed using credentials linked to the cardholder's account rather than the physical card.
    /// </summary>
    [IsoId("_Qgd0sGZ_EfCX7uJiAWHfoQ")]
    [DisplayName("Account Based Digital Signature")]
    [IsoXmlTag("AcctBasedDgtlSgntr")]
    public IsoExact2NumericText? AccountBasedDigitalSignature { get; init; }

    /// <summary>
    /// Contains a value assigned to a Secure Electronic Commerce cardholder certificate issued by the acquirer's certificate authority.
    /// </summary>
    [IsoId("_tsu6kGZ_EfCX7uJiAWHfoQ")]
    [DisplayName("Cardholder Certificate Serial Number")]
    [IsoXmlTag("CrdhldrCertSrlNb")]
    public IsoMax16Binary? CardholderCertificateSerialNumber { get; init; }

    /// <summary>
    /// Contains a value assigned to a secure electronic commerce merchant certificate issued by the acquirer's certificate authority.
    /// </summary>
    [IsoId("_7H0msGZ_EfCX7uJiAWHfoQ")]
    [DisplayName("Acceptor Certificate Serial Number")]
    [IsoXmlTag("AccptrCertSrlNb")]
    public IsoMax16Binary? AcceptorCertificateSerialNumber { get; init; }

    /// <summary>
    /// The Protocol version number of the specification used by the system creating authentication message.
    /// </summary>
    [IsoId("_GRetoGZ-EfCX7uJiAWHfoQ")]
    [DisplayName("Message Version")]
    [IsoXmlTag("MsgVrsn")]
    public IsoMin5Max8Text? MessageVersion { get; init; }

    /// <summary>
    /// Contains a unique secure electronic commerce number generated by the merchant server to identify the transaction.
    /// </summary>
    [IsoId("_jffOAGaAEfCX7uJiAWHfoQ")]
    [DisplayName("XID")]
    [IsoXmlTag("XID")]
    public IsoExact20Binary? XID { get; init; }

    /// <summary>
    /// Payment System-specific value provided by the ACS or the DS using an algorithm defined by Payment System.
    /// </summary>
    [IsoId("_t5ddEGaBEfCX7uJiAWHfoQ")]
    [DisplayName("Authentication Value")]
    [IsoXmlTag("AuthntcnVal")]
    public IsoExact20Binary? AuthenticationValue { get; init; }

    /// <summary>
    /// Contains authentication code.
    /// </summary>
    [IsoId("_P08rIGaCEfCX7uJiAWHfoQ")]
    [DisplayName("Authentication Code")]
    [IsoXmlTag("AuthntcnCd")]
    public IsoMax50Text? AuthenticationCode { get; init; }

    /// <summary>
    /// Contains the authentication message category.
    /// </summary>
    [IsoId("_pOqFYGaCEfCX7uJiAWHfoQ")]
    [DisplayName("Message Category")]
    [IsoXmlTag("MsgCtgy")]
    public IsoExact2NumericText? MessageCategory { get; init; }

    /// <summary>
    /// Merchant name assigned by the Acquirer or Payment System during the authentication.
    /// </summary>
    [IsoId("_ElDR8GaHEfCX7uJiAWHfoQ")]
    [DisplayName("Authentication Merchant Name")]
    [IsoXmlTag("AuthntcnMrchntNm")]
    public IsoMax40Text? AuthenticationMerchantName { get; init; }

    /// <summary>
    /// IP address of the Browser.
    /// </summary>
    [IsoId("_Ug5DkGaHEfCX7uJiAWHfoQ")]
    [DisplayName("Browser IP Address")]
    [IsoXmlTag("BrwsrIPAdr")]
    public IsoMax45Text? BrowserIPAddress { get; init; }

    /// <summary>
    /// Device information gathered by the 3DS SDK from a Consumer Device.
    /// </summary>
    [IsoId("_l66DYGaHEfCX7uJiAWHfoQ")]
    [DisplayName("Device Information")]
    [IsoXmlTag("DvcInf")]
    public IsoMax10KText? DeviceInformation { get; init; }

    /// <summary>
    /// Purchase amount in minor units of currency with all punctuation removed.
    /// </summary>
    [IsoId("_DEFZAGaIEfCX7uJiAWHfoQ")]
    [DisplayName("Purchase Amount")]
    [IsoXmlTag("PurchsAmt")]
    public IsoMax48Text? PurchaseAmount { get; init; }

    /// <summary>
    /// Currency in which purchase amount is expressed.
    /// </summary>
    [IsoId("_TSZasGaIEfCX7uJiAWHfoQ")]
    [DisplayName("Purchase Currency")]
    [IsoXmlTag("PurchsCcy")]
    public ISO3NumericCurrencyCode? PurchaseCurrency { get; init; }

    /// <summary>
    /// Date and time of the authentication converted into UTC.
    /// </summary>
    [IsoId("_beAKMGaIEfCX7uJiAWHfoQ")]
    [DisplayName("Purchase Date Time")]
    [IsoXmlTag("PurchsDtTm")]
    public IsoExact14NumericText? PurchaseDateTime { get; init; }

    /// <summary>
    /// Indicates whether the Cardholder Shipping Address and Cardholder Billing Address are the same.
    /// </summary>
    [IsoId("_b71gQGaJEfCX7uJiAWHfoQ")]
    [DisplayName("Address Match Indicator")]
    [IsoXmlTag("AdrMtchInd")]
    public IsoExact1Text? AddressMatchIndicator { get; init; }

    /// <summary>
    /// Universally unique transaction identifier assigned by the Intermediary entity to identify a single transaction.
    /// </summary>
    [IsoId("_t_YlQGaJEfCX7uJiAWHfoQ")]
    [DisplayName("Intermediary Transaction Identifier")]
    [IsoXmlTag("IntrmyTxIdr")]
    public IsoMax36Text? IntermediaryTransactionIdentifier { get; init; }

    /// <summary>
    /// Universally Unique transaction identifier assigned by the authentication server to identify a single transaction.
    /// </summary>
    [IsoId("_8L010GaJEfCX7uJiAWHfoQ")]
    [DisplayName("Authentication Server Transaction Identifier")]
    [IsoXmlTag("AuthntcnSvrTxIdr")]
    public IsoMax36Text? AuthenticationServerTransactionIdentifier { get; init; }

    /// <summary>
    /// Indicate the authentication status.
    /// </summary>
    [IsoId("_zW-fkGaKEfCX7uJiAWHfoQ")]
    [DisplayName("Authentication Status")]
    [IsoXmlTag("AuthntcnSts")]
    public IsoExact1AlphaText? AuthenticationStatus { get; init; }

    /// <summary>
    /// External IP address used by the 3DS Requestor App when it connects to the 3DS Requestor environment.
    /// </summary>
    [IsoId("_V0wiYGaLEfCX7uJiAWHfoQ")]
    [DisplayName("Application IP Address")]
    [IsoXmlTag("ApplIPAdr")]
    public IsoMax45Text? ApplicationIPAddress { get; init; }

    /// <summary>
    /// Indicates shipping method chosen for the transaction.
    /// </summary>
    [IsoId("_o4Tr0GaLEfCX7uJiAWHfoQ")]
    [DisplayName("Shipping Indicator")]
    [IsoXmlTag("ShppgInd")]
    public ISO8583ShippingIndicatorCode? ShippingIndicator { get; init; }

    /// <summary>
    /// Universally unique identification that is created for each installation of the 3DS Requestor App on a Consumer Device.
    /// </summary>
    [IsoId("_P2A6UGlwEfCyxsm1jzUNug")]
    [DisplayName("SDK Application Identification")]
    [IsoXmlTag("SDKApplId")]
    public IsoMax37Text? SDKApplicationIdentification { get; init; }

    /// <summary>
    /// Unique and immutable identifier linked to a device that is consistent across 3DS transactions for the specific user device.
    /// </summary>
    [IsoId("_FCFpUG2EEfC68Y4jZPNEug")]
    [DisplayName("Device Identification")]
    [IsoXmlTag("DvcId")]
    public SimpleValueList<IsoMax64Text> DeviceIdentification { get; init; } = [];

    /// <summary>
    /// Contain value to indicates the device type.
    /// </summary>
    [IsoId("_6OtpgG2HEfC68Y4jZPNEug")]
    [DisplayName("Device Type")]
    [IsoXmlTag("DvcTp")]
    public SimpleValueList<IsoExact2NumericText> DeviceType { get; init; } = [];

    /// <summary>
    /// Indicate the status of recurring transaction data provided in the authentication.
    /// </summary>
    [IsoId("_Ai0nkG8XEfC68Y4jZPNEug")]
    [DisplayName("Recurring Transaction Setup")]
    [IsoXmlTag("RcrngTxSetp")]
    public IsoExact3AlphaNumericText? RecurringTransactionSetup { get; init; }

    /// <summary>
    /// Identify the third party who provided the authentication service.
    /// </summary>
    [IsoId("_YQpu0G8XEfC68Y4jZPNEug")]
    [DisplayName("Third Party Identification")]
    [IsoXmlTag("ThrdPtyId")]
    public IsoMax64Text? ThirdPartyIdentification { get; init; }

    /// <summary>
    /// Contains the Risk score provided by the third party service provider.
    /// </summary>
    [IsoId("_e7PlQW8cEfC68Y4jZPNEug")]
    [DisplayName("Third Party Risk Score")]
    [IsoXmlTag("ThrdPtyRskScore")]
    public IsoExact2NumericText? ThirdPartyRiskScore { get; init; }

    /// <summary>
    /// Contains authentication service provider-generated unique identifier that identifies a transaction.
    /// </summary>
    [IsoId("_3aVjoG8XEfC68Y4jZPNEug")]
    [DisplayName("Session Identification")]
    [IsoXmlTag("SsnId")]
    public IsoMax35Text? SessionIdentification { get; init; }

    /// <summary>
    /// Contains the velocity count for the IP address of a 3D-secure transaction.
    /// </summary>
    [IsoId("_BzxcoG8YEfC68Y4jZPNEug")]
    [DisplayName("IP Address Velocity Count")]
    [IsoXmlTag("IPAdrVlctyCnt")]
    public IsoExact2NumericText? IPAddressVelocityCount { get; init; }

    /// <summary>
    /// Contains the velocity count for the device ID of a 3D-secure transaction.
    /// </summary>
    [IsoId("_VBkuQW8YEfC68Y4jZPNEug")]
    [DisplayName("Device Identification Velocity Count")]
    [IsoXmlTag("DvcIdVlctyCnt")]
    public IsoExact2NumericText? DeviceIdentificationVelocityCount { get; init; }

    /// <summary>
    /// Indicate whether the transaction has sufficient authentication data.
    /// </summary>
    [IsoId("_FuQwsG8iEfC68Y4jZPNEug")]
    [DisplayName("Data Quality")]
    [IsoXmlTag("DataQlty")]
    public IsoTrueFalseIndicator? DataQuality { get; init; }

    /// <summary>
    /// Identifies the authentication solution used to process the transaction.
    /// </summary>
    [IsoId("_hYWSIG8iEfC68Y4jZPNEug")]
    [DisplayName("Programme")]
    [IsoXmlTag("Prgrmm")]
    public IsoMax10Text? Programme { get; init; }

    /// <summary>
    /// Reserved for private data.
    /// </summary>
    [IsoId("_7aY3sm8iEfC68Y4jZPNEug")]
    [DisplayName("Private Data")]
    [IsoXmlTag("PrvtData")]
    public ValueList<LaxProcessing> PrivateData { get; init; } = [];

    /// <summary>
    /// Reserved to define data unique to the country applications.
    /// </summary>
    [IsoId("_7aY3s28iEfC68Y4jZPNEug")]
    [DisplayName("National Data")]
    [IsoXmlTag("NtlData")]
    public ValueList<LaxProcessing> NationalData { get; init; } = [];
}
