// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;
using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Card transaction for which the financial authorisation has been requested.
/// </summary>
[IsoId("_YXjg8YK5EeSqNu7AiKfyqQ")]
[DisplayName("Card Transaction")]
public record CardTransaction6
{
    /// <summary>
    /// Type of transaction being undertaken for the main service.
    /// It correspond partially to the ISO 8583, field number 3.
    /// </summary>
    [IsoId("_YnLRUYK5EeSqNu7AiKfyqQ")]
    [DisplayName("Transaction Type")]
    [IsoXmlTag("TxTp")]
    public required CardPaymentServiceType7Code TransactionType { get; init; }

    /// <summary>
    /// Identification of the reconciliation period between the acquirer and the issuer or their respective agents.
    /// </summary>
    [IsoId("_YnLRU4K5EeSqNu7AiKfyqQ")]
    [DisplayName("Reconciliation")]
    [IsoXmlTag("Rcncltn")]
    public TransactionIdentifier2? Reconciliation { get; init; }

    /// <summary>
    /// Date and time of the transaction transported unchanged by the acquirer from the card acceptor to the issuer. Corresponds to the CAPE data element TransactionIdentification/ TransactionDateTime.
    /// It correspond to the ISO 8583, field number 12.
    /// </summary>
    [IsoId("_YnLRVYK5EeSqNu7AiKfyqQ")]
    [DisplayName("Acceptor Transaction Date Time")]
    [IsoXmlTag("AccptrTxDtTm")]
    [IsoSimpleType(IsoSimpleType.ISODateTime)]
    public required IsoISODateTime AcceptorTransactionDateTime { get; init; }

    /// <summary>
    /// Number generated by the transaction Initiator to assist in identifying a transaction uniquely. This value remains unchanged for all messages within a message pair exchange, for instance an initiation/response. It corresponds to the ISO 8583 field number 11.
    /// </summary>
    [IsoId("_YnLRV4K5EeSqNu7AiKfyqQ")]
    [DisplayName("Initiator Transaction Identification")]
    [IsoXmlTag("InitrTxId")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35, MinimumLength = 1)]
    public required IsoMax35Text InitiatorTransactionIdentification { get; init; }

    /// <summary>
    /// Unique identification to match transactions throughout their life cycle (for example, authorisation to financial presentment, financial presentment to chargeback). It shall contain the same value in all messages throughout a transaction’s life cycle. It corresponds partially to ISO 8583: 2003 field number 21.
    /// </summary>
    [IsoId("_YnLRWYK5EeSqNu7AiKfyqQ")]
    [DisplayName("Transaction Life Cycle Identification")]
    [IsoXmlTag("TxLifeCyclId")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35, MinimumLength = 1)]
    public IsoMax35Text? TransactionLifeCycleIdentification { get; init; }

    /// <summary>
    /// Life cycle transaction sequence number when multiple authorisations are performed for the same presentment.
    /// It corresponds partially to ISO 8583: 2003, field number 21.
    /// </summary>
    [IsoId("_YnLRW4K5EeSqNu7AiKfyqQ")]
    [DisplayName("Transaction Life Cycle Sequence Number")]
    [IsoXmlTag("TxLifeCyclSeqNb")]
    [IsoSimpleType(IsoSimpleType.Number)]
    public IsoNumber? TransactionLifeCycleSequenceNumber { get; init; }

    /// <summary>
    /// Total number of transactions under the same life cycle transaction sequence number.
    /// </summary>
    [IsoId("_YnLRXYK5EeSqNu7AiKfyqQ")]
    [DisplayName("Transaction Life Cycle Sequence Counter")]
    [IsoXmlTag("TxLifeCyclSeqCntr")]
    [IsoSimpleType(IsoSimpleType.Number)]
    public IsoNumber? TransactionLifeCycleSequenceCounter { get; init; }

    /// <summary>
    /// Data supplied by a card issuer in response messages or in issuer generated messages, that the acquirer may be required to be provided in subsequent messages. It corresponds to ISO 8583: 93 and 2003 field number 95.
    /// </summary>
    [IsoId("_C-aBgC7xEeWc7f-D6ByqMg")]
    [DisplayName("Card Issuer Reference Data")]
    [IsoXmlTag("CardIssrRefData")]
    [IsoSimpleType(IsoSimpleType.Max140Text)]
    [StringLength(maximumLength: 140, MinimumLength = 1)]
    public IsoMax140Text? CardIssuerReferenceData { get; init; }

    /// <summary>
    /// Details of the card transaction.
    /// </summary>
    [IsoId("_YnLRX4K5EeSqNu7AiKfyqQ")]
    [DisplayName("Transaction Details")]
    [IsoXmlTag("TxDtls")]
    public required CardTransactionDetail4 TransactionDetails { get; init; }

    /// <summary>
    /// Outcome of the authorisation.
    /// </summary>
    [IsoId("_YnLRYYK5EeSqNu7AiKfyqQ")]
    [DisplayName("Authorisation Result")]
    [IsoXmlTag("AuthstnRslt")]
    public AuthorisationResult8? AuthorisationResult { get; init; }
}
