// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;
using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Merchant token information.
/// </summary>
[IsoId("_U_eg0U7ZEeyGi9JAv6wq7Q")]
[DisplayName("Merchant Token")]
public record MerchantToken2
{
    /// <summary>
    /// Surrogate value of the PAN.
    /// </summary>
    [IsoId("_VGaPQU7ZEeyGi9JAv6wq7Q")]
    [DisplayName("Token")]
    [IsoXmlTag("Tkn")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35, MinimumLength = 1)]
    public IsoMax35Text? Token { get; init; }

    /// <summary>
    /// Expiration date of the payment token that is generated by and maintained in the token vault.
    /// </summary>
    [IsoId("_VGaPQ07ZEeyGi9JAv6wq7Q")]
    [DisplayName("Token Expiry Date")]
    [IsoXmlTag("TknXpryDt")]
    [IsoSimpleType(IsoSimpleType.Max10Text)]
    [StringLength(maximumLength: 10, MinimumLength = 1)]
    public IsoMax10Text? TokenExpiryDate { get; init; }

    /// <summary>
    /// Additional payment token information.
    /// </summary>
    [IsoId("_VGaPRU7ZEeyGi9JAv6wq7Q")]
    [DisplayName("Token Characteristic")]
    [IsoXmlTag("TknChrtc")]
    [IsoSimpleType(IsoSimpleType.Max35Text)]
    [StringLength(maximumLength: 35, MinimumLength = 1)]
    public IsoMax35Text? TokenCharacteristic { get; init; }

    /// <summary>
    /// Identifier of a token provider requestor.
    /// </summary>
    [IsoId("_VGaPR07ZEeyGi9JAv6wq7Q")]
    [DisplayName("Token Requestor")]
    [IsoXmlTag("TknRqstr")]
    public PaymentTokenIdentifiers1? TokenRequestor { get; init; }

    /// <summary>
    /// Level of confidence resulting of the identification and authentication of the cardholder performed and the entity that performed it.
    /// </summary>
    [IsoId("_VGaPSU7ZEeyGi9JAv6wq7Q")]
    [DisplayName("Token Assurance Level")]
    [IsoXmlTag("TknAssrncLvl")]
    [IsoSimpleType(IsoSimpleType.Number)]
    public IsoNumber? TokenAssuranceLevel { get; init; }

    /// <summary>
    /// Information about the identification and verification of the cardholder.
    /// </summary>
    [IsoId("_VGaPS07ZEeyGi9JAv6wq7Q")]
    [DisplayName("Token Assurance Data")]
    [IsoXmlTag("TknAssrncData")]
    [IsoSimpleType(IsoSimpleType.Max500Binary)]
    public IsoMax500Binary? TokenAssuranceData { get; init; }

    /// <summary>
    /// Value that allows a Token Service Provider to indicate the identification and verification performed representing the binding of the payment token to the underlying PAN and cardholder.
    /// </summary>
    [IsoId("_VGaPTU7ZEeyGi9JAv6wq7Q")]
    [DisplayName("Token Assurance Method")]
    [IsoXmlTag("TknAssrncMtd")]
    [IsoSimpleType(IsoSimpleType.Max2NumericText)]
    public IsoMax2NumericText? TokenAssuranceMethod { get; init; }

    /// <summary>
    /// Original transaction was initiated by Token.
    /// </summary>
    [IsoId("_VGaPT07ZEeyGi9JAv6wq7Q")]
    [DisplayName("Token Initiated Indicator")]
    [IsoXmlTag("TknInittdInd")]
    [IsoSimpleType(IsoSimpleType.TrueFalseIndicator)]
    public IsoTrueFalseIndicator? TokenInitiatedIndicator { get; init; }
}
