// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;
using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Customer or Merchant receipts generated by the POI system.
/// </summary>
[IsoId("_a2GKkQxrEeqdx6buGpCCQw")]
[DisplayName("Payment Receipt")]
public record PaymentReceipt2
{
    /// <summary>
    /// Qualification of the document to print to the Cashier or the Customer.
    /// </summary>
    [IsoId("_bA1a8QxrEeqdx6buGpCCQw")]
    [DisplayName("Document Qualifier")]
    [IsoXmlTag("DocQlfr")]
    public required DocumentType7Code DocumentQualifier { get; init; }

    /// <summary>
    /// Flag is the print is integrated to other prints.
    /// </summary>
    [IsoId("_bA1a8wxrEeqdx6buGpCCQw")]
    [DisplayName("Integrated Print Flag")]
    [IsoXmlTag("IntgrtdPrtFlg")]
    [IsoSimpleType(IsoSimpleType.TrueFalseIndicator)]
    public IsoTrueFalseIndicator? IntegratedPrintFlag { get; init; }

    /// <summary>
    /// Flag to indicate that the cardholder payment receipt requires a signature by the customer.
    /// </summary>
    [IsoId("_bA1a9QxrEeqdx6buGpCCQw")]
    [DisplayName("Required Signature Flag")]
    [IsoXmlTag("ReqrdSgntrFlg")]
    [IsoSimpleType(IsoSimpleType.TrueFalseIndicator)]
    public IsoTrueFalseIndicator? RequiredSignatureFlag { get; init; }

    /// <summary>
    /// Document to print.
    /// </summary>
    [IsoId("_bA1a9wxrEeqdx6buGpCCQw")]
    [DisplayName("Output Content")]
    [IsoXmlTag("OutptCntt")]
    public required ActionMessage7 OutputContent { get; init; }
}
