// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;
using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Customer or merchant receipts generated by the POI system.
/// </summary>
[IsoId("_0qGlUbZgEfCUZfsQO4rYeA")]
[DisplayName("Payment Receipt7")]
public record PaymentReceipt7
{
    /// <summary>
    /// Qualification of the document to print to the Cashier or the Customer.
    /// </summary>
    [IsoId("_0rKVRbZgEfCUZfsQO4rYeA")]
    [DisplayName("Document Qualifier")]
    [IsoXmlTag("DocQlfr")]
    public required DocumentType7Code DocumentQualifier { get; init; }

    /// <summary>
    /// Flag is the print is integrated to other prints.
    /// </summary>
    [IsoId("_0rKVS7ZgEfCUZfsQO4rYeA")]
    [DisplayName("Integrated Print Flag")]
    [IsoXmlTag("IntgrtdPrtFlg")]
    public IsoTrueFalseIndicator? IntegratedPrintFlag { get; init; }

    /// <summary>
    /// Flag to indicate that the cardholder payment receipt requires a signature by the customer.
    /// </summary>
    [IsoId("_0rKVUbZgEfCUZfsQO4rYeA")]
    [DisplayName("Required Signature Flag")]
    [IsoXmlTag("ReqrdSgntrFlg")]
    public IsoTrueFalseIndicator? RequiredSignatureFlag { get; init; }

    /// <summary>
    /// Document to print.
    /// </summary>
    [IsoId("_0rKVV7ZgEfCUZfsQO4rYeA")]
    [DisplayName("Output Content")]
    [IsoXmlTag("OutptCntt")]
    public required ActionMessage12 OutputContent { get; init; }
}
