// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using BeneficialStrategies.Iso20022.Choices;
using BeneficialStrategies.Iso20022.ExternalSchema;
using BeneficialStrategies.Iso20022.UserDefined;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Xml.Linq;

namespace BeneficialStrategies.Iso20022.Components;

/// <summary>
/// Details of the transaction.
/// </summary>
[IsoId("_S-6mMdp-Ed-ak6NoX_4Aeg_-160365271")]
[DisplayName("Transaction Details")]
public partial record TransactionDetails3
{
    #nullable enable
    
    /// <summary>
    /// Unique identification assigned to a trade. This is the reference generated by a firm or the reference allocated by the executing system if the trade was executed automatically.
    /// </summary>
    [IsoId("_S-6mMtp-Ed-ak6NoX_4Aeg_-160365269")]
    [DisplayName("Trade Reference")]
    [IsoXmlTag("TradRef")]
    [IsoSimpleType(IsoSimpleType.Max70Text)]
    [StringLength(maximumLength: 70 ,MinimumLength = 1)]
    public required IsoMax70Text TradeReference { get; init; } 
    
    /// <summary>
    /// Reference that links to other trades that are/will be sent, eg for straddles where put and call legs need to be reported together.
    /// </summary>
    [IsoId("_S-6mM9p-Ed-ak6NoX_4Aeg_-160365253")]
    [DisplayName("Associated Trade Reference")]
    [IsoXmlTag("AssoctdTradRef")]
    [IsoSimpleType(IsoSimpleType.Max70Text)]
    [StringLength(maximumLength: 70 ,MinimumLength = 1)]
    public IsoMax70Text? AssociatedTradeReference { get; init; } 
    
    /// <summary>
    /// Identifies the execution venue. In the case of an exchange or a Multilateral Trading Facility (MTF), this should be identified using a MIC code. In the case of a systematic internaliser, place of trade should be identified using a BIC code.
    /// </summary>
    [IsoId("_S-6mNNp-Ed-ak6NoX_4Aeg_-160365236")]
    [DisplayName("Place Of Trade")]
    [IsoXmlTag("PlcOfTrad")]
    public required PlaceOfTradeIdentification2Choice_ PlaceOfTrade { get; init; } 
    
    /// <summary>
    /// Specifies the date/time on which the trade was executed.
    /// </summary>
    [IsoId("_S-6mNdp-Ed-ak6NoX_4Aeg_-160365218")]
    [DisplayName("Trade Date Time")]
    [IsoXmlTag("TradDtTm")]
    [IsoSimpleType(IsoSimpleType.ISODateTime)]
    public required IsoISODateTime TradeDateTime { get; init; } 
    
    /// <summary>
    /// Provides details of the financial instrument for which the transaction report is being sent.
    /// </summary>
    [IsoId("_S-6mNtp-Ed-ak6NoX_4Aeg_-160364400")]
    [DisplayName("Financial Instrument Details")]
    [IsoXmlTag("FinInstrmDtls")]
    public required FinancialInstrument15 FinancialInstrumentDetails { get; init; } 
    
    /// <summary>
    /// Identifies whether the transaction was a buy or a sell from the perspective of the reporting firm.
    /// </summary>
    [IsoId("_S-6mN9p-Ed-ak6NoX_4Aeg_-160365193")]
    [DisplayName("Side")]
    [IsoXmlTag("Sd")]
    public required OrderDriverCode Side { get; init; } 
    
    /// <summary>
    /// Identifies the regulator(s) to whom the transaction report must be sent.
    /// </summary>
    [IsoId("_S-6mONp-Ed-ak6NoX_4Aeg_-160364357")]
    [DisplayName("Transaction Report Marker")]
    [IsoXmlTag("TxRptMrkr")]
    [MinLength(0)]
    [MaxLength(10)]
    public ValueList<PartyIdentification24Choice_> TransactionReportMarker { get; init; } = [];
    
    /// <summary>
    /// Provides details of the counterparty.
    /// </summary>
    [IsoId("_S-6mOdp-Ed-ak6NoX_4Aeg_-160364512")]
    [DisplayName("Counterparty")]
    [IsoXmlTag("CtrPty")]
    public required PartyIdentification11Choice_ Counterparty { get; init; } 
    
    /// <summary>
    /// Provides details of the client.
    /// </summary>
    [IsoId("_S_EXMNp-Ed-ak6NoX_4Aeg_-160364802")]
    [DisplayName("Client")]
    [IsoXmlTag("Clnt")]
    public PartyIdentification23? Client { get; init; } 
    
    /// <summary>
    /// Identifies the trading capacity of the firm reporting the transaction, eg Agent or Principal.
    /// </summary>
    [IsoId("_S_EXMdp-Ed-ak6NoX_4Aeg_-160364941")]
    [DisplayName("Capacity")]
    [IsoXmlTag("Cpcty")]
    public required TradingCapacity3Code Capacity { get; init; } 
    
    /// <summary>
    /// Specifies the currency and price at which the trade has been executed, excluding commission or accrued interest.
    /// </summary>
    [IsoId("_S_EXMtp-Ed-ak6NoX_4Aeg_-160364916")]
    [DisplayName("Executed Trade Price")]
    [IsoXmlTag("ExctdTradPric")]
    public required PriceRateOrAmountChoice_ ExecutedTradePrice { get; init; } 
    
    /// <summary>
    /// Quantity of financial instrument executed by the trading party.
    /// </summary>
    [IsoId("_S_EXM9p-Ed-ak6NoX_4Aeg_-160364899")]
    [DisplayName("Executed Trade Quantity")]
    [IsoXmlTag("ExctdTradQty")]
    public required UnitOrFaceAmountChoice_ ExecutedTradeQuantity { get; init; } 
    
    /// <summary>
    /// The total consideration or value.
    /// </summary>
    [IsoId("_S_EXNNp-Ed-ak6NoX_4Aeg_-160364881")]
    [DisplayName("Settlement Amount")]
    [IsoXmlTag("SttlmAmt")]
    public ActiveCurrencyAndAmount? SettlementAmount { get; init; } 
    
    /// <summary>
    /// Identifies the intended settlement date.
    /// </summary>
    [IsoId("_S_EXNdp-Ed-ak6NoX_4Aeg_-160364864")]
    [DisplayName("Settlement Date")]
    [IsoXmlTag("SttlmDt")]
    [IsoSimpleType(IsoSimpleType.ISODateTime)]
    public IsoISODateTime? SettlementDate { get; init; } 
    
    /// <summary>
    /// Provides details of the person/organisation that has the power of attorney.
    /// </summary>
    [IsoId("_S_EXNtp-Ed-ak6NoX_4Aeg_-160364417")]
    [DisplayName("Proxy Holder")]
    [IsoXmlTag("PrxyHldr")]
    public PartyIdentification2Choice_? ProxyHolder { get; init; } 
    
    /// <summary>
    /// Additional domestic regulatory transaction information.
    /// </summary>
    [IsoId("_S_EXN9p-Ed-ak6NoX_4Aeg_-160364846")]
    [DisplayName("Additional Information")]
    [IsoXmlTag("AddtlInf")]
    [IsoSimpleType(IsoSimpleType.Max350Text)]
    [StringLength(maximumLength: 350 ,MinimumLength = 1)]
    public IsoMax350Text? AdditionalInformation { get; init; } 
    
    
    #nullable disable
    
}
