// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using BeneficialStrategies.Iso20022.Choices.RecordMessage2Choice;

namespace BeneficialStrategies.Iso20022.Choices
{
    /// <summary>Choice between message record types for card payment messages.</summary>
    [IsoId("_kKcwsW7-EfC68Y4jZPNEug")]
    [DisplayName("Record Message 2 Choice")]
    [KnownType(typeof(RecordMessage2Choice.AddendumInitiation))]
    [KnownType(typeof(RecordMessage2Choice.AddendumResponse))]
    [KnownType(typeof(RecordMessage2Choice.Amendment))]
    [KnownType(typeof(RecordMessage2Choice.AuthorisationInitiation))]
    [KnownType(typeof(RecordMessage2Choice.AuthorisationResponse))]
    [KnownType(typeof(RecordMessage2Choice.CardManagementInitiation))]
    [KnownType(typeof(RecordMessage2Choice.CardManagementResponse))]
    [KnownType(typeof(RecordMessage2Choice.ChargeBackInitiation))]
    [KnownType(typeof(RecordMessage2Choice.ChargeBackResponse))]
    [KnownType(typeof(RecordMessage2Choice.Error))]
    [KnownType(typeof(RecordMessage2Choice.FeeCollectionInitiation))]
    [KnownType(typeof(RecordMessage2Choice.FeeCollectionResponse))]
    [KnownType(typeof(RecordMessage2Choice.FileActionInitiation))]
    [KnownType(typeof(RecordMessage2Choice.FileActionResponse))]
    [KnownType(typeof(RecordMessage2Choice.FinancialInitiation))]
    [KnownType(typeof(RecordMessage2Choice.FinancialResponse))]
    [KnownType(typeof(RecordMessage2Choice.FraudDispositionInitiation))]
    [KnownType(typeof(RecordMessage2Choice.FraudDispositionResponse))]
    [KnownType(typeof(RecordMessage2Choice.FraudReportingInitiation))]
    [KnownType(typeof(RecordMessage2Choice.FraudReportingResponse))]
    [KnownType(typeof(RecordMessage2Choice.InquiryVerificationInitiation))]
    [KnownType(typeof(RecordMessage2Choice.InquiryVerificationResponse))]
    [KnownType(typeof(RecordMessage2Choice.KeyExchangeInitiation))]
    [KnownType(typeof(RecordMessage2Choice.KeyExchangeResponse))]
    [KnownType(typeof(RecordMessage2Choice.NetworkManagementInitiation))]
    [KnownType(typeof(RecordMessage2Choice.NetworkManagementResponse))]
    [KnownType(typeof(RecordMessage2Choice.ReconciliationInitiation))]
    [KnownType(typeof(RecordMessage2Choice.ReconciliationResponse))]
    [KnownType(typeof(RecordMessage2Choice.RetrievalInitiation))]
    [KnownType(typeof(RecordMessage2Choice.RetrievalResponse))]
    [KnownType(typeof(RecordMessage2Choice.RetrievalFulfilmentInitiation))]
    [KnownType(typeof(RecordMessage2Choice.RetrievalFulfilmentResponse))]
    [KnownType(typeof(RecordMessage2Choice.ReversalInitiation))]
    [KnownType(typeof(RecordMessage2Choice.ReversalResponse))]
    [KnownType(typeof(RecordMessage2Choice.SettlementReportingInitiation))]
    [KnownType(typeof(RecordMessage2Choice.SettlementReportingResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.AddendumInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.AddendumResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.Amendment))]
    [JsonDerivedType(typeof(RecordMessage2Choice.AuthorisationInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.AuthorisationResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.CardManagementInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.CardManagementResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.ChargeBackInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.ChargeBackResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.Error))]
    [JsonDerivedType(typeof(RecordMessage2Choice.FeeCollectionInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.FeeCollectionResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.FileActionInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.FileActionResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.FinancialInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.FinancialResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.FraudDispositionInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.FraudDispositionResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.FraudReportingInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.FraudReportingResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.InquiryVerificationInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.InquiryVerificationResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.KeyExchangeInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.KeyExchangeResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.NetworkManagementInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.NetworkManagementResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.ReconciliationInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.ReconciliationResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.RetrievalInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.RetrievalResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.RetrievalFulfilmentInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.RetrievalFulfilmentResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.ReversalInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.ReversalResponse))]
    [JsonDerivedType(typeof(RecordMessage2Choice.SettlementReportingInitiation))]
    [JsonDerivedType(typeof(RecordMessage2Choice.SettlementReportingResponse))]
    public abstract record RecordMessage2Choice_
    {
    }
}
