// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using BeneficialStrategies.Iso20022.Components;
using BeneficialStrategies.Iso20022.ExternalSchema;
using System.Xml;
using System.Xml.Linq;

using System.ComponentModel.DataAnnotations;
namespace BeneficialStrategies.Iso20022.Choices.UnderlyingTransaction3Choice
{
    /// <summary>
    /// Set of elements used to reference the details of the original payment initiation.
    /// </summary>
    [IsoId("_X0Xj4WXpEeap-P22vGV91g")]
    [DisplayName("Initiation")]
    public partial record Initiation : UnderlyingTransaction3Choice_
    {
        #nullable enable
        
        /// <summary>
        /// Set of elements used to provide information on the original message.
        /// </summary>
        [IsoId("_X-qvZWXpEeap-P22vGV91g")]
        [DisplayName("Original Group Information")]
        [IsoXmlTag("OrgnlGrpInf")]
        public UnderlyingGroupInformation1? OriginalGroupInformation { get; init; } 
        
        /// <summary>
        /// Unique identification, as assigned by the original sending party, to unambiguously identify the original payment information group.
        /// </summary>
        [IsoId("_X-qvZ2XpEeap-P22vGV91g")]
        [DisplayName("Original Payment Information Identification")]
        [IsoXmlTag("OrgnlPmtInfId")]
        [IsoSimpleType(IsoSimpleType.Max35Text)]
        [StringLength(maximumLength: 35 ,MinimumLength = 1)]
        public IsoMax35Text? OriginalPaymentInformationIdentification { get; init; } 
        
        /// <summary>
        /// Unique identification, as assigned by the original instructing party for the original instructed party, to unambiguously identify the original instruction.
        /// </summary>
        [IsoId("_X-qvaWXpEeap-P22vGV91g")]
        [DisplayName("Original Instruction Identification")]
        [IsoXmlTag("OrgnlInstrId")]
        [IsoSimpleType(IsoSimpleType.Max35Text)]
        [StringLength(maximumLength: 35 ,MinimumLength = 1)]
        public IsoMax35Text? OriginalInstructionIdentification { get; init; } 
        
        /// <summary>
        /// Unique identification, as assigned by the original initiating party, to unambiguously identify the original transaction.
        /// </summary>
        [IsoId("_X-qva2XpEeap-P22vGV91g")]
        [DisplayName("Original End To End Identification")]
        [IsoXmlTag("OrgnlEndToEndId")]
        [IsoSimpleType(IsoSimpleType.Max35Text)]
        [StringLength(maximumLength: 35 ,MinimumLength = 1)]
        public IsoMax35Text? OriginalEndToEndIdentification { get; init; } 
        
        /// <summary>
        /// Amount of money, as provided in the original transaction, to be moved between the debtor and the creditor, before deduction of charges, expressed in the currency, as ordered by the original initiating party.
        /// </summary>
        [IsoId("_X-qvbWXpEeap-P22vGV91g")]
        [DisplayName("Original Instructed Amount")]
        [IsoXmlTag("OrgnlInstdAmt")]
        public required ActiveOrHistoricCurrencyAndAmount OriginalInstructedAmount { get; init; } 
        
        /// <summary>
        /// Date at which the initiating party requests the clearing agent to process the payment. |Usage: This is the date on which the debtor&apos;s account is to be debited. If payment by cheque, the date when the cheque must be generated by the bank.
        /// </summary>
        [IsoId("_X-qvb2XpEeap-P22vGV91g")]
        [DisplayName("Requested Execution Date")]
        [IsoXmlTag("ReqdExctnDt")]
        public DateAndDateTimeChoice_? RequestedExecutionDate { get; init; } 
        
        /// <summary>
        /// Date at which the creditor requests the amount of money to be collected from the debtor.
        /// </summary>
        [IsoId("_X-qvcWXpEeap-P22vGV91g")]
        [DisplayName("Requested Collection Date")]
        [IsoXmlTag("ReqdColltnDt")]
        [IsoSimpleType(IsoSimpleType.ISODate)]
        public IsoISODate? RequestedCollectionDate { get; init; } 
        
        
        #nullable disable
        
    }
}
