//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetEnumGenerator for AssessmentOfValueRequiredUnderCOLLUKType1Code.  ISO2002 ID# _-5gjcCuUEe6GGqp7D_oKtA.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using System.Reflection;
using System.Runtime.Serialization;

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Specifies if assessment of value is required under UK Collective Investment Schemes. When used in reference to MiFID, this is in the scope of the European MiFID Template (EMT) reference 09040.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_-5gjcCuUEe6GGqp7D_oKtA")]
[Description(@"Specifies if assessment of value is required under UK Collective Investment Schemes. When used in reference to MiFID, this is in the scope of the European MiFID Template (EMT) reference 09040.")]
[DerivedFrom(typeof(AssessmentOfValueRequiredUnderCOLLUKTypeCode))]
public enum AssessmentOfValueRequiredUnderCOLLUKType1Code
{
    /// <summary>
    /// Assessement of value is not required.
    /// Encoded/decoded by serializers as &quot;NSCO&quot;.
    /// </summary>
    [EnumMember(Value = "NSCO")]
    [IsoId("")]
    [Description(@"Assessement of value is not required.")]
    No = AssessmentOfValueRequiredUnderCOLLUKTypeCode.No, // same ordinal as derivation source for type conversions

    /// <summary>
    /// Assessement of value is required.
    /// Encoded/decoded by serializers as &quot;YSCO&quot;.
    /// </summary>
    [EnumMember(Value = "YSCO")]
    [IsoId("")]
    [Description(@"Assessement of value is required.")]
    Yes = AssessmentOfValueRequiredUnderCOLLUKTypeCode.Yes, // same ordinal as derivation source for type conversions

}
