// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using System.Reflection;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Type of authentication method.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_C71jURODEfC1ZfCQz0xB3g")]
[Description(@"Type of authentication method.")]
[DerivedFrom(typeof(AuthenticationMethodCode))]
[JsonConverter(typeof(Iso20022EnumJsonConverter<AuthenticationMethod13Code>))]
public enum AuthenticationMethod13Code
{
    /// <summary>
    /// Serial number of the acceptor's certificate.
    /// Encoded/decoded by serializers as &quot;ACSN&quot;.
    /// </summary>
    [EnumMember(Value = "ACSN")]
    [IsoId("_DDRBexODEfC1ZfCQz0xB3g")]
    [Description(@"Serial number of the acceptor's certificate.")]
    AcceptorCertificateSerialNumber = AuthenticationMethodCode.AcceptorCertificateSerialNumber,

    /// <summary>
    /// Cardholder billing address verification.
    /// Encoded/decoded by serializers as &quot;ADDB&quot;.
    /// </summary>
    [EnumMember(Value = "ADDB")]
    [IsoId("_DDRBaxODEfC1ZfCQz0xB3g")]
    [Description(@"Cardholder billing address verification.")]
    BillingAddressVerification = AuthenticationMethodCode.BillingAddressVerification,

    /// <summary>
    /// Cardholder shipping address verification.
    /// Encoded/decoded by serializers as &quot;ADDS&quot;.
    /// </summary>
    [EnumMember(Value = "ADDS")]
    [IsoId("_DDRBbRODEfC1ZfCQz0xB3g")]
    [Description(@"Cardholder shipping address verification.")]
    ShippingAddressVerification = AuthenticationMethodCode.ShippingAddressVerification,

    /// <summary>
    /// Digits of the address.
    /// Encoded/decoded by serializers as &quot;ADVF&quot;.
    /// </summary>
    [EnumMember(Value = "ADVF")]
    [IsoId("_DDRBAxODEfC1ZfCQz0xB3g")]
    [Description(@"Digits of the address.")]
    AddressDigits = AuthenticationMethodCode.AddressDigits,

    /// <summary>
    /// Account-based digital signature authentication.
    /// Encoded/decoded by serializers as &quot;APKI&quot;.
    /// </summary>
    [EnumMember(Value = "APKI")]
    [IsoId("_DDRBARODEfC1ZfCQz0xB3g")]
    [Description(@"Account-based digital signature authentication.")]
    AccountDigitalSignature = AuthenticationMethodCode.AccountDigitalSignature,

    /// <summary>
    /// Number assigned by a government agency to identify foreign nationals.
    /// Encoded/decoded by serializers as &quot;ARNB&quot;.
    /// </summary>
    [EnumMember(Value = "ARNB")]
    [IsoId("_DDRBBRODEfC1ZfCQz0xB3g")]
    [Description(@"Number assigned by a government agency to identify foreign nationals.")]
    AlienRegistrationNumber = AuthenticationMethodCode.AlienRegistrationNumber,

    /// <summary>
    /// Response Card Cryptogram (ARPC) verification.
    /// Encoded/decoded by serializers as &quot;ARPC&quot;.
    /// </summary>
    [EnumMember(Value = "ARPC")]
    [IsoId("_DDRBBxODEfC1ZfCQz0xB3g")]
    [Description(@"Response Card Cryptogram (ARPC) verification.")]
    ARPCVerification = AuthenticationMethodCode.ARPCVerification,

    /// <summary>
    /// Verification of a cryptogram generated by a chip card, for instance an ARQC (Authorisation Request Cryptogram).
    /// Encoded/decoded by serializers as &quot;ARQC&quot;.
    /// </summary>
    [EnumMember(Value = "ARQC")]
    [IsoId("_DDRBCRODEfC1ZfCQz0xB3g")]
    [Description(@"Verification of a cryptogram generated by a chip card, for instance an ARQC (Authorisation Request Cryptogram).")]
    ARQCVerification = AuthenticationMethodCode.ARQCVerification,

    /// <summary>
    /// Application Transaction Counter.
    /// Encoded/decoded by serializers as &quot;ATCC&quot;.
    /// </summary>
    [EnumMember(Value = "ATCC")]
    [IsoId("_DDRBCxODEfC1ZfCQz0xB3g")]
    [Description(@"Application Transaction Counter.")]
    ATC = AuthenticationMethodCode.ATC,

    /// <summary>
    /// Biometric authentication of the cardholder.
    /// Encoded/decoded by serializers as &quot;BIOM&quot;.
    /// </summary>
    [EnumMember(Value = "BIOM")]
    [IsoId("_DDRBcxODEfC1ZfCQz0xB3g")]
    [Description(@"Biometric authentication of the cardholder.")]
    Biometry = AuthenticationMethodCode.Biometry,

    /// <summary>
    /// Date of birth of a person.
    /// Encoded/decoded by serializers as &quot;BTHD&quot;.
    /// </summary>
    [EnumMember(Value = "BTHD")]
    [IsoId("_DDRBDRODEfC1ZfCQz0xB3g")]
    [Description(@"Date of birth of a person.")]
    BirthDate = AuthenticationMethodCode.BirthDate,

    /// <summary>
    /// Cardholder data provided for verification, for instance social security number, driver license number, passport number.
    /// Encoded/decoded by serializers as &quot;CDHI&quot;.
    /// </summary>
    [EnumMember(Value = "CDHI")]
    [IsoId("_DDRBXxODEfC1ZfCQz0xB3g")]
    [Description(@"Cardholder data provided for verification, for instance social security number, driver license number, passport number.")]
    CardholderIdentificationData = AuthenticationMethodCode.CardholderIdentificationData,

    /// <summary>
    /// Name of cardholder.
    /// Encoded/decoded by serializers as &quot;CHDN&quot;.
    /// </summary>
    [EnumMember(Value = "CHDN")]
    [IsoId("_DDRBERODEfC1ZfCQz0xB3g")]
    [Description(@"Name of cardholder.")]
    CardholderName = AuthenticationMethodCode.CardholderName,

    /// <summary>
    /// Verification whether the address corresponds to the cardholder's one.
    /// Encoded/decoded by serializers as &quot;CHSA&quot;.
    /// </summary>
    [EnumMember(Value = "CHSA")]
    [IsoId("_DDRBDxODEfC1ZfCQz0xB3g")]
    [Description(@"Verification whether the address corresponds to the cardholder's one.")]
    CardholderAddress = AuthenticationMethodCode.CardholderAddress,

    /// <summary>
    /// Serial number of the cardholder's certificate.
    /// Encoded/decoded by serializers as &quot;CHSN&quot;.
    /// </summary>
    [EnumMember(Value = "CHSN")]
    [IsoId("_DDRBfRODEfC1ZfCQz0xB3g")]
    [Description(@"Serial number of the cardholder's certificate.")]
    CardholderCertificateSerialNumber = AuthenticationMethodCode.CardholderCertificateSerialNumber,

    /// <summary>
    /// Electronic signature capture (handwritten signature).
    /// Encoded/decoded by serializers as &quot;CPSG&quot;.
    /// </summary>
    [EnumMember(Value = "CPSG")]
    [IsoId("_DDRBVxODEfC1ZfCQz0xB3g")]
    [Description(@"Electronic signature capture (handwritten signature).")]
    SignatureCapture = AuthenticationMethodCode.SignatureCapture,

    /// <summary>
    /// Verification of a cryptogram generated by a chip card or another device, for instance ARQC (Authorisation Request Cryptogram).
    /// Encoded/decoded by serializers as &quot;CRYP&quot;.
    /// </summary>
    [EnumMember(Value = "CRYP")]
    [IsoId("_DDRBcRODEfC1ZfCQz0xB3g")]
    [Description(@"Verification of a cryptogram generated by a chip card or another device, for instance ARQC (Authorisation Request Cryptogram).")]
    CryptogramVerification = AuthenticationMethodCode.CryptogramVerification,

    /// <summary>
    /// Verification of Card Security Code.
    /// Encoded/decoded by serializers as &quot;CSCV&quot;.
    /// </summary>
    [EnumMember(Value = "CSCV")]
    [IsoId("_DDRBbxODEfC1ZfCQz0xB3g")]
    [Description(@"Verification of Card Security Code.")]
    CSCVerification = AuthenticationMethodCode.CSCVerification,

    /// <summary>
    /// Authentication performed during a secure electronic commerce transaction.
    /// Encoded/decoded by serializers as &quot;CSEC&quot;.
    /// </summary>
    [EnumMember(Value = "CSEC")]
    [IsoId("_DDRBURODEfC1ZfCQz0xB3g")]
    [Description(@"Authentication performed during a secure electronic commerce transaction.")]
    SecureElectronicCommerce = AuthenticationMethodCode.SecureElectronicCommerce,

    /// <summary>
    /// Customer number used as a mechanism of authentication.
    /// Encoded/decoded by serializers as &quot;CUID&quot;.
    /// </summary>
    [EnumMember(Value = "CUID")]
    [IsoId("_DDRBExODEfC1ZfCQz0xB3g")]
    [Description(@"Customer number used as a mechanism of authentication.")]
    CustomerIdentification = AuthenticationMethodCode.CustomerIdentification,

    /// <summary>
    /// Number assigned by a driving license authority to a person driving a car.
    /// Encoded/decoded by serializers as &quot;DRLN&quot;.
    /// </summary>
    [EnumMember(Value = "DRLN")]
    [IsoId("_DDRBFxODEfC1ZfCQz0xB3g")]
    [Description(@"Number assigned by a driving license authority to a person driving a car.")]
    DriverLicenseNumber = AuthenticationMethodCode.DriverLicenseNumber,

    /// <summary>
    /// Identification of a driver in a fleet of vehicles.
    /// Encoded/decoded by serializers as &quot;DRVI&quot;.
    /// </summary>
    [EnumMember(Value = "DRVI")]
    [IsoId("_DDRBFRODEfC1ZfCQz0xB3g")]
    [Description(@"Identification of a driver in a fleet of vehicles.")]
    DriverIdentification = AuthenticationMethodCode.DriverIdentification,

    /// <summary>
    /// Electronic mail address.
    /// Encoded/decoded by serializers as &quot;EMAL&quot;.
    /// </summary>
    [EnumMember(Value = "EMAL")]
    [IsoId("_DDRBGRODEfC1ZfCQz0xB3g")]
    [Description(@"Electronic mail address.")]
    Email = AuthenticationMethodCode.Email,

    /// <summary>
    /// Number assigned to an employee by an employer.
    /// Encoded/decoded by serializers as &quot;EMIN&quot;.
    /// </summary>
    [EnumMember(Value = "EMIN")]
    [IsoId("_DDRBGxODEfC1ZfCQz0xB3g")]
    [Description(@"Number assigned to an employee by an employer.")]
    EmployeeIdentificationNumber = AuthenticationMethodCode.EmployeeIdentificationNumber,

    /// <summary>
    /// Number assigned to an employer by a registration authority.
    /// Encoded/decoded by serializers as &quot;EMRN&quot;.
    /// </summary>
    [EnumMember(Value = "EMRN")]
    [IsoId("_DDRBHRODEfC1ZfCQz0xB3g")]
    [Description(@"Number assigned to an employer by a registration authority.")]
    EmployerIdentificationNumber = AuthenticationMethodCode.EmployerIdentificationNumber,

    /// <summary>
    /// Biographics authentication in an offline mode.
    /// Encoded/decoded by serializers as &quot;FBIG&quot;.
    /// </summary>
    [EnumMember(Value = "FBIG")]
    [IsoId("_DDRBJRODEfC1ZfCQz0xB3g")]
    [Description(@"Biographics authentication in an offline mode.")]
    OffLineBiographics = AuthenticationMethodCode.OffLineBiographics,

    /// <summary>
    /// Biometrics authentication in an offline mode.
    /// Encoded/decoded by serializers as &quot;FBIO&quot;.
    /// </summary>
    [EnumMember(Value = "FBIO")]
    [IsoId("_DDRBJxODEfC1ZfCQz0xB3g")]
    [Description(@"Biometrics authentication in an offline mode.")]
    OffLineBiometrics = AuthenticationMethodCode.OffLineBiometrics,

    /// <summary>
    /// PIN generated offline and transmitted in clear.
    /// Encoded/decoded by serializers as &quot;FCPN&quot;.
    /// </summary>
    [EnumMember(Value = "FCPN")]
    [IsoId("_DDRBLxODEfC1ZfCQz0xB3g")]
    [Description(@"PIN generated offline and transmitted in clear.")]
    OffLinePINInClear = AuthenticationMethodCode.OffLinePINInClear,

    /// <summary>
    /// Off-line PIN authentication (Personal Identification Number).
    /// Encoded/decoded by serializers as &quot;FPIN&quot;.
    /// </summary>
    [EnumMember(Value = "FPIN")]
    [IsoId("_DDRBdxODEfC1ZfCQz0xB3g")]
    [Description(@"Off-line PIN authentication (Personal Identification Number).")]
    OfflinePIN = AuthenticationMethodCode.OfflinePIN,

    /// <summary>
    /// Number assigned by a national authority to an identity card.
    /// Encoded/decoded by serializers as &quot;IDCN&quot;.
    /// </summary>
    [EnumMember(Value = "IDCN")]
    [IsoId("_DDRBHxODEfC1ZfCQz0xB3g")]
    [Description(@"Number assigned by a national authority to an identity card.")]
    IdentityCardNumber = AuthenticationMethodCode.IdentityCardNumber,

    /// <summary>
    /// Manual verification, for example passport or drivers license.
    /// Encoded/decoded by serializers as &quot;MANU&quot;.
    /// </summary>
    [EnumMember(Value = "MANU")]
    [IsoId("_DDRBIRODEfC1ZfCQz0xB3g")]
    [Description(@"Manual verification, for example passport or drivers license.")]
    ManualVerification = AuthenticationMethodCode.ManualVerification,

    /// <summary>
    /// Customer mobile device.
    /// Encoded/decoded by serializers as &quot;MOBL&quot;.
    /// </summary>
    [EnumMember(Value = "MOBL")]
    [IsoId("_DDRBdRODEfC1ZfCQz0xB3g")]
    [Description(@"Customer mobile device.")]
    Mobile = AuthenticationMethodCode.Mobile,

    /// <summary>
    /// Biographics authentication in an online mode.
    /// Encoded/decoded by serializers as &quot;NBIG&quot;.
    /// </summary>
    [EnumMember(Value = "NBIG")]
    [IsoId("_DDRBMxODEfC1ZfCQz0xB3g")]
    [Description(@"Biographics authentication in an online mode.")]
    OnLineBiographics = AuthenticationMethodCode.OnLineBiographics,

    /// <summary>
    /// On-line PIN authentication (Personal Identification Number).
    /// Encoded/decoded by serializers as &quot;NPIN&quot;.
    /// </summary>
    [EnumMember(Value = "NPIN")]
    [IsoId("_DDRBNRODEfC1ZfCQz0xB3g")]
    [Description(@"On-line PIN authentication (Personal Identification Number).")]
    OnLinePIN = AuthenticationMethodCode.OnLinePIN,

    /// <summary>
    /// Nationally assigned identifier.
    /// Encoded/decoded by serializers as &quot;NTID&quot;.
    /// </summary>
    [EnumMember(Value = "NTID")]
    [IsoId("_DDRBeRODEfC1ZfCQz0xB3g")]
    [Description(@"Nationally assigned identifier.")]
    NationalIdentifier = AuthenticationMethodCode.NationalIdentifier,

    /// <summary>
    /// Non visible Card Security Code.
    /// Encoded/decoded by serializers as &quot;NVSC&quot;.
    /// </summary>
    [EnumMember(Value = "NVSC")]
    [IsoId("_DDRBIxODEfC1ZfCQz0xB3g")]
    [Description(@"Non visible Card Security Code.")]
    NonVisibleCSC = AuthenticationMethodCode.NonVisibleCSC,

    /// <summary>
    /// Other cardholder data provided for identification.
    /// Encoded/decoded by serializers as &quot;OCHI&quot;.
    /// </summary>
    [EnumMember(Value = "OCHI")]
    [IsoId("_DDRBNxODEfC1ZfCQz0xB3g")]
    [Description(@"Other cardholder data provided for identification.")]
    OtherCardholderIdentification = AuthenticationMethodCode.OtherCardholderIdentification,

    /// <summary>
    /// PIN generated offline and transmitted encrypted.
    /// Encoded/decoded by serializers as &quot;OFPE&quot;.
    /// </summary>
    [EnumMember(Value = "OFPE")]
    [IsoId("_DDRBLRODEfC1ZfCQz0xB3g")]
    [Description(@"PIN generated offline and transmitted encrypted.")]
    OffLinePINEncrypted = AuthenticationMethodCode.OffLinePINEncrypted,

    /// <summary>
    /// Authentication of data in an offline mode.
    /// Encoded/decoded by serializers as &quot;OLDA&quot;.
    /// </summary>
    [EnumMember(Value = "OLDA")]
    [IsoId("_DDRBKRODEfC1ZfCQz0xB3g")]
    [Description(@"Authentication of data in an offline mode.")]
    OffLineDataAuthentication = AuthenticationMethodCode.OffLineDataAuthentication,

    /// <summary>
    /// Analysis of signature transmitted offline.
    /// Encoded/decoded by serializers as &quot;OLDS&quot;.
    /// </summary>
    [EnumMember(Value = "OLDS")]
    [IsoId("_DDRBKxODEfC1ZfCQz0xB3g")]
    [Description(@"Analysis of signature transmitted offline.")]
    OffLineDigitisedSignatureAnalysis = AuthenticationMethodCode.OffLineDigitisedSignatureAnalysis,

    /// <summary>
    /// Verification of a cryptogram generated by a non-card form factor.
    /// Encoded/decoded by serializers as &quot;OTHC&quot;.
    /// </summary>
    [EnumMember(Value = "OTHC")]
    [IsoId("_KbVawRODEfC1ZfCQz0xB3g")]
    [Description(@"Verification of a cryptogram generated by a non-card form factor.")]
    OtherCryptogram = AuthenticationMethodCode.OtherCryptogram,

    /// <summary>
    /// Other customer authentication.
    /// Encoded/decoded by serializers as &quot;OTHR&quot;.
    /// </summary>
    [EnumMember(Value = "OTHR")]
    [IsoId("_L085ERODEfC1ZfCQz0xB3g")]
    [Description(@"Other customer authentication.")]
    Other = AuthenticationMethodCode.Other,

    /// <summary>
    /// Verification of a one-time password provided by the issuer.
    /// Encoded/decoded by serializers as &quot;OTPW&quot;.
    /// </summary>
    [EnumMember(Value = "OTPW")]
    [IsoId("_DDRBMRODEfC1ZfCQz0xB3g")]
    [Description(@"Verification of a one-time password provided by the issuer.")]
    OneTimePassword = AuthenticationMethodCode.OneTimePassword,

    /// <summary>
    /// Number assigned by a passport authority to a passport.
    /// Encoded/decoded by serializers as &quot;PASN&quot;.
    /// </summary>
    [EnumMember(Value = "PASN")]
    [IsoId("_DDRBQRODEfC1ZfCQz0xB3g")]
    [Description(@"Number assigned by a passport authority to a passport.")]
    PassportNumber = AuthenticationMethodCode.PassportNumber,

    /// <summary>
    /// Verification based on digits of the postal code.
    /// Encoded/decoded by serializers as &quot;PCDV&quot;.
    /// </summary>
    [EnumMember(Value = "PCDV")]
    [IsoId("_DDRBSxODEfC1ZfCQz0xB3g")]
    [Description(@"Verification based on digits of the postal code.")]
    PostalCode = AuthenticationMethodCode.PostalCode,

    /// <summary>
    /// Customer home phone number.
    /// Encoded/decoded by serializers as &quot;PHOM&quot;.
    /// </summary>
    [EnumMember(Value = "PHOM")]
    [IsoId("_DDRBZRODEfC1ZfCQz0xB3g")]
    [Description(@"Customer home phone number.")]
    PhoneHome = AuthenticationMethodCode.PhoneHome,

    /// <summary>
    /// PKI (Public Key Infrastructure) based digital signature.
    /// Encoded/decoded by serializers as &quot;PKIS&quot;.
    /// </summary>
    [EnumMember(Value = "PKIS")]
    [IsoId("_DDRBRxODEfC1ZfCQz0xB3g")]
    [Description(@"PKI (Public Key Infrastructure) based digital signature.")]
    PKISignature = AuthenticationMethodCode.PKISignature,

    /// <summary>
    /// Place of birth of a person.
    /// Encoded/decoded by serializers as &quot;PLOB&quot;.
    /// </summary>
    [EnumMember(Value = "PLOB")]
    [IsoId("_DDRBSRODEfC1ZfCQz0xB3g")]
    [Description(@"Place of birth of a person.")]
    PlaceOfBirth = AuthenticationMethodCode.PlaceOfBirth,

    /// <summary>
    /// Handwritten paper signature.
    /// Encoded/decoded by serializers as &quot;PPSG&quot;.
    /// </summary>
    [EnumMember(Value = "PPSG")]
    [IsoId("_DDRBPRODEfC1ZfCQz0xB3g")]
    [Description(@"Handwritten paper signature.")]
    PaperSignature = AuthenticationMethodCode.PaperSignature,

    /// <summary>
    /// Authentication based on statistical cardholder behaviour.
    /// Encoded/decoded by serializers as &quot;PSVE&quot;.
    /// </summary>
    [EnumMember(Value = "PSVE")]
    [IsoId("_DDRBPxODEfC1ZfCQz0xB3g")]
    [Description(@"Authentication based on statistical cardholder behaviour.")]
    PassiveAuthentication = AuthenticationMethodCode.PassiveAuthentication,

    /// <summary>
    /// Authentication by a password.
    /// Encoded/decoded by serializers as &quot;PSWD&quot;.
    /// </summary>
    [EnumMember(Value = "PSWD")]
    [IsoId("_DDRBQxODEfC1ZfCQz0xB3g")]
    [Description(@"Authentication by a password.")]
    Password = AuthenticationMethodCode.Password,

    /// <summary>
    /// Customer work phone number.
    /// Encoded/decoded by serializers as &quot;PWOR&quot;.
    /// </summary>
    [EnumMember(Value = "PWOR")]
    [IsoId("_DDRBZxODEfC1ZfCQz0xB3g")]
    [Description(@"Customer work phone number.")]
    PhoneWork = AuthenticationMethodCode.PhoneWork,

    /// <summary>
    /// Qualified Certificate.
    /// Encoded/decoded by serializers as &quot;QWAC&quot;.
    /// </summary>
    [EnumMember(Value = "QWAC")]
    [IsoId("_DDRBYxODEfC1ZfCQz0xB3g")]
    [Description(@"Qualified Certificate.")]
    QualifiedCertificate = AuthenticationMethodCode.QualifiedCertificate,

    /// <summary>
    /// Channel-encrypted transaction.
    /// Encoded/decoded by serializers as &quot;SCNL&quot;.
    /// </summary>
    [EnumMember(Value = "SCNL")]
    [IsoId("_DDRBTxODEfC1ZfCQz0xB3g")]
    [Description(@"Channel-encrypted transaction.")]
    SecuredChannel = AuthenticationMethodCode.SecuredChannel,

    /// <summary>
    /// Electronic commerce transaction secured with the X.509 certificate of a customer.
    /// Encoded/decoded by serializers as &quot;SCRT&quot;.
    /// </summary>
    [EnumMember(Value = "SCRT")]
    [IsoId("_DDRBTRODEfC1ZfCQz0xB3g")]
    [Description(@"Electronic commerce transaction secured with the X.509 certificate of a customer.")]
    SecureCertificate = AuthenticationMethodCode.SecureCertificate,

    /// <summary>
    /// Shipping address from verification.
    /// Encoded/decoded by serializers as &quot;SHAF&quot;.
    /// </summary>
    [EnumMember(Value = "SHAF")]
    [IsoId("_DDRBUxODEfC1ZfCQz0xB3g")]
    [Description(@"Shipping address from verification.")]
    ShippingAddressFrom = AuthenticationMethodCode.ShippingAddressFrom,

    /// <summary>
    /// Shipping address to verification.
    /// Encoded/decoded by serializers as &quot;SHAT&quot;.
    /// </summary>
    [EnumMember(Value = "SHAT")]
    [IsoId("_DDRBVRODEfC1ZfCQz0xB3g")]
    [Description(@"Shipping address to verification.")]
    ShippingAddressTo = AuthenticationMethodCode.ShippingAddressTo,

    /// <summary>
    /// Number assigned by a social security agency.
    /// Encoded/decoded by serializers as &quot;SSNB&quot;.
    /// </summary>
    [EnumMember(Value = "SSNB")]
    [IsoId("_DDRBWRODEfC1ZfCQz0xB3g")]
    [Description(@"Number assigned by a social security agency.")]
    SocialSecurityNumber = AuthenticationMethodCode.SocialSecurityNumber,

    /// <summary>
    /// Authentication performed during a secure electronic commerce transaction.
    /// Encoded/decoded by serializers as &quot;THDS&quot;.
    /// </summary>
    [EnumMember(Value = "THDS")]
    [IsoId("_DDRBaRODEfC1ZfCQz0xB3g")]
    [Description(@"Authentication performed during a secure electronic commerce transaction.")]
    ThreeDS = AuthenticationMethodCode.ThreeDS,

    /// <summary>
    /// A token is used to verify an already performed authentication.
    /// Encoded/decoded by serializers as &quot;TOKA&quot;.
    /// </summary>
    [EnumMember(Value = "TOKA")]
    [IsoId("_DDRBXRODEfC1ZfCQz0xB3g")]
    [Description(@"A token is used to verify an already performed authentication.")]
    AuthenticationToken = AuthenticationMethodCode.AuthenticationToken,

    /// <summary>
    /// Cryptogram generated by the token requestor or a customer device to validate the authorised use of a token.
    /// Encoded/decoded by serializers as &quot;TOKN&quot;.
    /// </summary>
    [EnumMember(Value = "TOKN")]
    [IsoId("_DDRBYRODEfC1ZfCQz0xB3g")]
    [Description(@"Cryptogram generated by the token requestor or a customer device to validate the authorised use of a token.")]
    TokenAuthentication = AuthenticationMethodCode.TokenAuthentication,

    /// <summary>
    /// Verification or authentication related to the use of a payment token.
    /// Encoded/decoded by serializers as &quot;TOKP&quot;.
    /// </summary>
    [EnumMember(Value = "TOKP")]
    [IsoId("_DDRBRRODEfC1ZfCQz0xB3g")]
    [Description(@"Verification or authentication related to the use of a payment token.")]
    PaymentToken = AuthenticationMethodCode.PaymentToken,

    /// <summary>
    /// Number assigned by a tax authority to an entity.
    /// Encoded/decoded by serializers as &quot;TXIN&quot;.
    /// </summary>
    [EnumMember(Value = "TXIN")]
    [IsoId("_DDRBWxODEfC1ZfCQz0xB3g")]
    [Description(@"Number assigned by a tax authority to an entity.")]
    TaxIdentificationNumber = AuthenticationMethodCode.TaxIdentificationNumber,
}
