//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetEnumGenerator for CardPaymentServiceType15Code.  ISO2002 ID# _MeQ9YZxGEe-Jl6tBAvMHqA.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using System.Reflection;
using System.Runtime.Serialization;

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Additional attributes of the service provided by the card payment transaction.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_MeQ9YZxGEe-Jl6tBAvMHqA")]
[Description(@"Additional attributes of the service provided by the card payment transaction.")]
[DerivedFrom(typeof(CardPaymentServiceTypeCode))]
public enum CardPaymentServiceType15Code
{
    /// <summary>
    /// Additional payment after reservation.
    /// Encoded/decoded by serializers as &quot;ARES&quot;.
    /// </summary>
    [EnumMember(Value = "ARES")]
    [IsoId("")]
    [Description(@"Additional payment after reservation.")]
    AdditionalPayment = CardPaymentServiceTypeCode.AdditionalPayment, // same ordinal as derivation source for type conversions

    /// <summary>
    /// DeferredClearing identifies transactions, like ones related to health care system, that allows a delay in clearing which ensure the payer to be refunded by a system, for example an insurance, before its bank account is debited.
    /// Encoded/decoded by serializers as &quot;DFCL&quot;.
    /// </summary>
    [EnumMember(Value = "DFCL")]
    [IsoId("")]
    [Description(@"DeferredClearing identifies transactions, like ones related to health care system, that allows a delay in clearing which ensure the payer to be refunded by a system, for example an insurance, before its bank account is debited.")]
    DeferredClearing = CardPaymentServiceTypeCode.DeferredClearing, // same ordinal as derivation source for type conversions

    /// <summary>
    /// Initial recurring payment.
    /// Encoded/decoded by serializers as &quot;FREC&quot;.
    /// </summary>
    [EnumMember(Value = "FREC")]
    [IsoId("")]
    [Description(@"Initial recurring payment.")]
    FirstRecurring = CardPaymentServiceTypeCode.FirstRecurring, // same ordinal as derivation source for type conversions

    /// <summary>
    /// Acceptor claims for guarantee of payment.
    /// Encoded/decoded by serializers as &quot;GOPT&quot;.
    /// </summary>
    [EnumMember(Value = "GOPT")]
    [IsoId("")]
    [Description(@"Acceptor claims for guarantee of payment.")]
    GuaranteeOfPayment = CardPaymentServiceTypeCode.GuaranteeOfPayment, // same ordinal as derivation source for type conversions

    /// <summary>
    /// Initial reservation.
    /// Encoded/decoded by serializers as &quot;IRES&quot;.
    /// </summary>
    [EnumMember(Value = "IRES")]
    [IsoId("")]
    [Description(@"Initial reservation.")]
    InitialReservation = CardPaymentServiceTypeCode.InitialReservation, // same ordinal as derivation source for type conversions

    /// <summary>
    /// Payment after reservation.
    /// Encoded/decoded by serializers as &quot;PRES&quot;.
    /// </summary>
    [EnumMember(Value = "PRES")]
    [IsoId("")]
    [Description(@"Payment after reservation.")]
    PaymentReservation = CardPaymentServiceTypeCode.PaymentReservation, // same ordinal as derivation source for type conversions

    /// <summary>
    /// Repeat recurring payment.
    /// Encoded/decoded by serializers as &quot;RREC&quot;.
    /// </summary>
    [EnumMember(Value = "RREC")]
    [IsoId("")]
    [Description(@"Repeat recurring payment.")]
    FollowingRecurring = CardPaymentServiceTypeCode.FollowingRecurring, // same ordinal as derivation source for type conversions

    /// <summary>
    /// Update reservation.
    /// Encoded/decoded by serializers as &quot;URES&quot;.
    /// </summary>
    [EnumMember(Value = "URES")]
    [IsoId("")]
    [Description(@"Update reservation.")]
    UpdateReservation = CardPaymentServiceTypeCode.UpdateReservation, // same ordinal as derivation source for type conversions

}
