//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetEnumGenerator for EqualisationMethodologyType1Code.  ISO2002 ID# _sBK4QBvtEe6BvtAMnhq3zw.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using System.Reflection;
using System.Runtime.Serialization;

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Methodology used for the allocation of the performance fees.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_sBK4QBvtEe6BvtAMnhq3zw")]
[Description(@"Methodology used for the allocation of the performance fees.")]
[DerivedFrom(typeof(EqualisationMethodologyTypeCode))]
public enum EqualisationMethodologyType1Code
{
    /// <summary>
    /// Mandatory redemption of units processed either at redemption or crystallization, whose proceeds are due to the asset manager as performance fee. Performance fee to be paid by the investor when the value of the investment fund units were below their applicable high-watermark on subscription date, and above the high-watermark on redemption date.
    /// Encoded/decoded by serializers as &quot;COLI&quot;.
    /// </summary>
    [EnumMember(Value = "COLI")]
    [IsoId("")]
    [Description(@"Mandatory redemption of units processed either at redemption or crystallization, whose proceeds are due to the asset manager as performance fee. Performance fee to be paid by the investor when the value of the investment fund units were below their applicable high-watermark on subscription date, and above the high-watermark on redemption date.")]
    ContingentLiquidation = EqualisationMethodologyTypeCode.ContingentLiquidation, // same ordinal as derivation source for type conversions

    /// <summary>
    /// Performance fee to be paid by the investor when the net asset value reaches the high-watermark if the net asset value was under the high-watermark on subscription date.
    /// Encoded/decoded by serializers as &quot;DDEP&quot;.
    /// </summary>
    [EnumMember(Value = "DDEP")]
    [IsoId("")]
    [Description(@"Performance fee to be paid by the investor when the net asset value reaches the high-watermark if the net asset value was under the high-watermark on subscription date.")]
    DepreciationDeposit = EqualisationMethodologyTypeCode.DepreciationDeposit, // same ordinal as derivation source for type conversions

    /// <summary>
    /// Prepayment amount to be paid by the investor at the moment of the subscription.  The amount is based on the positive difference between the gross asset value at subscription and the high-watermark, when the investment fund units are subscribed to above their high-watermark.
    /// Encoded/decoded by serializers as &quot;EQCR&quot;.
    /// </summary>
    [EnumMember(Value = "EQCR")]
    [IsoId("")]
    [Description(@"Prepayment amount to be paid by the investor at the moment of the subscription.  The amount is based on the positive difference between the gross asset value at subscription and the high-watermark, when the investment fund units are subscribed to above their high-watermark.")]
    EqualisationCredit = EqualisationMethodologyTypeCode.EqualisationCredit, // same ordinal as derivation source for type conversions

}
