//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetEnumGenerator for ExternalEmissionAllowanceSubProductTypeCode.  ISO2002 ID# _cXVzaW8wEe6_0L6gLGEkbA.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using System.Reflection;
using System.Runtime.Serialization;

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Specifies the detailed sub products types allowed for emission allowances and associated derivatives.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_cXVzaW8wEe6_0L6gLGEkbA")]
[Description(@"Specifies the detailed sub products types allowed for emission allowances and associated derivatives.")]
[Derivations(typeof(ExternalEmissionAllowanceSubProductType1Code))]
public enum ExternalEmissionAllowanceSubProductTypeCode
{
    /// <summary>
    /// Commodity attribute of type emissions allowance CER (Certified Emission Reduction).
    /// Encoded/decoded by serializers as &quot;CERE&quot;.
    /// </summary>
    [EnumMember(Value = "CERE")]
    [IsoId("")]
    [Description(@"Commodity attribute of type emissions allowance CER (Certified Emission Reduction).")]
    CER,

    /// <summary>
    /// Commodity attribute of type emissions allowance ERU (European Reduction Unit).
    /// Encoded/decoded by serializers as &quot;ERUE&quot;.
    /// </summary>
    [EnumMember(Value = "ERUE")]
    [IsoId("")]
    [Description(@"Commodity attribute of type emissions allowance ERU (European Reduction Unit).")]
    ERU,

    /// <summary>
    /// Commodity attribute of type emissions allowance EUAA (European Union Aviation Allowance).
    /// Encoded/decoded by serializers as &quot;EUAA&quot;.
    /// </summary>
    [EnumMember(Value = "EUAA")]
    [IsoId("")]
    [Description(@"Commodity attribute of type emissions allowance EUAA (European Union Aviation Allowance).")]
    EUAA,

    /// <summary>
    /// Commodity attribute of type emissions allowance EUA (European Union Allowance).
    /// Encoded/decoded by serializers as &quot;EUAE&quot;.
    /// </summary>
    [EnumMember(Value = "EUAE")]
    [IsoId("")]
    [Description(@"Commodity attribute of type emissions allowance EUA (European Union Allowance).")]
    EUA,

    /// <summary>
    /// Commodity attribute of other type.
    /// Encoded/decoded by serializers as &quot;OTHR&quot;.
    /// </summary>
    [EnumMember(Value = "OTHR")]
    [IsoId("")]
    [Description(@"Commodity attribute of other type.")]
    Other,

}
