//
// GENERATED CODE, DO NOT EDIT THIS FILE!
//
// Generated by CodesetEnumGenerator for ExternalPaymentScenario1Code.  ISO2002 ID# _ASuJUGw9Ee-t2JGPeXy0Sw.
// Copyright 2024 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.
//

using System.Reflection;
using System.Runtime.Serialization;

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Specifies the payment scenario, as published in an external payment scenario code set.
/// External code sets can be downloaded from www.iso20022.org.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_ASuJUGw9Ee-t2JGPeXy0Sw")]
[Description(@"Specifies the payment scenario, as published in an external payment scenario code set.")]
[DerivedFrom(typeof(ExternalPaymentScenarioCode))]
public enum ExternalPaymentScenario1Code
{
}
