// Copyright 2026 Jeff Ward, Beneficial Strategies. Usage subject to license of enclosing library.

using System.Reflection;
using System.Runtime.Serialization;

namespace BeneficialStrategies.Iso20022.Codesets;

/// <summary>
/// Code to specify the authentication method used, as published separately in an external authentication method code set.
/// </summary>
[DataContract]
[Serializable]
[IsoId("_ExternalAuthenticationMethodCode")]
[Description(@"Code to specify the authentication method used, as published separately in an external authentication method code set.")]
public enum ExternalAuthenticationMethodCode
{
    /// <summary>
    /// Serial Number of the acceptor’s certificate.
    /// Encoded/decoded by serializers as &quot;ACSN&quot;.
    /// </summary>
    [EnumMember(Value = "ACSN")]
    [IsoId("_ExternalAuthenticationMethodCode_AcceptorCertificateSerialNumber")]
    [Description(@"Serial Number of the acceptor’s certificate.")]
    AcceptorCertificateSerialNumber,

    /// <summary>
    /// Cardholder billing address.
    /// Encoded/decoded by serializers as &quot;ADDB&quot;.
    /// </summary>
    [EnumMember(Value = "ADDB")]
    [IsoId("_ExternalAuthenticationMethodCode_BillingAddress")]
    [Description(@"Cardholder billing address.")]
    BillingAddress,

    /// <summary>
    /// Shipping address.
    /// Encoded/decoded by serializers as &quot;ADDS&quot;.
    /// </summary>
    [EnumMember(Value = "ADDS")]
    [IsoId("_ExternalAuthenticationMethodCode_ShippingAddress")]
    [Description(@"Shipping address.")]
    ShippingAddress,

    /// <summary>
    /// Account-based digital signature authentication.
    /// Encoded/decoded by serializers as &quot;APKI&quot;.
    /// </summary>
    [EnumMember(Value = "APKI")]
    [IsoId("_ExternalAuthenticationMethodCode_AccountDigitalSignature")]
    [Description(@"Account-based digital signature authentication.")]
    AccountDigitalSignature,

    /// <summary>
    /// Number assigned by a government agency to identify foreign nationals.
    /// Encoded/decoded by serializers as &quot;ARNB&quot;.
    /// </summary>
    [EnumMember(Value = "ARNB")]
    [IsoId("_ExternalAuthenticationMethodCode_AlienRegistrationNumber")]
    [Description(@"Number assigned by a government agency to identify foreign nationals.")]
    AlienRegistrationNumber,

    /// <summary>
    /// Response Card Cryptogram (ARPC) verification.
    /// Encoded/decoded by serializers as &quot;ARPC&quot;.
    /// </summary>
    [EnumMember(Value = "ARPC")]
    [IsoId("_ExternalAuthenticationMethodCode_ARPC")]
    [Description(@"Response Card Cryptogram (ARPC) verification.")]
    ARPC,

    /// <summary>
    /// Verification of a cryptogram generated by a chip card, for instance an ARQC (Authorisation Request Cryptogram).
    /// Encoded/decoded by serializers as &quot;ARQC&quot;.
    /// </summary>
    [EnumMember(Value = "ARQC")]
    [IsoId("_ExternalAuthenticationMethodCode_ARQC")]
    [Description(@"Verification of a cryptogram generated by a chip card, for instance an ARQC (Authorisation Request Cryptogram).")]
    ARQC,

    /// <summary>
    /// Application Transaction Counter.
    /// Encoded/decoded by serializers as &quot;ATCC&quot;.
    /// </summary>
    [EnumMember(Value = "ATCC")]
    [IsoId("_ExternalAuthenticationMethodCode_ATC")]
    [Description(@"Application Transaction Counter.")]
    ATC,

    /// <summary>
    /// A value is used to verify an already performed authentication, used for non ThreeDS related authentication.
    /// Encoded/decoded by serializers as &quot;AUVA&quot;.
    /// </summary>
    [EnumMember(Value = "AUVA")]
    [IsoId("_ExternalAuthenticationMethodCode_AuthenticationValue")]
    [Description(@"A value is used to verify an already performed authentication, used for non ThreeDS related authentication.")]
    AuthenticationValue,

    /// <summary>
    /// Biometric authentication of the cardholder.
    /// Encoded/decoded by serializers as &quot;BIOM&quot;.
    /// </summary>
    [EnumMember(Value = "BIOM")]
    [IsoId("_ExternalAuthenticationMethodCode_Biometry")]
    [Description(@"Biometric authentication of the cardholder.")]
    Biometry,

    /// <summary>
    /// Date of birth of a person.
    /// Encoded/decoded by serializers as &quot;BTHD&quot;.
    /// </summary>
    [EnumMember(Value = "BTHD")]
    [IsoId("_ExternalAuthenticationMethodCode_BirthDate")]
    [Description(@"Date of birth of a person.")]
    BirthDate,

    /// <summary>
    /// Consumer Device Cardholder Verification Method.
    /// Encoded/decoded by serializers as &quot;CDCM&quot;.
    /// </summary>
    [EnumMember(Value = "CDCM")]
    [IsoId("_ExternalAuthenticationMethodCode_CDCVM")]
    [Description(@"Consumer Device Cardholder Verification Method.")]
    CDCVM,

    /// <summary>
    /// Cardholder data provided for verification.
    /// Encoded/decoded by serializers as &quot;CDHI&quot;.
    /// </summary>
    [EnumMember(Value = "CDHI")]
    [IsoId("_ExternalAuthenticationMethodCode_CardholderIdentificationData")]
    [Description(@"Cardholder data provided for verification.")]
    CardholderIdentificationData,

    /// <summary>
    /// Name of cardholder.
    /// Encoded/decoded by serializers as &quot;CHDN&quot;.
    /// </summary>
    [EnumMember(Value = "CHDN")]
    [IsoId("_ExternalAuthenticationMethodCode_CardholderName")]
    [Description(@"Name of cardholder.")]
    CardholderName,

    /// <summary>
    /// Cardholder address.
    /// Encoded/decoded by serializers as &quot;CHSA&quot;.
    /// </summary>
    [EnumMember(Value = "CHSA")]
    [IsoId("_ExternalAuthenticationMethodCode_CardholderAddress")]
    [Description(@"Cardholder address.")]
    CardholderAddress,

    /// <summary>
    /// Serial Number of the cardholder’s certificate.
    /// Encoded/decoded by serializers as &quot;CHSN&quot;.
    /// </summary>
    [EnumMember(Value = "CHSN")]
    [IsoId("_ExternalAuthenticationMethodCode_CardholderCertificateSerialNumber")]
    [Description(@"Serial Number of the cardholder’s certificate.")]
    CardholderCertificateSerialNumber,

    /// <summary>
    /// Registration number of a company.
    /// Encoded/decoded by serializers as &quot;CPNY&quot;.
    /// </summary>
    [EnumMember(Value = "CPNY")]
    [IsoId("_ExternalAuthenticationMethodCode_CompanyRegistrationNumber")]
    [Description(@"Registration number of a company.")]
    CompanyRegistrationNumber,

    /// <summary>
    /// Electronic signature capture (handwritten signature).
    /// Encoded/decoded by serializers as &quot;CPSG&quot;.
    /// </summary>
    [EnumMember(Value = "CPSG")]
    [IsoId("_ExternalAuthenticationMethodCode_SignatureCapture")]
    [Description(@"Electronic signature capture (handwritten signature).")]
    SignatureCapture,

    /// <summary>
    /// Verification of Card Security Code.
    /// Encoded/decoded by serializers as &quot;CSCV&quot;.
    /// </summary>
    [EnumMember(Value = "CSCV")]
    [IsoId("_ExternalAuthenticationMethodCode_CSCVerification")]
    [Description(@"Verification of Card Security Code.")]
    CSCVerification,

    /// <summary>
    /// Authentication performed during a secure electronic commerce transaction.
    /// Encoded/decoded by serializers as &quot;CSEC&quot;.
    /// </summary>
    [EnumMember(Value = "CSEC")]
    [IsoId("_ExternalAuthenticationMethodCode_SecureElectronicCommerce")]
    [Description(@"Authentication performed during a secure electronic commerce transaction.")]
    SecureElectronicCommerce,

    /// <summary>
    /// Customer number used as a mechanism of authentication.
    /// Encoded/decoded by serializers as &quot;CUID&quot;.
    /// </summary>
    [EnumMember(Value = "CUID")]
    [IsoId("_ExternalAuthenticationMethodCode_CustomerIdentification")]
    [Description(@"Customer number used as a mechanism of authentication.")]
    CustomerIdentification,

    /// <summary>
    /// Number assigned by a driving license authority to a person.
    /// Encoded/decoded by serializers as &quot;DRID&quot;.
    /// </summary>
    [EnumMember(Value = "DRID")]
    [IsoId("_ExternalAuthenticationMethodCode_DriverLicenseNumber")]
    [Description(@"Number assigned by a driving license authority to a person.")]
    DriverLicenseNumber,

    /// <summary>
    /// Identification of a driver in a fleet of vehicles.
    /// Encoded/decoded by serializers as &quot;DRVI&quot;.
    /// </summary>
    [EnumMember(Value = "DRVI")]
    [IsoId("_ExternalAuthenticationMethodCode_DriverIdentification")]
    [Description(@"Identification of a driver in a fleet of vehicles.")]
    DriverIdentification,

    /// <summary>
    /// Electronic mail address.
    /// Encoded/decoded by serializers as &quot;EMAL&quot;.
    /// </summary>
    [EnumMember(Value = "EMAL")]
    [IsoId("_ExternalAuthenticationMethodCode_Email")]
    [Description(@"Electronic mail address.")]
    Email,

    /// <summary>
    /// Number assigned to an employee by an employer.
    /// Encoded/decoded by serializers as &quot;EMIN&quot;.
    /// </summary>
    [EnumMember(Value = "EMIN")]
    [IsoId("_ExternalAuthenticationMethodCode_EmployeeIdentificationNumber")]
    [Description(@"Number assigned to an employee by an employer.")]
    EmployeeIdentificationNumber,

    /// <summary>
    /// Number assigned to an employer by a registration authority.
    /// Encoded/decoded by serializers as &quot;EMRN&quot;.
    /// </summary>
    [EnumMember(Value = "EMRN")]
    [IsoId("_ExternalAuthenticationMethodCode_EmployerIdentificationNumber")]
    [Description(@"Number assigned to an employer by a registration authority.")]
    EmployerIdentificationNumber,

    /// <summary>
    /// Biographics authentication in an offline mode.
    /// Encoded/decoded by serializers as &quot;FBIG&quot;.
    /// </summary>
    [EnumMember(Value = "FBIG")]
    [IsoId("_ExternalAuthenticationMethodCode_OffLineBiographics")]
    [Description(@"Biographics authentication in an offline mode.")]
    OffLineBiographics,

    /// <summary>
    /// Biometrics authentication in an offline mode.
    /// Encoded/decoded by serializers as &quot;FBIO&quot;.
    /// </summary>
    [EnumMember(Value = "FBIO")]
    [IsoId("_ExternalAuthenticationMethodCode_OffLineBiometrics")]
    [Description(@"Biometrics authentication in an offline mode.")]
    OffLineBiometrics,

    /// <summary>
    /// PIN generated offline and transmitted in clear
    /// Encoded/decoded by serializers as &quot;FCPN&quot;.
    /// </summary>
    [EnumMember(Value = "FCPN")]
    [IsoId("_ExternalAuthenticationMethodCode_OffLinePINInClear")]
    [Description(@"PIN generated offline and transmitted in clear")]
    OffLinePINInClear,

    /// <summary>
    /// Off-line PIN authentication (Personal Identification Number).
    /// Encoded/decoded by serializers as &quot;FPIN&quot;.
    /// </summary>
    [EnumMember(Value = "FPIN")]
    [IsoId("_ExternalAuthenticationMethodCode_OfflinePIN")]
    [Description(@"Off-line PIN authentication (Personal Identification Number).")]
    OfflinePIN,

    /// <summary>
    /// Number assigned by a national authority to an identity card.
    /// Encoded/decoded by serializers as &quot;IDCN&quot;.
    /// </summary>
    [EnumMember(Value = "IDCN")]
    [IsoId("_ExternalAuthenticationMethodCode_IdentityCardNumber")]
    [Description(@"Number assigned by a national authority to an identity card.")]
    IdentityCardNumber,

    /// <summary>
    /// Identification of law enforcement.
    /// Encoded/decoded by serializers as &quot;LAWE&quot;.
    /// </summary>
    [EnumMember(Value = "LAWE")]
    [IsoId("_ExternalAuthenticationMethodCode_LawEnforcementIdentification")]
    [Description(@"Identification of law enforcement.")]
    LawEnforcementIdentification,

    /// <summary>
    /// Manual verification, for example passport or drivers license.
    /// Encoded/decoded by serializers as &quot;MANU&quot;.
    /// </summary>
    [EnumMember(Value = "MANU")]
    [IsoId("_ExternalAuthenticationMethodCode_ManualVerification")]
    [Description(@"Manual verification, for example passport or drivers license.")]
    ManualVerification,

    /// <summary>
    /// Identification of military.
    /// Encoded/decoded by serializers as &quot;MILI&quot;.
    /// </summary>
    [EnumMember(Value = "MILI")]
    [IsoId("_ExternalAuthenticationMethodCode_MilitaryIdentification")]
    [Description(@"Identification of military.")]
    MilitaryIdentification,

    /// <summary>
    /// Customer mobile phone number.
    /// Encoded/decoded by serializers as &quot;MOBL&quot;.
    /// </summary>
    [EnumMember(Value = "MOBL")]
    [IsoId("_ExternalAuthenticationMethodCode_PhoneMobile")]
    [Description(@"Customer mobile phone number.")]
    PhoneMobile,

    /// <summary>
    /// Biographics authentication in an online mode.
    /// Encoded/decoded by serializers as &quot;NBIG&quot;.
    /// </summary>
    [EnumMember(Value = "NBIG")]
    [IsoId("_ExternalAuthenticationMethodCode_OnLineBiographics")]
    [Description(@"Biographics authentication in an online mode.")]
    OnLineBiographics,

    /// <summary>
    /// On-line PIN authentication (Personal Identification Number).
    /// Encoded/decoded by serializers as &quot;NPIN&quot;.
    /// </summary>
    [EnumMember(Value = "NPIN")]
    [IsoId("_ExternalAuthenticationMethodCode_OnLinePIN")]
    [Description(@"On-line PIN authentication (Personal Identification Number).")]
    OnLinePIN,

    /// <summary>
    /// National Identifier.
    /// Encoded/decoded by serializers as &quot;NTID&quot;.
    /// </summary>
    [EnumMember(Value = "NTID")]
    [IsoId("_ExternalAuthenticationMethodCode_NationalIdentifer")]
    [Description(@"National Identifier.")]
    NationalIdentifer,

    /// <summary>
    /// Non visible Card Security Code.
    /// Encoded/decoded by serializers as &quot;NVSC&quot;.
    /// </summary>
    [EnumMember(Value = "NVSC")]
    [IsoId("_ExternalAuthenticationMethodCode_NonVisibleCSC")]
    [Description(@"Non visible Card Security Code.")]
    NonVisibleCSC,

    /// <summary>
    /// Other cardholder data provided for identification.
    /// Encoded/decoded by serializers as &quot;OCHI&quot;.
    /// </summary>
    [EnumMember(Value = "OCHI")]
    [IsoId("_ExternalAuthenticationMethodCode_OtherCardholderIdentification")]
    [Description(@"Other cardholder data provided for identification.")]
    OtherCardholderIdentification,

    /// <summary>
    /// PIN generated offline and transmitted encrypted.
    /// Encoded/decoded by serializers as &quot;OFPE&quot;.
    /// </summary>
    [EnumMember(Value = "OFPE")]
    [IsoId("_ExternalAuthenticationMethodCode_OffLinePINEncrypted")]
    [Description(@"PIN generated offline and transmitted encrypted.")]
    OffLinePINEncrypted,

    /// <summary>
    /// Authentication of data in an offline mode.
    /// Encoded/decoded by serializers as &quot;OLDA&quot;.
    /// </summary>
    [EnumMember(Value = "OLDA")]
    [IsoId("_ExternalAuthenticationMethodCode_OffLineDataAuthentication")]
    [Description(@"Authentication of data in an offline mode.")]
    OffLineDataAuthentication,

    /// <summary>
    /// Analysis of signature transmitted offline.
    /// Encoded/decoded by serializers as &quot;OLDS&quot;.
    /// </summary>
    [EnumMember(Value = "OLDS")]
    [IsoId("_ExternalAuthenticationMethodCode_OffLineDigitisedSignatureAnalysis")]
    [Description(@"Analysis of signature transmitted offline.")]
    OffLineDigitisedSignatureAnalysis,

    /// <summary>
    /// Other type of verification defined at national level.
    /// Encoded/decoded by serializers as &quot;OTHN&quot;.
    /// </summary>
    [EnumMember(Value = "OTHN")]
    [IsoId("_ExternalAuthenticationMethodCode_OtherNational")]
    [Description(@"Other type of verification defined at national level.")]
    OtherNational,

    /// <summary>
    /// Other type of verification defined at private level.
    /// Encoded/decoded by serializers as &quot;OTHP&quot;.
    /// </summary>
    [EnumMember(Value = "OTHP")]
    [IsoId("_ExternalAuthenticationMethodCode_OtherPrivate")]
    [Description(@"Other type of verification defined at private level.")]
    OtherPrivate,

    /// <summary>
    /// Verification of a one-time password provided by the issuer.
    /// Encoded/decoded by serializers as &quot;OTPW&quot;.
    /// </summary>
    [EnumMember(Value = "OTPW")]
    [IsoId("_ExternalAuthenticationMethodCode_OneTimePassword")]
    [Description(@"Verification of a one-time password provided by the issuer.")]
    OneTimePassword,

    /// <summary>
    /// Number assigned by a passport authority to a passport.
    /// Encoded/decoded by serializers as &quot;PASS&quot;.
    /// </summary>
    [EnumMember(Value = "PASS")]
    [IsoId("_ExternalAuthenticationMethodCode_PassportNumber")]
    [Description(@"Number assigned by a passport authority to a passport.")]
    PassportNumber,

    /// <summary>
    /// Verification based on digits of the postal code.
    /// Encoded/decoded by serializers as &quot;PCDV&quot;.
    /// </summary>
    [EnumMember(Value = "PCDV")]
    [IsoId("_ExternalAuthenticationMethodCode_PostalCode")]
    [Description(@"Verification based on digits of the postal code.")]
    PostalCode,

    /// <summary>
    /// Generical phone number.
    /// Encoded/decoded by serializers as &quot;PHNB&quot;.
    /// </summary>
    [EnumMember(Value = "PHNB")]
    [IsoId("_ExternalAuthenticationMethodCode_PhoneNumber")]
    [Description(@"Generical phone number.")]
    PhoneNumber,

    /// <summary>
    /// Customer home phone number.
    /// Encoded/decoded by serializers as &quot;PHOM&quot;.
    /// </summary>
    [EnumMember(Value = "PHOM")]
    [IsoId("_ExternalAuthenticationMethodCode_PhoneHome")]
    [Description(@"Customer home phone number.")]
    PhoneHome,

    /// <summary>
    /// PKI (Public Key Infrastructure) based digital signature.
    /// Encoded/decoded by serializers as &quot;PKIS&quot;.
    /// </summary>
    [EnumMember(Value = "PKIS")]
    [IsoId("_ExternalAuthenticationMethodCode_PKISignature")]
    [Description(@"PKI (Public Key Infrastructure) based digital signature.")]
    PKISignature,

    /// <summary>
    /// Place of birth of a person.
    /// Encoded/decoded by serializers as &quot;PLOB&quot;.
    /// </summary>
    [EnumMember(Value = "PLOB")]
    [IsoId("_ExternalAuthenticationMethodCode_PlaceOfBirth")]
    [Description(@"Place of birth of a person.")]
    PlaceOfBirth,

    /// <summary>
    /// Handwritten paper signature.
    /// Encoded/decoded by serializers as &quot;PPSG&quot;.
    /// </summary>
    [EnumMember(Value = "PPSG")]
    [IsoId("_ExternalAuthenticationMethodCode_PaperSignature")]
    [Description(@"Handwritten paper signature.")]
    PaperSignature,

    /// <summary>
    /// Proxy.
    /// Encoded/decoded by serializers as &quot;PRXY&quot;.
    /// </summary>
    [EnumMember(Value = "PRXY")]
    [IsoId("_ExternalAuthenticationMethodCode_Proxy")]
    [Description(@"Proxy.")]
    Proxy,

    /// <summary>
    /// Authentication by a passcode.
    /// Encoded/decoded by serializers as &quot;PSCD&quot;.
    /// </summary>
    [EnumMember(Value = "PSCD")]
    [IsoId("_ExternalAuthenticationMethodCode_Passcode")]
    [Description(@"Authentication by a passcode.")]
    Passcode,

    /// <summary>
    /// Authentication based on statistical cardholder behaviour.
    /// Encoded/decoded by serializers as &quot;PSVE&quot;.
    /// </summary>
    [EnumMember(Value = "PSVE")]
    [IsoId("_ExternalAuthenticationMethodCode_PassiveAuthentication")]
    [Description(@"Authentication based on statistical cardholder behaviour.")]
    PassiveAuthentication,

    /// <summary>
    /// Authentication by a password.
    /// Encoded/decoded by serializers as &quot;PSWD&quot;.
    /// </summary>
    [EnumMember(Value = "PSWD")]
    [IsoId("_ExternalAuthenticationMethodCode_Password")]
    [Description(@"Authentication by a password.")]
    Password,

    /// <summary>
    /// Customer business phone number.
    /// Encoded/decoded by serializers as &quot;PWOR&quot;.
    /// </summary>
    [EnumMember(Value = "PWOR")]
    [IsoId("_ExternalAuthenticationMethodCode_PhoneBusiness")]
    [Description(@"Customer business phone number.")]
    PhoneBusiness,

    /// <summary>
    /// Qualified Certificate.
    /// Encoded/decoded by serializers as &quot;QWAC&quot;.
    /// </summary>
    [EnumMember(Value = "QWAC")]
    [IsoId("_ExternalAuthenticationMethodCode_QualifiedCertificate")]
    [Description(@"Qualified Certificate.")]
    QualifiedCertificate,

    /// <summary>
    /// Channel-encrypted transaction.
    /// Encoded/decoded by serializers as &quot;SCNL&quot;.
    /// </summary>
    [EnumMember(Value = "SCNL")]
    [IsoId("_ExternalAuthenticationMethodCode_SecuredChannel")]
    [Description(@"Channel-encrypted transaction.")]
    SecuredChannel,

    /// <summary>
    /// Electronic commerce transaction secured with the X.509 certificate of a customer.
    /// Encoded/decoded by serializers as &quot;SCRT&quot;.
    /// </summary>
    [EnumMember(Value = "SCRT")]
    [IsoId("_ExternalAuthenticationMethodCode_SecureCertificate")]
    [Description(@"Electronic commerce transaction secured with the X.509 certificate of a customer.")]
    SecureCertificate,

    /// <summary>
    /// Shipping address from verification.
    /// Encoded/decoded by serializers as &quot;SHAF&quot;.
    /// </summary>
    [EnumMember(Value = "SHAF")]
    [IsoId("_ExternalAuthenticationMethodCode_ShippingAddressFrom")]
    [Description(@"Shipping address from verification.")]
    ShippingAddressFrom,

    /// <summary>
    /// Shipping address to verification
    /// Encoded/decoded by serializers as &quot;SHAT&quot;.
    /// </summary>
    [EnumMember(Value = "SHAT")]
    [IsoId("_ExternalAuthenticationMethodCode_ShippingAddressTo")]
    [Description(@"Shipping address to verification")]
    ShippingAddressTo,

    /// <summary>
    /// Number assigned by a social security agency.
    /// Encoded/decoded by serializers as &quot;SSYN&quot;.
    /// </summary>
    [EnumMember(Value = "SSYN")]
    [IsoId("_ExternalAuthenticationMethodCode_SocialSecurityNumber")]
    [Description(@"Number assigned by a social security agency.")]
    SocialSecurityNumber,

    /// <summary>
    /// A value used to validate the authorised use of a token.
    /// Encoded/decoded by serializers as &quot;TAVV&quot;.
    /// </summary>
    [EnumMember(Value = "TAVV")]
    [IsoId("_ExternalAuthenticationMethodCode_TokenAuthenticationValue")]
    [Description(@"A value used to validate the authorised use of a token.")]
    TokenAuthenticationValue,

    /// <summary>
    /// Authentication performed during a secure electronic commerce transaction.
    /// Encoded/decoded by serializers as &quot;THDS&quot;.
    /// </summary>
    [EnumMember(Value = "THDS")]
    [IsoId("_ExternalAuthenticationMethodCode_ThreeDS")]
    [Description(@"Authentication performed during a secure electronic commerce transaction.")]
    ThreeDS,

    /// <summary>
    /// Identification used for travel.
    /// Encoded/decoded by serializers as &quot;TRVL&quot;.
    /// </summary>
    [EnumMember(Value = "TRVL")]
    [IsoId("_ExternalAuthenticationMethodCode_TravelIdentification")]
    [Description(@"Identification used for travel.")]
    TravelIdentification,

    /// <summary>
    /// Number assigned by a tax authority to an entity.
    /// Encoded/decoded by serializers as &quot;TXID&quot;.
    /// </summary>
    [EnumMember(Value = "TXID")]
    [IsoId("_ExternalAuthenticationMethodCode_TaxIdentificationNumber")]
    [Description(@"Number assigned by a tax authority to an entity.")]
    TaxIdentificationNumber,

}
